### ISSUE TITLE
Problem running the test dataset command

### ISSUE THREAD

**Issue by dence** [BioInf-Wuerzburg/proovread#1]
Hi, when I ran command in the documentation to test whether proovread had installed correctly, I got this error: 

~/applications/proovread/bin/proovread --sample --pre /tmp/pr-sample
[Mon Mar 30 13:42:43 2015] Reading core config
[Mon Mar 30 13:42:43 2015] Reading command line options
#------------------------------------------------------------------------------#
  No such file or directory: `/tmp/pr-sample/tmp/pr-sample.parameter.log`
	Exited at 'main'
	'/home/dence/applications/proovread/bin/proovread', line 387

I figured that I should check the usage statement, so I did "proovread --help", and saw "--sample-run" as an option. Maybe this should be updated in the documentation?

**Comment by thackl** [comment]
Hi dence,

as you obviously found out, the problem is not with `--sample` but with the `/tmp/pr-sample` which should be `pr-sample`. A rather stupid mistake on my side. I fixed the call in the README.

Thanks a lot for reporting.
