### ISSUE TITLE
bam2cns

### ISSUE THREAD

**Issue by rebzzy** [BioInf-Wuerzburg/proovread#100]
Hi  -

I'm trying to follow the directions I found on this thread: https://www.biostars.org/p/155236/
However, I'm getting the following error and I have no idea how to fix it.

```
Fastq::Parser::new: broken_assembly.oneLine.fa.masked.fa, No such file or directory at /gscratch/leache/rbharris/bin/proovread/bin/../lib//Fastq/Parser.pm line 229, <SAM> line 18529.
Use of uninitialized value in numeric eq (==) at /gscratch/leache/rbharris/bin/proovread/bin/../lib//Fastq/Parser.pm line 694, <SAM> line 18529.
        (in cleanup) Can't use an undefined value as a symbol reference at /gscratch/leache/rbharris/bin/proovread/bin/../lib//Fastq/Parser.pm line 246, <SAM> line 18529.

```

Thanks!

**Comment by thackl** [comment]
Hi Rebecca,

I think that this is the important part of the error: 
`broken_assembly.oneLine.fa.masked.fa, No such file or directory`

The parser fails to open that fasta file. Are you sure it is typed 
correctly? Try to specify the complete 
/path/to/broken_assembly.oneLine.fa.masked.fa

Cheers
Thomas

**Comment by rebzzy** [comment]
Hi again - 
I'm getting a new error "[06:35:28] Unknown format of reference file". It's a fasta file and I don't see any flag to specify input format. Thanks for the help + quick response!

**Comment by thackl** [comment]
Sorry, I somehow missed your second message. Unknown format should mean it's neither fasta nor fastq. Can you send me the first lines of the file? (thackl@lim4.de)
