### ISSUE TITLE
Error: bam2cns unexpectedly returned

### ISSUE THREAD

**Issue by realseanla** [BioInf-Wuerzburg/proovread#101]
I'm receiving the following error message:
```
...
[Thu Apr 20 18:54:04 2017] Batch 411/2999
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/bam2cns --append 1 --bam proovread-yeast-200Sx50L/bwa-sr-3/proovread-ye\
ast-200Sx50L.bam --bin-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-we\
ak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --prefix proovread-yeast-200Sx\
50L/bwa-sr-3/proovread-yeast-200Sx50L.410 --qv-offset 33 --ref proovread-yeast-\
200Sx50L/bwa-sr-2/proovread-yeast-200Sx50L.fq --ref-offset 160792741
#------------------------------------------------------------------------------#
Warning: unable to close filehandle properly: Disk quota exceeded during global\
 destruction.
#------------------------------------------------------------------------------#
[Thu Apr 20 18:54:29 2017] bam2cns unexpectedly returned
        Exited at 'main'
        '/home/seanla/Software/proovread/bin/proovread', line 1634
        Last call 'main::correct_sr_mt'
        '/home/seanla/Software/proovread/bin/proovread', line 868                                                                          
```

Any help resolving this error would be appreciated! Thanks.

**Comment by thackl** [comment]
That's a weird one. I'm not entirely sure what it causing this, but my guess is that it has something to do with too many open files. Looks like you are correcting a very large batch of sequences. 

1) You might wanna check the recommendations on limits for chunk sizes (https://github.com/BioInf-Wuerzburg/proovread#getting-chunk-sizes-right-48). You seem to correct much more than 1X of Yeast PacBio data in one go. Using less data should already solve the issue.

2) You can increase the following value in the proovread.cfg:
```
## Number of reads to check out at once for individual consensus correction 
##  process. Memory intensive step, be cautios with great values
'chunk-size' => 100, # <= increase to 1000
```

3) This is a warning, not sure if it actually has any negative affect on the execution of the program. It wouldn't be to hard to make proovread simply ignore it. Let me know if you want to go down that road.
