### ISSUE TITLE
Estimating short read quality offset failed.

### ISSUE THREAD

**Issue by sybsun** [BioInf-Wuerzburg/proovread#104]
syb@thinkstation:~/software/proovread$ bin/proovread -l sample/long_error.fq -s sample/short.fq --pre long_error
[Fri Jun 16 17:22:49 2017] Running proovread-2.14.0 under Perl 5.22.1
[Fri Jun 16 17:22:49 2017] Reading core config
[Fri Jun 16 17:22:49 2017] Reading command line options
[Fri Jun 16 17:22:49 2017] Logging parameter to `long_error/long_error.parameter
.log`
[Fri Jun 16 17:22:49 2017] Checking short read files
  
short.fq
  Detected FASTQ format
  Estimated short read length: 100 +-0
#------------------------------------------------------------------------------#
  Estimating short read quality offset failed.
See 'sr-qv-offset' in the advanced section for manual overwrite
	Exited at 'main'
	'bin/proovread', line 469

**Comment by thackl** [comment]
As the message suggests, set `--sr-qv-offset` by hand, i.e. most likely `--sr-qv-offset 33` or 64, depending on the encoding of quality values in your illumina files.

**Comment by sybsun** [comment]
Thanks! I had set  --sr-qv-offset 33, but encounter new problem.

sunyangbo@thinkstation:~/software/proovread$ bin/proovread -l sample/long_error.fq -s sample/short.fq --pre long-error
[Tue Jun 20 15:26:12 2017] Running proovread-2.14.0 under Perl 5.22.1
[Tue Jun 20 15:26:12 2017] Reading core config
[Tue Jun 20 15:26:12 2017] Reading command line options
[Tue Jun 20 15:26:12 2017] Logging parameter to `long-error/long-error.parameter
.log`
[Tue Jun 20 15:26:12 2017] Checking short read files
  
short.fq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 50.0k

[Tue Jun 20 15:26:12 2017] Checking required binaries

  [ok] samtools-1.4.1  /usr/local/bin
  [ok] bwa-proovread   /home/syb/software/proovread/bin/../util/bwa
  [ok] blastn-2.2.31   /usr/bin

[Tue Jun 20 15:26:12 2017] Running mode: sr
[Tue Jun 20 15:26:12 2017] Preparing long reads
#------------------------------------------------------------------------------#
perl -I/home/syb/software/proovread/bin/../lib/ /home/syb/software/\
proovread/bin/SeqFilter --fasta --in long-error/read-long/long-error.fq --line-\
width 80 --lower-case --out long-error/read-long/long-error.masked.fa --phred-o\
ffset 33
syntax error at /home/syb/software/proovread/bin/SeqFilter line 1, near ".."
Unknown regexp modifier "/S" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
Unknown regexp modifier "/e" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
Unknown regexp modifier "/q" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
Unknown regexp modifier "/F" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
Unknown regexp modifier "/t" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
Unknown regexp modifier "/e" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
Unknown regexp modifier "/r" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
Unknown regexp modifier "/S" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
Unknown regexp modifier "/e" at /home/syb/software/proovread/bin/SeqFilter line 1, at end of line
/home/syb/software/proovread/bin/SeqFilter has too many errors.
#------------------------------------------------------------------------------#
[Tue Jun 20 15:26:12 2017] Read IDs don't look like proper PacBio subread IDs.
Falling back to running mode: sr-noccs

[Tue Jun 20 15:26:12 2017] Running task bwa-sr-1
[Tue Jun 20 15:26:12 2017] Indexing Long reads
#------------------------------------------------------------------------------#
/home/syb/software/proovread/bin/../util/bwa/bwa-proovread index long-err\
or/read-long/long-error.masked.fa long-error/read-long/long-error.masked.fa 2>l\
ong-error/bwa-sr-1/long-error_bwa.log
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
  
	Exited at 'main'
	'bin/proovread', line 1277
	Last call 'main::run_bwa'
	'bin/proovread', line 853

**Comment by thackl** [comment]
This is very weird. Can you open the `/home/syb/software/proovread/bin/SeqFilter` file and have a look at the first lines.  It should look like this:
```
#!/usr/bin/env perl

use warnings;
use strict;
```
Not sure how ".." could have ended up in your file.

**Comment by Hulanyue** [comment]
Hi!
I have the same problem,I want to konw how to set `--sr-qv-offset`,I set `--sr-qv-offset`in terminal ,it show me `command not found`

**Comment by Hulanyue** [comment]
OK!I have set `--sr-qv-offset` by hand ,thank you!
