### ISSUE TITLE
FILE should be located at './bin/SeqChunker'

### ISSUE THREAD

**Issue by sybsun** [BioInf-Wuerzburg/proovread#105]
I had run using below command, and received the following error"FILE should be located at './bin/SeqChunker'" Could u tell me how to use or where wrong I have? Thank u.
syb@thinkstation:~/software/proovread/util/SeqChunker$ ./bin/SeqChunker -s 20M -o F.antasticus_long_error.fq

**Comment by thackl** [comment]
That is not an error, just a regular log message. Could you post the complete log of the run?
