### ISSUE TITLE
bam2cns unexpectedly returned

### ISSUE THREAD

**Issue by symcong** [BioInf-Wuerzburg/proovread#108]
[main_samview] region "i1_c122/f71p15/1555:" specifies an unknown reference nam\
e. Continue anyway.
#------------------------------------------------------------------------------#
[Wed Aug 30 13:47:13 2017] bam2cns unexpectedly returned
	Exited at 'main'
	'/PUBLIC/software/PB/pipeline/Pacbio_Isoseq_V2.0/software/proovread/proovread/b
in/proovread', line 1634
	Last call 'main::correct_sr_mt'
	'/PUBLIC/software/PB/pipeline/Pacbio_Isoseq_V2.0/software/proovread/proovread/b
in/proovread', line 868
please help me solve the error，thank you very much！

**Comment by thackl** [comment]
sorry for the delayed reply, I just returned from a longer vacation. Do you still need help with this problem? If so, can you send me the full log of the run that failed?
