### ISSUE TITLE
error while running bam2cns

### ISSUE THREAD

**Issue by nam183** [BioInf-Wuerzburg/proovread#109]
I am running bam2cns to generate consensus from bam file generated using bwa and illumina data, and i am getting following error in Seq.pm

Use of uninitialized value $cigar[1] in string eq at /Downloads/proovread/bin/../lib/Sam/Seq.pm line 290, <SAM> line 3768977
.
.
Sam::Seq::State_matrixEmpty Cigar at /Downloads/proovread/bin/../lib/Sam/Seq.pm line 313, <SAM> line 3768977.

Please help me how can i solve this error?

Thank You

**Comment by thackl** [comment]
There seems to be a problem with parsing your bam file. Can you try and filter and remove unmapped and secondary/supplementary alignments first?
```
samtools view -bF 2308 my.bam -o my-filtered.bam
```

**Comment by nam183** [comment]
Thank You, removing secondary alignments worked for me.
Actually i am following this thread [https://www.biostars.org/p/155236/](url)

I have successfully run bam2cns, and now i have cns.fq file of size around 5 Gb, and to run this file with SeqFilter howmuch minimum memory is required, because i am running it in my server having 1 TB RAM and it is getting killed.
How can i run the command with big genome size?

Thank You

**Comment by thackl** [comment]
You will have to use another tool for trimming low quality regions. SeqFilter is not built to handle sequences of that size. Sorry...
