### ISSUE TITLE
changing temp folder

### ISSUE THREAD

**Issue by slhellmann** [BioInf-Wuerzburg/proovread#111]
Hi Thomas,

I am using proovread on a slurm cluster. As our filesystem tends to be rather slow, I'd like to save the temporary files to memory rather than disk. How can I do this?

Best,
Lukas

**Comment by thackl** [comment]
Hi Lukas,

I haven't implemented a way that let's you put temporary files elsewhere. Everything is done in the folder specified by --pre. But I would suggest to try out the following workaround. Wrap the call to proovread into a bash script, write the entire output of proovread into RAM, and after the run finished, move the non-temporary data to some location on the disk. This should work well as long as you have enough memory.

```
#!/usr/bin/env bash

# run proovread in ram
proovread --pre /dev/shm/my-run-01 --sample-run
# mv save to disk
mv /dev/shm/my-run-01 /somewhere/on/disk/.
```

**Comment by slhellmann** [comment]
It worked as described.
Thank you Thomas!

**Comment by thackl** [comment]
Happy to hear. Thanks for the feedback.
