### ISSUE TITLE
the meaning of the sequence name of the output

### ISSUE THREAD

**Issue by shenghuizhoucaas** [BioInf-Wuerzburg/proovread#115]
Dear,
i want to know the meaning of the sequence name of output file. Such as the difference between  ">c0/f1p54/17291.1.1 SUBSTR:0,5481 SUBSTR:3919,1562" and ">c0/f1p54/17291.1.2 SUBSTR:0,5481 SUBSTR:1449,649".
Best regards.

**Comment by thackl** [comment]
Sorry for the very late answer... The IDs and description indicate how the read has been cut by proovread. There are two steps in the pipeline that can lead to cutting reads - chimera detection and trimming. The read at hand has been cut in both steps  - every time a cut happened the ID has been appended by a `.X` (1, 2, ... different pieces). The first `SUBSTR:0,5481` indicates the coordinates of the first cutting operation in perl-style `substr` notation: start (0-offset), length, and with respect to how the read looked like at that stage of correction (NOTE that removing indels during correction slightly shifts coordinates between original and corrected reads). The second `SUBSTR` fields indicate the coordinates of the two high-quality pieces that were cut out from the read created during the first cutting operation, i.e. the trimming operation. One piece starts at 1449 and with length 649 bp, and a second high-quality piece starts at 3913, with length 1562.

Hope that helps!
