### ISSUE TITLE
make: *** [util] Error 1

### ISSUE THREAD

**Issue by jazberna1** [BioInf-Wuerzburg/proovread#119]
Hello, 

I get the error pasted below after running the 'make' command. Do you happen to know if I am missing something? i.e. dependencies.

Thanks
Jorge

make
git submodule init
git submodule update --force
Usage: git submodule [--quiet] add [-b branch] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] update [--init] [-N|--no-fetch] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--] [<path>...]
make: *** [util] Error 1

**Comment by jazberna1** [comment]
Hi,

I removed '--force' from the git calls, probably that will make it work.

Jorge

**Comment by thackl** [comment]
Yes, I think `--force` is not supported in some git submodule versions.
