### ISSUE TITLE
Unexpectedly dropped all alignments during processing and BLAST engine error:  Sequence contains no data

### ISSUE THREAD

**Issue by litianqi715** [BioInf-Wuerzburg/proovread#12]
Hi,
I recently changed my computing environment, which is now Red Hat Enterprise Linux Server release 6.6 (Santiago), gcc 4.4.7-11, perl 5.10.1, samtools 1.2, ncbi-blast+2.2.31. This time my 20M reads runs give out some errors llike this:

[Tue Jul 28 00:59:29 2015] Quality trimming and siamaera filtering raw output
#------------------------------------------------------------------------------#
perl -I/public/home/wangrj/program/proovread/bin/../lib/ /public/home/wangrj/pr\
ogram/proovread/bin/SeqFilter --in pb052015-0052/pb052015-0052.untrimmed.fq --m\
in-length 500 --phred-offset 33 --substr pb052015-0052/pb052015-0052.chim.tsv -\
-trim-win 12,5 --out - | perl -I/public/home/wangrj/program/proovread/bin/../li\
b/ /public/home/wangrj/program/proovread/bin/siamaera > pb052015-0052/pb052015-\
0052.trimmed.fq
[00:59:29] /public/home/wangrj/program/proovread/bin/SeqFilter-1.06
[00:59:29] --in: pb052015-0052/pb052015-0052.untrimmed.fq
[00:59:29] Detected FASTQ format, phred-offset 33
[00:59:29] --substr-file: pb052015-0052/pb052015-0052.chim.tsv
    0  [                                                          ]^M  332k [=>                                                        ] ETA 00:05:36Warning: [blastn] Subject_1 m150525_092658_42146_c100815402550000001823183910291513_s1_p0/139315/25301_37450.1.3: Subject sequence contians no data
^M  620k [==>                                                       ] ETA 00:05:30^M  935k [===>                                                      ] ETA 00:05:24^M 1.26M [====>                                                     ] ETA 00:05:31Warning: [blastn] Subject_1 m150525_092658_42146_c100815402550000001823183910291513_s1_p0/139416/13951_29484.1: Subject sequence contians no data
^M 1.57M [=====>                                                    ] ETA 00:05:32^M 1.86M [======>                                                   ] ETA 00:05:31^M 2.19M [=======>                                                  ] ETA 00:05:21BLAST engine error: Warning: Sequence contains no data 
[15-07-28 01:00:15] [siamaera] Blast exited with error: 768 
#------------------------------------------------------------------------------#

Some other times it give out another form of error like this:

[Sat Jul 25 21:05:28 2015] Quality trimming and siamaera filtering raw output
#------------------------------------------------------------------------------#
perl -I/public/home/wangrj/program/proovread/bin/../lib/ /public/home/wangrj/pr\
ogram/proovread/bin/SeqFilter --in pb052015-1/pb052015-1.untrimmed.fq --min-len\
gth 500 --phred-offset 33 --substr pb052015-1/pb052015-1.chim.tsv --trim-win 12\
,5 --out - | perl -I/public/home/wangrj/program/proovread/bin/../lib/ /public/h\
ome/wangrj/program/proovread/bin/siamaera > pb052015-1/pb052015-1.trimmed.fq
[21:05:29] /public/home/wangrj/program/proovread/bin/SeqFilter-1.06
[21:05:29] --in: pb052015-1/pb052015-1.untrimmed.fq
[21:05:29] Detected FASTQ format, phred-offset 33
[21:05:29] --substr-file: pb052015-1/pb052015-1.chim.tsv
    0  [                                                          ]BLAST engine error: Warning: Sequence contains no data 
[15-07-25 21:19:55] [siamaera] Blast exited with error: 768 
#------------------------------------------------------------------------------#

Other times it just gave out:

 7.30M [========================>                            
     ] ETA 00:07:15^M 7.61M [=========================>                                ] ETA 00:07:02[15-07-27 20:01:08] [siamaera] Unexpectedly dropped all alignments during processing: m150521_061840_42146_c100828742550000001823180311251520_s1_p0/109715/6389_9635.1
^M 7.90M [==========================>                               ] ETA 00:06:47^M 8.20M [===========================>                              ]
and finish normally but with a short N50 of less than 3kb.

I have also tried ncbi-blast+ version 2.2.28 and 2.2.30, which is the version used in my old environment. They gave out the same errors. 
All runs can finish with the errors and give out a result N50 of less than 3kb and ~70% total sequences remains. 
In my old environment, however, all runs is normal with a result N50 of ~6kb and ~80% sequences remains.

I don't know where the problem lies and how to fix it now. Can you give me some suggestions?

Thanks.

Tianqi Li

**Comment by thackl** [comment]
Hi Tianqi,

first, sorry for the inconvenience. It's most likely a bash issue - which bash version do you have - I'm using a dirty hack to run a self-comparision blast for each sequence without temporary files. Can you put the following code snippet into a file (blast.pl)

``` perl
#!/usr/bin/env perl
use warnings;
use strict;

use Fasta::Parser;

my $fp = Fasta::Parser->new(file => $ARGV[0]);

while (my $fa = $fp->next_seq) {
    print blast("$fa");
}

sub blast{
    my ($seq) = @_;
    my $cmd = "SEQ=\"$seq\" && ".q/
blastn \
-subject <(echo "$SEQ") \
-query <(echo "$SEQ")
/;

    print "#-- cmd: ".("-"x52)."#\n";
    print "$cmd";
    print "#".("-"x60)."#\n\n";

    my @blastre = qx( bash -c '$cmd' );
}
```

and run it with a test.fasta file - any random fasta file should do, maybe start with a single, short sequence.

``` sh
perl -I/path/to/proovread-installation/lib/ blast.pl < test.fasta
```

**Comment by litianqi715** [comment]
Hi,
my shell version is GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu) and it is the same as my old environment.
I make the script blast.pl and run command 
perl -I/home/wangrj/program/proovread/lib/ blast.pl < test.fasta >test.log 2>&1

Content of test.log is as follows:

#-- cmd: ----------------------------------------------------#
SEQ=">ctg7180014845866
GCATATTCTGTATTGGGTTTAACACTTGAATGATGACTGTGGAATACTTGTTGCTTGTTGGTCACAAAAGAGTTACCATTGGGTTTTTTTAAATCTTTATTGCATTTTTTTTAACTTTTTAATTTCACTGTTTACATACTTCTGAATTTTTTTTGGACTATATGCGTTCAGCTTTTTTATTTATTTTTTACATATATTTTTTTTATTGTCGTTTAGTACGGGTCTTTTTAATACTGTTCCTTTAGGCTTTGACATTTTATGTCTTGTTGGTTCTATATATTTAATATTTAGGTTTTTTACTATGTGTTTTTGGGTTTTACATTTGTAAAGCCCTCTGAGCAGCATTGCTGATTATGCGCTATTTAAATATTAC
" && 
blastn \
-subject <(echo "$SEQ") \
-query <(echo "$SEQ")
#------------------------------------------------------------#

BLASTN 2.2.28+

Query= ctg7180014845866

Length=373

Subject= ctg7180014845866

Length=373

 Score =  689 bits (373),  Expect = 0.0
 Identities = 373/373 (100%), Gaps = 0/373 (0%)
 Strand=Plus/Plus

Query  1    GCATATTCTGTATTGGGTTTAACACTTGAATGATGACTGTGGAATACTTGTTGCTTGTTG  60
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  1    GCATATTCTGTATTGGGTTTAACACTTGAATGATGACTGTGGAATACTTGTTGCTTGTTG  60

Query  61   GTCACAAAAGAGTTACCATTGGGtttttttaaatctttattgcattttttttaacttttt  120
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  61   GTCACAAAAGAGTTACCATTGGGTTTTTTTAAATCTTTATTGCATTTTTTTTAACTTTTT  120

Query  121  aatttcactgtttacatacttctgaattttttttggactatatgcgttcagcttttttat  180
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  121  AATTTCACTGTTTACATACTTCTGAATTTTTTTTGGACTATATGCGTTCAGCTTTTTTAT  180

Query  181  ttattttttacatatattttttttatTGTCGTTTAGTACGGGTCTTTTTAATACTGTTCC  240
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  181  TTATTTTTTACATATATTTTTTTTATTGTCGTTTAGTACGGGTCTTTTTAATACTGTTCC  240

Query  241  TTTAGGCTTTGACAttttatgtcttgttggttctatatatttaatatttaggttttttac  300
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  241  TTTAGGCTTTGACATTTTATGTCTTGTTGGTTCTATATATTTAATATTTAGGTTTTTTAC  300

Query  301  tatgtgtttttgggttttACATTTGTAAAGCCCTCTGAGCAGCATTGCTGATTATGCGCT  360
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  301  TATGTGTTTTTGGGTTTTACATTTGTAAAGCCCTCTGAGCAGCATTGCTGATTATGCGCT  360

Query  361  ATTTAAATATTAC  373
            |||||||||||||
Sbjct  361  ATTTAAATATTAC  373

Lambda      K        H
    1.33    0.621     1.12 

Gapped
Lambda      K        H
    1.28    0.460    0.850 

Effective search space used: 131769

Matrix: blastn matrix 1 -2
Gap Penalties: Existence: 0, Extension: 2.5


I also run it with a more complex fasta file with 25 longer sequences. The result is alike this one.

Thanks,

Tianqi Li

**Comment by thackl** [comment]
Okay, thanks. Can you also run the proovread reads against the test script:

``` bash
perl -I/public/home/wangrj/program/proovread/bin/../lib/ \
/public/home/wangrj/program/proovread/bin/SeqFilter --in \
pb052015-0052/pb052015-0052.untrimmed.fq --out - --fasta | 
perl -I/public/home/wangrj/program/proovread/bin/../lib/ blast.pl
```

**Comment by litianqi715** [comment]
Hi Thomas,

The command gave out 

[17:32:39] /public/home/wangrj/program/proovread/bin/SeqFilter-1.06
[17:32:39] --in: /public/home/wangrj/pacbio052015/split20m/pb052015-0052/pb05201
5-0052.untrimmed.fq
[17:32:44] Detected FASTQ format, phred-offset 33
 17.6M [=========================================================>] TTS 00:02:04
#------------------------------------------------------------------------------#
[17:34:48] Input
[17:34:48] Sequences              968 #
[17:34:48] Total              8756455 bp
[17:34:48] Longest              27722 bp
[17:34:48] Shortest               324 bp
[17:34:48] N50                  11727 bp
[17:34:48] N90                   5160 bp
#------------------------------------------------------------------------------#
[17:34:48] Filtered
[17:34:48] Sequences              968 #
[17:34:48] Total              8756455 bp
[17:34:48] Longest              27722 bp
[17:34:48] Shortest               324 bp
[17:34:48] N50                  11727 bp
[17:34:48] N90                   5160 bp
#------------------------------------------------------------------------------#

The results of blast.pl is alike the previous run. Header and tail lines are as follows:

#-- cmd: ----------------------------------------------------#
SEQ=">m150525_092658_42146_c100815402550000001823183910291513_s1_p0/139264/0_1689
GAGAGGTATGAGGCATGAGACACATACTATCCCAGGTATACTGCGGGAGTTTCCTTACCGCAGCTCTACTCGCACCTACTGTACTAGAGGAATTTAACTGGAATGAGAAACAGCGGACAATATTTC
TGCCTAGCTCGTCAGCTGGCACTAGTTGATGCGGAGAGGCTATAGGCTTGCAGAGGACTAGATGGTAGCAGAGCAACGTAGTCACACGTGGAGAGGACTAGTGGGACAAGTCGATGAGACGAGATG
AAGGTATGGTCACGCGAGAACGAATTCTGGCAAGACAAGATGTTCCCACGCTGCACAAATAGAGCCTAAGTAGGAATTGTCATGGAGTCTGTGGCACTATTTGGTACATGGTCAACGTCAGATATT
CTGGGTAGCTTCTCAGTGTCACCATCGTTCTCTGGGTGGGGCGTTACTGCCTCCACATCTGCTTTCACGCTCAGTTCGTTTTTTCCAGGATCTGTGGAGCTGCTGAGTCCACACTGTGCACATGGT
TTCCTCGATAGTGCGTCTGCATTGAGGTGCTTGGTTCCCGGCCTGTGTTCGATCTTGAATTCATAAGGGGCTAACCTCTCTATCCAGCGAGCAACCTGCCCCTCGGGTTCCTTGAATGAAAACAAC
CACCGCAAGCTCCCATGATCGGTACGTAGTAGAAACGGCTTGCCCAGCAAGTAATGTCTGAAATACCGTACAAAGTAAACAACGGCCAGCAACTCTTTTCTCGTTGTACAATAGTTGCGTTCCCTT
TTCGTGAGAAGTCGACTTCCATAGGAAATAACAAGTTCCTGACCAGACTGTTTCTGTGAGAGCACTGCACCTATTCCAAACTGGCTGGCATCTGTGTCGAGTACAAAAGGGTCCTTATCGTAGGGG
TATGCCAAAATCGGAGATGAGGTTAGTTTGTTCTTCAGAGTAGCAAATGCTTCTGCACAGTCATCGCTCCACTTGAACTGCTTTCCTTTCTCAGTCAGTGCATGCAGTGGACGGGCTATGCTGGCG
AACCCTTCAATGAACCTCCGATAGTAGGTTGCAAGGCCTAGAAAGCTCCTCAGGTCTGTCAAGGTTGAGGGTGTGACCCATTCCGCTACATCCTTTACTTTCCGGGGGTTGGGACTTATACCTTCA
CCTGATACTACGTGGCCCAAGAACTCAACTTTGCTTTGGAATAGGCAGCACTTCTTGGTTTTCAGTGTCAGATTGGCCTCTCGCAAACGTTGGAGGACAGAGCTTAAGCGTTCTATGTGTTCCTCA
AATGTGCGCCCATGCACTATGATGTCATCGATGTATAAGACGGCAACGTCCCACTGAAGGCCAGCAAGAACCCTTTCCATCAAACGTTGGAAAGTGGCCGGGGCGTTGCAGAGACCGAACGGCATA
ACTGTGAATTCATACAGTCCTTTTCGAGTAACAAAGGCAGTCTTAGCTCGATCCTCCTCTTTAACTTCAACTTGCCAGTATCCAGAGGCTAAGTCCAAAGTGGAAAACCACCTCGACCCGCCTAGG
GAATCCAAGCTATCTTCGATCCTTGGAAGAGGATACGCGTCTTTGATGGTGGCATCGTTGAGCTTTCTGTAGTCGACACAGAAGCGGGTGGAGCCGTCTTTCTTTGTAACAAGCACAATACAGCGT
G
" && 
blastn \
-subject <(echo "$SEQ") \
-query <(echo "$SEQ")
#------------------------------------------------------------#

BLASTN 2.2.28+

Query= m150525_092658_42146_c100815402550000001823183910291513_s1_p0/139264
/0_1689

Length=1639

Subject= m150525_092658_42146_c100815402550000001823183910291513_s1_p0/139264
/0_1689

Length=1639

 Score = 3027 bits (1639),  Expect = 0.0
 Identities = 1639/1639 (100%), Gaps = 0/1639 (0%)
 Strand=Plus/Plus

Query  1     GAGAGGTATGAGGCATGAGACACATACTATCCCAGGTATACTGCGGGAGTTTCCTTACCG  60
             ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  1     GAGAGGTATGAGGCATGAGACACATACTATCCCAGGTATACTGCGGGAGTTTCCTTACCG  60

Query  61    CAGCTCTACTCGCACCTACTGTACTAGAGGAATTTAACTGGAATGAGAAACAGCGGACAA  120
             ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  61    CAGCTCTACTCGCACCTACTGTACTAGAGGAATTTAACTGGAATGAGAAACAGCGGACAA  120

(skip)......(skip)

Query  6344  GGACGAGGGAGA  6355
             ||||||||||||
Sbjct  5837  GGACGAGGGAGA  5848

Lambda      K        H
    1.33    0.621     1.12 

Gapped
Lambda      K        H
    1.28    0.460    0.850 

Effective search space used: 106296100

Matrix: blastn matrix 1 -2
Gap Penalties: Existence: 0, Extension: 2.5

**Comment by thackl** [comment]
:(. Just to make sure the following produces errors:

```
perl -I/public/home/wangrj/program/proovread/bin/../lib/ /public/home/wangrj/pr\
ogram/proovread/bin/SeqFilter --in pb052015-0052/pb052015-0052.untrimmed.fq --m\
in-length 500 --phred-offset 33 --substr pb052015-0052/pb052015-0052.chim.tsv -\
-trim-win 12,5 --out - | perl -I/public/home/wangrj/program/proovread/bin/../li\
b/ /public/home/wangrj/program/proovread/bin/siamaera > pb052015-0052/pb052015-\
0052.trimmed.fq
```

Btw, the "unexpectedly dropped ..." issue is already fixed in the latest proovread version. But I don't think, an upgrade would fix the issue at hand...

**Comment by litianqi715** [comment]
Sorry about the delay.
Yes the command gave out the error message:

[11:00:44] /public/home/wangrj/program/proovread/bin/SeqFilter-1.06
[11:00:44] --in: /public/home/wangrj/pacbio052015/split20m/pb052015-0052/pb05201
5-0052.untrimmed.fq
[11:00:44] Detected FASTQ format, phred-offset 33
[11:00:44] --substr-file: /public/home/wangrj/pacbio052015/split20m/pb052015-005
2/pb052015-0052.chim.tsv
 14.2M [==============================================>           ] ETA 00:00:19[15-07-31 11:02:07] [siamaera] Unexpectedly dropped all alignments during processing: m150525_092658_42146_c100815402550000001823183910291513_s1_p0/140788/0_8119.4
 17.6M [=========================================================>] TTS 00:01:42
#------------------------------------------------------------------------------#
[11:02:26] Input
[11:02:26] Sequences              968 #
[11:02:26] Total              8756455 bp
[11:02:26] Longest              27722 bp
[11:02:26] Shortest               324 bp
[11:02:26] N50                  11727 bp
[11:02:26] N90                   5160 bp
#------------------------------------------------------------------------------#
[11:02:26] Filtered
[11:02:26] Sequences             3698 #
[11:02:26] Total              6991608 bp
[11:02:26] Longest              16689 bp
[11:02:26] Shortest               500 bp
[11:02:26] N50                   2647 bp
[11:02:26] N90                    849 bp
#------------------------------------------------------------------------------#

[15-07-31 11:02:27] [siamaera] Summary:
3698 reads scanned
32 siamaeras trimmed (0.87%)
13 potential siamaeras with multiple, unresolved HSPs filtered (0.35%)

And N50 is like that of before.

Eh...I always think the latest version is 2.12 but notice an update of June 30 now. I will update the program and try again.

**Comment by litianqi715** [comment]
I download the newest version of 2.13.6 and run again. It doesn't give out error or warning messages any more while the N50 result is still ~2.5kb.

**Comment by thackl** [comment]
Sorry for the late replay, I've been on a short trip over the weekend. This is quite strange, the only thing to have disappeared should be the "unexpectedly dropped" warning, which is now correctly handled as a debug comment. Basically, there are two things that could cause the issue: either the data or your setup.

The quickest way to eliminate your data as source would be, if I could test some of it on my machine. Would it be possible to send me a hand full of sequences by email. 10-20 should suffice, ideally those sequences that got chopped into pieces  and raised exceptions on your system.

I will also prepare a debug script with some hopefully useful tests later today, to check how your system handles its execution.

**Comment by litianqi715** [comment]
The truth is, I have already tested the same dataset on another cluster, which has the same version of perl, Log::Log4perl, samtools, ncbi-blast+ and proovread 2.12. It gave out the "unexpectedly dropped" warnings but can finish normally and the result N50 is more than 5k bp. So I think the dataset is good.

I have splited the pacbio reads to 20M pieces so this is okay to be transfered, but the short reads library is very large. The genome size is very big, so I think only a very low coverage of short reads is  possible. If this is okay for test, I can email them to thackl@lim4.de or other sites.

Besides, I think the setup can be the problem. In the earliest runs, the process is always stuck at the "Reading ~/rawreads/SC-180.fastq" step and never end. After we switched the operating system to redhat, this problem is tackled and comes the N50 problem. I wonder there are some other environment settings which are not noted in the document but don't meet the requirement.

**Comment by thackl** [comment]
Okay, this is very good - if it works on another cluster, than there most likely is no data issue.

However, just to be really sure, I'd like to have a look at it, particularly because the files in question are produced by proovread and might contain errors that have been introduced in a previous step and aren't directly linked to the siameara step. I don't need short reads, only `pb052015-0052/pb052015-0052.untrimmed.fq` and `pb052015-0052/pb052015-0052.chim.tsv` (or a part of these to files if they are to large to send)

**Comment by litianqi715** [comment]
I have sent them to your mail thackl@lim4.de.

**Comment by thackl** [comment]
Thanks a lot for the data. It seems I slightly misunderstood your problem though. There seem to be two problems:

1. siamaera blast exceptions
2. low N50 (dropped from >10kb to <2.5kb)

Judging from the batch you just sent me, these issues are not related. The only siamaera warning in the log ist the "unexpectedly dropped" debug message (which has been fixed in the latest release)

I suspect, your true issue is the drop in N50. The direct reason for that is the quality based trimming by the SeqFilter.

```bash
# trim reads + get stats
perl -I/public/home/wangrj/program/proovread/bin/../lib/ \
 /public/home/wangrj/program/proovread/bin/SeqFilter \
 --in pb052015-0107/pb052015-0107.untrimmed.fq \
--min-length 500 --phred-offset 33 --trim-win 12,5
```

There doesn't seem to be a bug, I get the same stats on my machine here with the data set you sent me. It basically means that a lot of the reads in the data set could not be corrected along their entire length. Read N50 is quite sensitive, because as soon if you have one spot of a couple of base pairs in a read, that could not be corrected, the read will be cut into two pieces, essentially halving the N50.

But I'm assuming, not all of you chunks exhibit/did exhibit a drop this significantly in N50 and that is why you expected a potential bug/issue with the new setup?

Do you have a log file of a run with good results? Is the problem systematic - are all chunks on the new system bad or does it affect only a few chunks. Do you have direct comparisons? The important thing would again be to determine, whether it is a generic data set issue or related to your system specifically

**Comment by thackl** [comment]
I just read your inital post again, which answers most of the my latest questions...
> They gave out the same errors.
> All runs can finish with the errors and give out a result N50 of less than 3kb and ~70% total sequences remains.
> In my old environment, however, all runs is normal with a result N50 of ~6kb and ~80% sequences remains.
There definitely seems to be something going wrong during the correction process. Do you by any chance still have a log from a successful run - that could help a lot in pinpointing the problem

**Comment by litianqi715** [comment]
Eh..well, same version of software setup in different environment gave out different results. This really bothers me. Perhaps new computing environment always has some odd problems to tackle.

I have sent files from good run of pb052015-0052 to your email. Good run of pb052015-0107 has not been conducted and I can have results in 5 hours, if you need. 

Computing resources of the good cluster is very limited now so I cannot process all the data.

**Comment by thackl** [comment]
Thanks for mailing me the log. I already found a potential issue right at the start of the log. Have a look at these statistics about the provided short read file, particularly the estimated number of reads:

``` bash
# good log
SC-180.fastq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 420M

# bad log
SC-180.fastq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 112M
```

This is supposed to be the same short read file in both runs, I suspect. To be sure, could you verify the files integrity - it is also possible that there is an issue in file size estimation resulting in wrong estimates about read number and hence skewed sampling rates...

**Comment by litianqi715** [comment]
Ah... I just check the short reads library and it indeed is about a quarter of the normal size. Perhaps I damaged it when dealing with the earlier "reading never end" problem and OS re-installation. I shall re-run the process.

This is a shame!!! I'm very sorry! I will tell you the result when test run is complete. Sorry again.

**Comment by thackl** [comment]
No problem at all, I'm happy  if I could help :). I hope this didn't affect any other analyses.

**Comment by thackl** [comment]
Dear Tianqi,

I hope you where able to restore your data and I'm gonna assume that that also resolved the issue.

**Comment by litianqi715** [comment]
Hi, I have run a batch of files. So far they have all passed. The N50 are normal. I think all I need now is more running time. Thank you for your help!
