### ISSUE TITLE
threads

### ISSUE THREAD

**Issue by dandepledge** [BioInf-Wuerzburg/proovread#123]
What's the maximum number of threads that can be requested and utilised with proovread? I'm trying to run it on an HPC system (single node, 20 threads requested) but it seems to be running slower than by default (which I think requests 8 threads)?

Thanks

**Comment by thackl** [comment]
It should scale well to 20 or more threads. Have you had a look at the log to see what steps are running slower? The most time consuming step is mapping with `bwa mem`, and that should not have any issues with ramping up threads. If there is a bottle neck, it might be related to piping the `bwa mem` output through `samtools` and writing the output to disk.

**Comment by dandepledge** [comment]
So as best I can tell the correction is being split into 2930 batches and each batch is taking about 1 min or so to run. Even with scaling this seems to take around 9 hrs for each round of correction (I think proovread does five rounds (bwa-sr-1 to bwa-sr-5).

I'm using 1 million paired-end Illumina reads (FLASh merged) against about 200,000 long read sequences (mostly in the range of 500bp - 4500bp).

I seem to get a small improvement when utilizing --no-sampling (this is long read RNA sequencing data) but not as substantial as other uses seem to suggest.

**Comment by thackl** [comment]
Could you send me you log file?
