### ISSUE TITLE
'N' in proovread corrected sequences

### ISSUE THREAD

**Issue by fantastycrane** [BioInf-Wuerzburg/proovread#124]
Hi @thackl ,

I am using proovread to correct quivered concensus sequence from Iso-seq with Illumina RNASeq data. Seems like some bases in original sequences are replaced with 'N' in the output. Any way to avoid 'N' occured in the corrected result? 

Thanks.

**Comment by thackl** [comment]
Does quiver output IUPAC code, i.e. characters other than `ATGC` (`W` for `A` or `T`, ...) ?. proovread substitutes non-`ATGC` with `N`. Unfortunately proovread does not support IUPAC. A quick hack to prevent `N` in the output would be to substitute the IUPAC chars in the input sequence with an `ATGC` character. For example replace every occurrence of a `W` randomly with `A` or `T`, ... Not sure if this would work for you. If so, I can send you a script to prepare your input reads in that way.

**Comment by thackl** [comment]
Oh and let me know if there aren't any IUPAC chars in the input. In that case something else might be going wrong.

**Comment by fantastycrane** [comment]
I have checked quivered output and there are't any IUPAC chars. But there are very few 'N's in Illumina RNASeq data. Could this be the problem?

**Comment by thackl** [comment]
Yes, that might be it. If for a certain location, there is only one Illumina read with an N (or mulitple and N is the most abundant base at that location), then proovread would pick the N as the consensus base. And yes, this doesn't seem like the ideal behavior. In a case like that proovread should keep the base from the pacbio data...

Unfortunately, I don't have the time right now to make the necessary changes to proovread in a timely fashion, sorry. What comes to mind as an alternative would be to quality-trim your Illumina reads and discards `N`s that way.

**Comment by fantastycrane** [comment]
Thanks.
It is possible most Hiseq X Ten produced reads have N in them. In that case, there will be not much data left for correcting. For the time being, I'll try converting N in corrected results to orginal base at the same position in quivered output.

**Comment by thackl** [comment]
OK, that sounds like a good approach. Sorry for the inconvenience. I wil close this issue for now, butl think about updating proovread to handle the case of N in Illumina reads better when I get the chance. Thanks for reporting the issue
