### ISSUE TITLE
bwa-proovread

### ISSUE THREAD

**Issue by Toral-Manvar** [BioInf-Wuerzburg/proovread#128]
Hello,

I want to use proovreads for pacbio error correction, so when I tried using it for sample data, but it gave me error :
Binary '/opt/app/proovread/bin/../util/bwa/bwa-proovread' neither in PATH nor executable.
In installation guide, it is mentioned in Note "proovread comes with its own, modified version of bwa". 
So I am wondering, why my bin folder doesnot contain bwa?

Please help.

**Comment by thackl** [comment]
How did you install proovread? Did you run `make && make install`? Did you get any errors during install? And have you checked whether `/opt/app/proovread/bin/../util/` contains a folder `bwa/` and  with the binaries in it? If so, also make sure the files are executable.

**Comment by Toral-Manvar** [comment]
Thank  you very much prompt reply. 
Sorry for troubling you unnecesarily. Yes there was problem in installation and thus there were no binaries in bwa folder.

But now I am facing different problem.
I am using illumina, 2x150 and 2x250 reads along with allpath unitig sequences for pacbio sequel read correction.

command used:
proovread -l ../pacbio.fasta -u Allpaths_unitigs.fasta -s MP_150_R1.fq -s MP_150_R2.fq -s PE_150_R1.fq -s PE_150_R2.fq -s PE2_150_R1.fq -s PE2_150_R2.fq -s PE_250_R1.fq -s PE_250_R2.fq  -t 40 --overwrite -p pacbio_corrected

+++++++++==============+++++++++=====================+++++++++++++++
                                                     Error obtained
+++++++++==============++++++++++====================+++++++++++++++
[Wed May  9 17:59:46 2018] Running proovread-2.14.1 under Perl 5.10.1
[Wed May  9 17:59:46 2018] Reading core config
[Wed May  9 17:59:46 2018] Reading command line options
[Wed May  9 17:59:48 2018] Logging parameter to `pacbio_corrected/pacbio_correct
ed.parameter.log`
[Wed May  9 17:59:48 2018] Checking short read files
  
MP_150_R1.fq
  Detected FASTQ format
  Estimated short read length: 124 +-36
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 25.0M
  
MP_150_R2.fq
  Detected FASTQ format
  Estimated short read length: 125 +-36
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 24.9M
  
PE_150_R1.fq
  Detected FASTQ format
  Estimated short read length: 150 +-2
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 76.2M
  
PE_150_R2.fq
  Detected FASTQ format
  Estimated short read length: 150 +-6
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 76.3M
  
PE2_150_R1.fq
  Detected FASTQ format
  Estimated short read length: 129 +-28
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 63.7M
  
PE2_150_R2.fq
  Detected FASTQ format
  Estimated short read length: 129 +-28
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 64.6M
  
PE_250_R1.fq
  Detected FASTQ format
  Estimated short read length: 239 +-27
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 34.0M
  
PE_250_R2.fq
  Detected FASTQ format
  Estimated short read length: 220 +-47
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 33.8M

[Wed May  9 17:59:50 2018] Checking alternative read files
  
Allpaths_unitigs.fasta
  Detected FASTA format
  Estimating fragment length: 270 +-718
  Estimating approximate number of fragments: 17.1M

[Wed May  9 18:00:32 2018] Checking required binaries

  [ok] samtools-1.4.1  /usr/local/bin
  [ok] bwa-proovread   /opt/app/proovread/bin/../util/bwa
  [ok] blasr           /opt/app/proovread/bin/../util/blasr-1.3.1
  [ok] blastn-2.2.28   /opt/app/blastPLUS_020228

[Wed May  9 18:00:32 2018] Running mode: mr+utg
[Wed May  9 18:00:32 2018] Preparing long reads
  Skipped 11900 stubby reads with length <342
#------------------------------------------------------------------------------#
perl -I/opt/app/proovread/bin/../lib/ /opt/app/proovread/bin/SeqFilter --fasta \
--in pacbio_corrected/read-long/pacbio_corrected.fq --line-width 80 --lower-cas\
e --out pacbio_corrected/read-long/pacbio_corrected.masked.fa --phred-offset 33
Unknown option: in
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
perl -I/opt/app/proovread/bin/../lib/ /opt/app/proovread/bin/ccseq --bwa-path /\
opt/app/proovread/bin/../util/bwa/ --threads 40 --pre pacbio_corrected/ccs-1 <p\
acbio_corrected/read-long/pacbio_corrected.fq | tee pacbio_corrected/ccs-1/pacb\
io_corrected.fq | perl -I/opt/app/proovread/bin/../lib/ /opt/app/proovread/bin/\
SeqFilter --line-width 80 --phred-offset 33 --phred-mask 20,41,137,222,60,0.7 -\
-fasta --out pacbio_corrected/ccs-1/pacbio_corrected.masked.fa --base-content N\
 --tsv - --quiet
Unknown option: tsv
[18-05-09 18:06:07] [ccseq] Reading STDIN
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
  ccseq failed: 256

	Exited at 'main'
	'/opt/app/proovread/bin/proovread', line 890
==============================================================================

Please help.

**Comment by Toral-Manvar** [comment]
Thank you very much for prompt reply.
Sorry for troubling you unnecessarily. Yes, there was problem in installation and thus there were no binaries in bwa folder.

But now I am facing another problem.
I am using illumina, 2x150 and 2x250 reads along with allpath unitig sequences for pacbio sequel read correction.

command used:
proovread -l ../pacbio.fasta -u Allpaths_unitigs.fasta -s MP_150_R1.fq -s MP_150_R2.fq -s PE_150_R1.fq -s PE_150_R2.fq -s PE2_150_R1.fq -s PE2_150_R2.fq -s PE_250_R1.fq -s PE_250_R2.fq -t 40 --overwrite -p pacbio_corrected

+++++++++==============+++++++++=====================+++++++++++++++
Error obtained
+++++++++==============++++++++++====================+++++++++++++++
[Wed May 9 17:59:46 2018] Running proovread-2.14.1 under Perl 5.10.1
[Wed May 9 17:59:46 2018] Reading core config
[Wed May 9 17:59:46 2018] Reading command line options
[Wed May 9 17:59:48 2018] Logging parameter to pacbio_corrected/pacbio_correct ed.parameter.log
[Wed May 9 17:59:48 2018] Checking short read files

MP_150_R1.fq
Detected FASTQ format
Estimated short read length: 124 +-36
Etimated short read quality offset: 33
Estimating approximate number of short reads: 25.0M

MP_150_R2.fq
Detected FASTQ format
Estimated short read length: 125 +-36
Etimated short read quality offset: 33
Estimating approximate number of short reads: 24.9M

PE_150_R1.fq
Detected FASTQ format
Estimated short read length: 150 +-2
Etimated short read quality offset: 33
Estimating approximate number of short reads: 76.2M

PE_150_R2.fq
Detected FASTQ format
Estimated short read length: 150 +-6
Etimated short read quality offset: 33
Estimating approximate number of short reads: 76.3M

PE2_150_R1.fq
Detected FASTQ format
Estimated short read length: 129 +-28
Etimated short read quality offset: 33
Estimating approximate number of short reads: 63.7M

PE2_150_R2.fq
Detected FASTQ format
Estimated short read length: 129 +-28
Etimated short read quality offset: 33
Estimating approximate number of short reads: 64.6M

PE_250_R1.fq
Detected FASTQ format
Estimated short read length: 239 +-27
Etimated short read quality offset: 33
Estimating approximate number of short reads: 34.0M

PE_250_R2.fq
Detected FASTQ format
Estimated short read length: 220 +-47
Etimated short read quality offset: 33
Estimating approximate number of short reads: 33.8M

[Wed May 9 17:59:50 2018] Checking alternative read files

Allpaths_unitigs.fasta
Detected FASTA format
Estimating fragment length: 270 +-718
Estimating approximate number of fragments: 17.1M

[Wed May 9 18:00:32 2018] Checking required binaries

[ok] samtools-1.4.1 /usr/local/bin
[ok] bwa-proovread /opt/app/proovread/bin/../util/bwa
[ok] blasr /opt/app/proovread/bin/../util/blasr-1.3.1
[ok] blastn-2.2.28 /opt/app/blastPLUS_020228

[Wed May 9 18:00:32 2018] Running mode: mr+utg
[Wed May 9 18:00:32 2018] Preparing long reads
Skipped 11900 stubby reads with length <342
#------------------------------------------------------------------------------#
perl -I/opt/app/proovread/bin/../lib/ /opt/app/proovread/bin/SeqFilter --fasta
--in pacbio_corrected/read-long/pacbio_corrected.fq --line-width 80 --lower-cas
e --out pacbio_corrected/read-long/pacbio_corrected.masked.fa --phred-offset 33
Unknown option: in
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
perl -I/opt/app/proovread/bin/../lib/ /opt/app/proovread/bin/ccseq --bwa-path /
opt/app/proovread/bin/../util/bwa/ --threads 40 --pre pacbio_corrected/ccs-1 <p
acbio_corrected/read-long/pacbio_corrected.fq | tee pacbio_corrected/ccs-1/pacb
io_corrected.fq | perl -I/opt/app/proovread/bin/../lib/ /opt/app/proovread/bin/
SeqFilter --line-width 80 --phred-offset 33 --phred-mask 20,41,137,222,60,0.7 -
-fasta --out pacbio_corrected/ccs-1/pacbio_corrected.masked.fa --base-content N
--tsv - --quiet
Unknown option: tsv
[18-05-09 18:06:07] [ccseq] Reading STDIN
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
ccseq failed: 256

Exited at 'main'
'/opt/app/proovread/bin/proovread', line 890

==============================================================================

Please help.

**Comment by thackl** [comment]
Something weird seems to be going on with `SeqFilter`. It failed in both of the last commands with
`Unknown option: in` and `Unknown option: tsv`, which does not make sense. What happens if you run

`perl -I/opt/app/proovread/bin/../lib/ /opt/app/proovread/bin/SeqFilter -h`

**Comment by thackl** [comment]
OK, to me it looks like you are dealing with quite a large data set. What's the size of your genome? In general I would say if your genome is larger than 500MB, and you have more than just a few X coverage, using proovread for correction might get impractical. It is still possible if you are dedicated and have a few HPC nodes at your expense to distribute partial jobs. I corrected 10X of a 3GB plant genome for my PhD. But in general I'd recommend looking into other tools that use alignment free approaches.

If you want to continue using proovread, I'd suggest to have a look at https://github.com/BioInf-Wuerzburg/proovread#getting-chunk-sizes-right-48 for details on how to break up data and distribute jobs.

**Comment by Toral-Manvar** [comment]
Yes thackl, I am dealing with ~500 Mb plant genome using >100x data and just ~6x pacbio data. But by using single illumina PE library (~30x), I was able to successfully run proovreads. So thank you very much for your constant help and guidance.
