### ISSUE TITLE
proovread dealing with long reads (>100Mbp)

### ISSUE THREAD

**Issue by justdx** [BioInf-Wuerzburg/proovread#129]
[Wed May 16 19:14:00 2018] Batch 19/19
perl -I/mnt/md3600f/mayj/yangj/software/proovread/bin/../lib/ /mnt/md3600f/mayj\
/yangj/software/proovread/bin/bam2cns --append 1 --bam DZH002/bwa-sr-1/DZH002.b\
am --bin-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --m\
ax-ins-length 0 --max-ref-seqs 100 --prefix DZH002/bwa-sr-1/DZH002.18 --qv-offs\
et 33 --ref DZH002/read-long/DZH002.fq --ref-offset 730273449
#------------------------------------------------------------------------------#
Out of memory!
#------------------------------------------------------------------------------#
[Thu May 17 08:43:05 2018] bam2cns unexpectedly returned
	Exited at 'main'
	'/mnt/md3600f/mayj/yangj/software/proovread/bin/proovread', line 1634
	Last call 'main::correct_sr_mt'
	'/mnt/md3600f/mayj/yangj/software/proovread/bin/proovread', line 868

Hi there. I am dealing with long reads >100M with proovread, but it ended up with "out of memory". Can I ask is there a maximum length of long reads and what shall I do to run it smoothly?
Thanks.

Xiao

**Comment by thackl** [comment]
Hi Xiao,

frankly, I never really tested proovread on very long reads. And I also didn't implement it in a way that would scale well when reads get >100kbp. I am not surprised it ran out of memory. How much memory did you give to the job? Unfortunately, I don't think there is an easy fix for making proovread work with your data, sorry.

**Comment by justdx** [comment]
Thank you anyway.
