### ISSUE TITLE
Masked ratio always be 0.0%

### ISSUE THREAD

**Issue by justdx** [BioInf-Wuerzburg/proovread#130]
Hello. I am using 62G Illumina data to correct 150M Pacbio data. The proovread run well without ERROR or Warning, but from the beginning to the end the 'Masked ratio' is always 0.0% as shown below.
I am wondering what is going wrong and how can I fix it? Thanks.

[Thu May 31 09:51:53 2018] Running task bwa-sr-1
[Fri Jun  1 12:00:56 2018] Masked : 0.0%
[Fri Jun  1 12:00:56 2018] Masked < 92% total / > 3% new - continuing
[Fri Jun  1 12:00:56 2018] Running task bwa-sr-2
[Sat Jun  2 17:34:12 2018] Masked : 0.0%
[Sat Jun  2 17:34:12 2018] Masked < 92% total / > 3% new - continuing
[Sat Jun  2 17:34:12 2018] Running task bwa-sr-3
[Sun Jun  3 17:36:03 2018] Masked : 0.0%
[Sun Jun  3 17:36:03 2018] Masked < 92% total / > 3% new - continuing
[Sun Jun  3 17:36:03 2018] Running task bwa-sr-4
[Mon Jun  4 16:48:31 2018] Masked : 0.0%
[Mon Jun  4 16:48:31 2018] Masked < 92% total / > 3% new - continuing
[Mon Jun  4 16:48:31 2018] Running task bwa-sr-5
[Tue Jun  5 17:47:01 2018] Masked : 0.0%
[Tue Jun  5 17:47:01 2018] Masked < 92% total / > 3% new - continuing
[Tue Jun  5 17:47:01 2018] Running task bwa-sr-6
[Wed Jun  6 23:55:46 2018] Masked : 0.0%
[Wed Jun  6 23:56:03 2018] Running task bwa-sr-finish

**Comment by thackl** [comment]
Hm, it means that there probably weren't any reads mapped to the PacBio reads. Can you attach the complete log, so I can check for other issues? Can you tell me a bit more about the data you are working with (genomic/transcriptomic, length of Illumina reads, quality of PacBio, ...)
