### ISSUE TITLE
proovread on large datasets

### ISSUE THREAD

**Issue by TobiasJu** [BioInf-Wuerzburg/proovread#131]
Hi,

I am very interested in using proovread to correct long PacBio reads, with Illumina short reads. The problem is that our data set is very large. We have about 10000000 PacBio reads and 500000000 Illumina reads. Leading to a coverage of 80. In the manual you wrote "Run proovread on one chunk first", which i did.

To approximate the run time I took 1/512 of the PacBio reads vs all Illumina short reads, and it took about 3 days, using 1/256 of the data set it took 6 days. 1/128 of the data set is currently running (9 days so far). So it is save to assume that the total run will be 256*6 = **1536 Days**. Which is a bummer because i need the corrected reads asap.  
  
Our servers are quite powerful, we have about 256 to 512GB RAM and 40 cores on our machines. The CPUs are well loaded and the RAM usage was fine, like 20 to 40GB. But with all 5 machines in parallel it would still take 300 days.  
  
This was my cmd argument:
`/bin/proovread --threads 40 --coverage=80 --long-reads=pacbio.fastq -s=Illumina_reads.fasta`  
  
Log for the 1/512 subset:  
```
[Mon Aug  6 13:46:57 2018] Running mode: mr
[Mon Aug  6 14:41:21 2018] Running task bwa-mr-1
[Tue Aug  7 14:33:58 2018] Masked : 58.6%
[Tue Aug  7 14:33:58 2018] Running task bwa-mr-2
[Wed Aug  8 04:39:54 2018] Masked : 70.2%
[Wed Aug  8 04:39:54 2018] Running task bwa-mr-3
[Wed Aug  8 15:25:58 2018] Masked : 74.6%
[Wed Aug  8 15:25:58 2018] Running task bwa-mr-4
[Thu Aug  9 01:15:29 2018] Masked : 77.6%
[Thu Aug  9 01:15:29 2018] Running task bwa-mr-5
[Thu Aug  9 08:35:16 2018] Masked : 78.9%
[Thu Aug  9 08:35:17 2018] Running task bwa-mr-finish
[Thu Aug  9 10:32:02 2018] Masked : 73.4%
```
    
Is there a way to speed up the process, allow more RAM usage, allow a lower masked area and/or less bwa-mr runs?  
  
PS: Your "Total time spent" at the end of each run is broken. It said 21h, but it was more like 3 days:  
`[Mon Aug  6 13:46:33 2018] Running proovread-2.14.1
....
[Thu Aug  9 11:19:41 2018] Total time spent 21:33:08
[Thu Aug  9 11:19:41 2018] Done`  
  
Thanks for your work.  
Tobias

**Comment by thackl** [comment]
Hi Tobias,

if I am not mistaken, you are looking at a genome on the order of 6 Gb or more. In that case, I don't think that proovread is the right tool for you. proovread is quite sensitive and accurate, and at the time I developed it, it was basically the only program that was able to tackle Gb-sized data set, at the expense of quite a bit of runtime, though. Nowadays, however, there are quite a few newer and faster tools for large data sets out there, such as [HALC](http://dx.doi.org/10.1186/s12859-017-1610-3),  [Jabba](http://dx.doi.org/10.1186/s13015-016-0075-7), or [HG-CoLoR](http://dx.doi.org/10.1093/bioinformatics/bty521). 

Cheers
Thomas

P.S.: And yes, I should put this as a disclaimer at the start of proovread's readme. Sorry, for the time you've already spend on it.

**Comment by TobiasJu** [comment]
Hi Thomas,

yeah we have a genome with many many Gb. Thanks a lot fot the suggestions, we already tried Jabba and it failed horribly. HG-CoLoR looks promising and we will also test HALC.

The last test run (1/128) finished a little over 9 days, so it may be scale better than linear. I will run a last test just out of curiosity and report back here.

And yes a disclaimer in the readme would be highly appreciated. 

best regards
Tobias

**Comment by thackl** [comment]
Yes, I thought about that too. Minimap2 is pretty amazing. It could also replace all the other mappers/aligners I use on proovread (blast, blasr, ..). Right now, there are two obstacles, though. A) bwa-proovread is a modified version of bwa. Because of the sensitive settings necessary to map to pacbios, a ton of mappings is created and reported when running proovread. That quickly let's temporary bam files explode, especially with repetitive genomes. bwa-proovread has an additional single-pass filter I implemented to mitigate that issue. I'm not sure if I would run into similar issues with minimap2, but I might. And that leads to B) I don't think I have the time right now to look into this and implement it, even though, it would be a good idea...
