### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by joonlee311** [BioInf-Wuerzburg/proovread#132]
Hi,

I can't seem to find out what went wrong. I am using blast+/2.6.0, proovread/2.14.1, perl/5.22.4., samtools/1.9

Could you please help me to solve this problem?

Thanks,
John

Below is the error message.

[Thu Aug 23 22:43:13 2018] Running proovread-2.14.1 under Perl 5.22.4
[Thu Aug 23 22:43:13 2018] Reading core config
[Thu Aug 23 22:43:13 2018] Reading command line options
[Thu Aug 23 22:43:13 2018] Logging parameter to `string/string.parameter.log`
[Thu Aug 23 22:43:13 2018] Checking short read files
  
RNAseq_13HP02_all_PSC8.fastq
  Detected FASTQ format
  Estimated short read length: 98 +-10
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 405M

[Thu Aug 23 22:44:28 2018] Checking required binaries

  [ok] samtools-1.9    /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx\
2/Compiler/gcc5.4/samtools/1.9/bin
  [ok] bwa-proovread   /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx\
2/Compiler/gcc5.4/proovread/2.14.1/bin/../util/bwa
  [ok] blastn-2.6.0    /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx\
2/Compiler/gcc5.4/blast+/2.6.0/bin

[Thu Aug 23 22:44:29 2018] Running mode: sr
[Thu Aug 23 22:44:29 2018] Preparing long reads
#------------------------------------------------------------------------------#
[Thu Aug 23 22:44:35 2018] Non-unique long read id (transcript/0) in /home/joonl
ee3/projects/rpp-rbruskie/joonlee3/Isoseq_INRA/PSC8/corrected_with_RNASeq/IsoSeq
/PSC8_all.hq.fastq
        Exited at 'main'
        '/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/proo
vread/2.14.1/bin/proovread', line 1473
        Last call 'main::read_long'
        '/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/proo
vread/2.14.1/bin/proovread', line 716

**Comment by thackl** [comment]
Ho Joon,

The issue is `Non-unique long read id (transcript/0)`, which means that you have multiple sequences with same ID (transcript/0) in your input file PSC8_all.hq.fastq. proovread indexes the sequences it should correct by ID and, therefore, requires a unique ID for each input sequence.
