### ISSUE TITLE
issue when trying to install proovread

### ISSUE THREAD

**Issue by jupollet** [BioInf-Wuerzburg/proovread#136]
Hi,
I have an issue when I try to install proovread on my Ubuntu 16.04 with perl 5.22  and no other bwa version install on it:
`make[1] : on quitte le répertoire « /home/justine/Documents/Tools/proovread/util/bwa »`

**Comment by thackl** [comment]
Does it mean you got it running?

**Comment by jupollet** [comment]
No, It's a missclick.
And I am not sure your tools correspond to my task.
I have BAM files from human exome and I want to simplify the sequence doing contigs with mapped reads.

**Comment by jupollet** [comment]
Sorry for the disturbance, finally I will not do this task.
