### ISSUE TITLE
question about the chunk size

### ISSUE THREAD

**Issue by xix017** [BioInf-Wuerzburg/proovread#137]
Hi thackl,
Thanks for your work. I am sorry I am a little confused about the example you gave in setting the chunk size: <10Mbp genome and 20M chunks.
# generate a single <10Mbp chunk
SeqChunker -s 20M -l 1 -o pb-%03d.fq pb-subreads.fq

For my understanding, this chunk size contains 2x coverage of the genome, which contradicts to the description "chunks should not contain more than 1X coverage of the genome".  Could you please tell me what's wrong with my understanding of this example?

Thanks a lot for your time and help.
Best,
Min

**Comment by thackl** [comment]
Good question. The `-s` parameter actually refers to size in byte not bp. For fq files every 1 actual  1bp is about 2byte and a bit (one char nuc, one char quality, and some extra for read headers). So in the example chunksize is a bit less than 1x.
