### ISSUE TITLE
provide an installation routine that installs everything needed to a common prefix

### ISSUE THREAD

**Issue by wookietreiber** [BioInf-Wuerzburg/proovread#14]
Usually, when building and installing software, at the end of the instructions, there is something like `make install` that installs everything to a certain prefix, e.g. `/usr/local`.

My impression at this moment is, that proovread is not meant for this kind of installation, because the instructions are to clone the repository to some path and work within this path. This way, you can't really install it to some location so that multiple users can access it.

It would be really nice to have an installation routine that would install proovread to such a common prefix, i.e. have all the executables in `$prefix/bin`, have the perl modules in `$prefix/lib/perl5/site_perl` and other stuff like proovread.cfg or the samples in `$prefix/share/proovread`.

I am currently trying to do this manually but had some issues as I had to fix all of these `$RealBin/../...` paths.

**Comment by thackl** [comment]
You are right, proovread does not come with a real install routine or make install thingi.. That has two main reasons:
1. Personally I like to have the entire package as a self contained thing (on most systems I work with, I don't have permissions to write to global install locations any way). Once downloaded, you can move the entire folder anywhere, e.g. globally /shared-software/, and it will work. No messing around with library dependencies/version conflicts..
2. To be honest, I don't want to / don't have the time to fiddle with things, I'm not really familiar with - this includes writing universally applicable make file or putting libraries in globally shared perl library paths. I'm a biologist first, my informatics skill are self-taught and only go so far...

Sorry for the inconvenience, but I don't think, I can really help with this issue.

**Comment by thackl** [comment]
Fyi, if your main concern is to get the proovread executable into /usr/bin/, it should suffice to place a link there pointing to the clone (and moved) proovread folder. `$RealBin` resolves links correctly.
