### ISSUE TITLE
Proovread terminated with error

### ISSUE THREAD

**Issue by sanjaysingh765** [BioInf-Wuerzburg/proovread#140]
**I run proovread with following command**
     
    `perl proove/proovread/bin/proovread -l Lang_flnc.fasta.CDHIT.fasta -s normalized.fastq -o re`

After running for 5 days, it terminated with the following error.

```
Reading normalized.fastq
    Killed
    [E::sam_parse1] incomplete aux field
    [W::sam_read1] parse error at line 185663450
    [main_samview] truncated file.
    #------------------------------------------------------------------------------#
  
	Exited at 'main'
	'proove/proovread/bin/proovread', line 1320
	Last call 'main::run_bwa'
	'proove/proovread/bin/proovread', line 853
```

Any help will be appreciated. Thanks.

**Comment by thackl** [comment]
Can you send me your complete log file. Seems like something went wrong earlier in the run which then resulted in a truncated bam file.

**Comment by sanjaysingh765** [comment]
I am not sure where to locate log file. Please find the log file created after each iteration. Thanks.


[proovread_bwa.log](https://github.com/BioInf-Wuerzburg/proovread/files/3213665/proovread_bwa.log)
[proovread_bwa.log](https://github.com/BioInf-Wuerzburg/proovread/files/3213668/proovread_bwa.log)
[proovread_bwa.log](https://github.com/BioInf-Wuerzburg/proovread/files/3213670/proovread_bwa.log)
[proovread_bwa.log](https://github.com/BioInf-Wuerzburg/proovread/files/3213671/proovread_bwa.log)
[proovread_bwa.log](https://github.com/BioInf-Wuerzburg/proovread/files/3213673/proovread_bwa.log)
[proovread_bwa.log](https://github.com/BioInf-Wuerzburg/proovread/files/3213674/proovread_bwa.log)

**Comment by thackl** [comment]
Ah, no, those are just the logs from mapping with bwa. I mean everything that proovread logged to the console. But I'm guessing from the confusion that you did not save that to a file?

**Comment by sanjaysingh765** [comment]
Sorry I didn't save it. However partial log is attached. Thanks

[log.txt](https://github.com/BioInf-Wuerzburg/proovread/files/3213720/log.txt)

**Comment by thackl** [comment]
Perfect, thanks. Yes, just look 5 lines up from what you sent initially. It says:
```
/home/sanjaysingh765/Desktop/analysis/proove/proovread/bin/SeqChunker: line 17: echo: write error: No space left on device
/home/sanjaysingh765/Desktop/analysis/proove/proovread/bin/SeqChunker: line 23: echo: write error: No space left on device
```

It means you ran out of diskspace, and that's what killed samtools and resulted in the truncated file. If you want to rerun proovread, I'd suggest to split your input data. You seem to have a lot of reads to correct, which is also not ideal for best results. Have a look at this section of the manual https://github.com/BioInf-Wuerzburg/proovread#getting-chunk-sizes-right-48 for more info. Smaller input sets should need less space and you can also delete intermediate files after the end of the run. (And fyi, proovread died in the last iteration, so you were actually almost done, sorry...)

**Comment by sanjaysingh765** [comment]
Thanks for your reply. Is there any way to resume my old job?

**Comment by thackl** [comment]
No, unfortunately not...

**Comment by sanjaysingh765** [comment]
Thanks
