### ISSUE TITLE
Error in make sample

### ISSUE THREAD

**Issue by martynakgajos** [BioInf-Wuerzburg/proovread#141]
Hi!
I get a following error:

> [Tue Aug  6 17:46:41 2019] Running proovread-2.14.1 under Perl 5.12.1
> [Tue Aug  6 17:46:41 2019] Reading core config
> [Tue Aug  6 17:46:41 2019] Reading command line options
> [Tue Aug  6 17:46:41 2019] Logging parameter to `sample-results/sample-results.p
> arameter.log`
> [Tue Aug  6 17:46:41 2019] Checking short read files
>   
> F.antasticus_short.fq
>   Detected FASTQ format
>   Estimated short read length: 100 +-0
>   Estimating approximate number of short reads: 50.0k
> 
> [Tue Aug  6 17:46:41 2019] Checking required binaries
> 
>   [ok] samtools-1.9    /usr/local/package/bin
>   [ok] bwa-proovread   /home/Programs/proovread/bin/../util/bwa
> FATAL:  Missing query sequence filename.
> EXIT CODE 5
> #------------------------------------------------------------------------------#
> [Tue Aug  6 17:46:42 2019] Couldn't determine version of blastn, at least 2.2.24
>  required
> 	Exited at 'main'
> 	'bin/proovread', line 2068
> 	Last call 'main::check_binary'
> 	'bin/proovread', line 672
> make: *** [Makefile:32: sample] Error 255

Howeve, when I check `blastn -version`
> blastn: 2.9.0+
>  Package: blast 2.9.0, build Jun 27 2019 15:04:52
What might cause the problem here?

**Comment by thackl** [comment]
Hi, thanks for getting in touch.  Hmm, odd. I have the same blast version, and don't have any issues. What happens if you run the perl snippet below on your system? This is essentially what proovread runs, too. On my system I get the expected output.
```
perl -e 'print qx(blastn -version);'
blastn: 2.9.0+
 Package: blast 2.9.0, build Apr 26 2019 05:55:13
```

**Comment by martynakgajos** [comment]
Good point! When called in this way, I am being sent to a different blast version.
> FATAL:  Missing query sequence filename.
> EXIT CODE 5
> BLASTN 2.0MP-WashU [04-May-2006] [linux26-x64-I32LPF64 2006-05-10T17:22:28]
