### ISSUE TITLE
make: *** [Makefile:18: util] Error 1

### ISSUE THREAD

**Issue by akesarwani** [BioInf-Wuerzburg/proovread#143]
The very first step of installation throws error. Not sure what it could be.

make
git submodule init
git submodule update --force
Usage: git submodule [--quiet] add [-b branch] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] update [--init] [-N|--no-fetch] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--] [<path>...]
make: *** [Makefile:18: util] Error 1

**Comment by thackl** [comment]
I think this is an issue with your particular git version. Can you run `git --version` and `git submodule --help` and see if it supports `--force`?

**Comment by Hulanyue** [comment]
hello,I have similar problem,I install git version and when I 

$ make && make install 
it will show :
git submodule init
fatal:not a git repository (or any of the parent directories) : .git
make: ***[Makefile:17:util] Error 128

**Comment by akesarwani** [comment]
I used git/2.8.3 and the installation went successful.

**Comment by thackl** [comment]
Yes, so this is an issue with git version `1.7`, which somehow lacks `submodule --force`. The best fix would be to upgrade your git. If that is not an option, try removing the `--force ` from the make script. To this, remove everything, get a fresh clone, adjust the makefile, run make. I hope this should work. But with this configuration, you won't be able to update proovread, but will have to get a fresh install everytime you want to update
