### ISSUE TITLE
SeqChunker: command not found

### ISSUE THREAD

**Issue by Hulanyue** [BioInf-Wuerzburg/proovread#148]
**Hi,thackl!
when I run  `SeqChunker -s 20M -o pb-%03d.fq pb-subreads.fq`,there is a problem.**

linux@linux-virtual-machine:~/proovread$ SeqChunker -s 20M -o pb-%03d.fq pb-subreads.fq
SeqChunker: command not found

linux@linux-virtual-machine:~/proovread$ cd util
linux@linux-virtual-machine:~/proovread/util$ SeqChunker -s 20M -o pb-%03d.fq pb-subreads.fq
SeqChunker: command not found

linux@linux-virtual-machine:~/proovread/util/SeqChunker/bin$ SeqChunker -s 20M -o pb-%03d.fq pb-subreads.fq
SeqChunker: command not found

**And I try  ` linux@linux-virtual-machine:~/proovread$ ln -s /home/proovread/util/SeqChunker/bin/SeqChunker-perl` ,it is still `SeqChunker: command not found`**

I don't konw what the problem is ,can you enlighten me ?

**Comment by greatfireball** [comment]
Hey @Hulanyue 

seems to be an easy answer: if you call a program or script in Linux, the current folder will not be searched for the program to call. Normally, `SeqChunker` should be located inside the `bin` folder. To execute it, just add a `bin/` in front of `SeqChunker`. Therefore your original call should be:

```bash
bin/SeqChunker -s 20M -o pb-%03d.fq pb-subreads.fq
```
Hope that solves your problem.

Best,
Frank

PS: If you want to call a program in the same folder use `./` instead a folder name. Moreover, using the absolute path is also always possible. In your case the call would be:

```bash
~/proovread/bin/SeqChunker -s 20M -o pb-%03d.fq pb-subreads.fq
```

**Comment by Hulanyue** [comment]
Hi @greatfireball 
Can you tell me what the meaning is about two files(pb-%03d.fq pb-subreads.fq),there are no such files in the folder(I downloaded from this link)
and when I run 

linux@linux-virtual-machine:~/proovread/util/SeqChunker$ bin/SeqChunker -s 20M -o pb-%03d.fq pb-subreads.fq
FILE should be located at 'bin/SeqChunker'
The file 'pb-subreads.fq' does not exist!

I try to use other file(.fq) to replace `pb-subreads.fq`,it is still `does not exist!`

**Comment by greatfireball** [comment]
Sure, the `-o pb-%03d.fq` defines the name of the output files. Within the expression `%03d` is a placeholder and will be substituted by (at least) three digit numbers with leading zeros. The `pb-subreads.fq` is the input file. If the input file does not exist, just use one existing. If the file is not located inside the current directory, you can specify its location via a relative or an absolute path, eg. `../data/in.fq` will search for a file in a subfolder called `data` of the current parent directory names `in.fq`. As already mentioned, you can use absolute paths as well, eg. `~/proovread/data/in.fq`.

**Comment by Hulanyue** [comment]
**when I run `bin/SeqChunker -s 20M -o pb-%03d.fq  ~/proovread/util/SeqChunker/t/ec.fq`,it shows me :** 
linux@linux-virtual-machine:~/proovread/util/SeqChunker$ bin/SeqChunker -s 20M -o pb-%03d.fq  ~/proovread/util/SeqChunker/t/ec.fq
FILE should be located at 'bin/SeqChunker'
Reading /home/linux/proovread/util/SeqChunker/t/ec.fq

**I don't know whether it is right ,because it shows me `FILE should be located at 'bin/SeqChunker'` 
 But, at least a file(pb-001.fq) was generated.**

**Comment by greatfireball** [comment]
Does it contain the sequences from `ec.fq`? That would be fine. Nevertheless, you should probably call `bin/SeqChunker -s 20M -o pb-%03d.fq ~/proovread/util/SeqChunker/t/ec.fq` from the folder `~/proovread/`.

**Comment by Hulanyue** [comment]
Yes,two files are same!
Thank you very much,frank!!

**Comment by greatfireball** [comment]
Welcome... Just let us know, if you need further help
