### ISSUE TITLE
Oxford Nanopore data

### ISSUE THREAD

**Issue by akesarwani** [BioInf-Wuerzburg/proovread#149]
can proovread be used for ONT sequence. I am not sure if any parameter tuning might be required.

**Comment by thackl** [comment]
No, not very well without parameter tuning. And we tried a bit in the past but at least with shorter Illumina data <150bp, we didn't have to get too good results.

**Comment by akesarwani** [comment]
proovread was used to correct error in oxford nanopore direct RNA sequencing data in a recent paper (https://www.biorxiv.org/content/10.1101/706002v1). Not sure, how proovread can be used.

**Comment by thackl** [comment]
You can certainly use it. And it will correct your data as good as it can. But it likely won't be as good as it would be with pacbio data, or as other dedicated tools might be with nanopore.
