### ISSUE TITLE
Error in main::check_binary from samtools --version

### ISSUE THREAD

**Issue by cmorganl** [BioInf-Wuerzburg/proovread#15]
Hey there,

Newer versions of samtools (at least, V1.19) no longer support a --version command, causing this error:
[Wed Sep  2 16:31:51 2015] Checking required binaries

[main] unrecognized command '--version'
#------------------------------------------------------------------------------#
[Wed Sep  2 16:31:51 2015] Couldn't determine version of samtools, at least 1.1 
required
	Exited at 'main'
	'./bin/proovread', line 2045
	Last call 'main::check_binary'
	'./bin/proovread', line 663

This can be solved by using samtools 1.1 of course, but I thought I'd bring it to your attention. 

Other than that, installation and testing was successful on my laptop running Ubuntu 14.04!

Cheers,
Connor

**Comment by thackl** [comment]
the samtools versioning format is a little bit confusing, there actually is no version 1.19, only 0.1.19, which you seem to have. Versions starting with "0" are older than the current releases:

0.1.19 - old, and unfortunately doesn't support --version
1.1 - minimum for proovread
1.2 - current
