### ISSUE TITLE
out.trimmed.fq size 0. Need advise toadjust coverage?

### ISSUE THREAD

**Issue by pomidorku** [BioInf-Wuerzburg/proovread#153]
Hi,
I run proovread to correct pacbio subreads by using illumina (124 bp reads). The size of the bacterial genomes is about 4 million bp.

The out.trimmed.fq size is zero. I intend to use the corrected pacbio reads for assembly. 

I read on the "issues" that someone having a similar problem solved it by specifying a coverage ~20x.

Would you advise me to do specify a low coverage as the above?

I mapped both the pacbio and illumina reads to a sister species to have an approximation to the coverage.

PB
mean coverageData = 691.574X
std coverageData = 311.3044X

ill
mean coverageData = 790.7982X
std coverageData = 320.0393X

The proovread command I run is:

proovread --threads $threads --keep-temporary -l Sphing1_F181_m54092_180524_174447.subreadsFQ.fastq -s Sphing1_FIL_181_I08_ACTTGA_R1.fastq.gz -s Sphing1_FIL_181_I08_ACTTGA_R2.fastq.gz --pre $out_prefix

Please, let me know what you think about this issue.

Regards,

pomidorku

**Comment by thackl** [comment]
I'm pretty sure that something else went wrong. Do you have the log file of the run? Did it run for a long time?

**Comment by pomidorku** [comment]
It run for a long time, about 20 hours (see stdout and stderr files).

I am attaching the stderr, stdout and the log files
[results_out.parameter.log](https://github.com/BioInf-Wuerzburg/proovread/files/4099659/results_out.parameter.log)
[stderr.9338256.txt](https://github.com/BioInf-Wuerzburg/proovread/files/4099662/stderr.9338256.txt)
[stdout.9338256.txt](https://github.com/BioInf-Wuerzburg/proovread/files/4099664/stdout.9338256.txt)

**Comment by thackl** [comment]
Great, thanks!

OK there is an issue with reading the gzipped files. Not entirely sure why, but that is the reason why the correction does not work. The easiest fix for that would be to unpack you short read files.

However, if your goal is to just get a good assembly, based on the data you have, I don't think using proovread is the best strategy for you. (And if you still would want to use it, you should - as you said adjust you coverage. But before going there, consider what I wrote below. If you still want to use proovread, let me know and I will help you with the coverage adjustment)

Here is my suggestion for how to best (and fast) generate an assembly for your genome with your data:

1. Use an assembler that uses raw pacbio data - you have almost 6Gb of Pacbio data, that is >1000x coverage for a 5Mb genome. That is pleeeenty. I would use flye (https://github.com/fenderglass/Flye). Easy to install and use. Should give you a decent assembly within minutes. Use the --asm-coverage option to restrict your coverage to 30X or so (see flye --help). Chances are, this will give you a single chromosome contig, or at least something where most of the genome sits on a handful of large contigs.

2. Use racon (https://github.com/isovic/racon) to polish the assembly with your Illumina data. This helps to remove the base-level errors that you could not get rid of with pacbio self-correction alone. You can even do racon in multiple iterations.

This approach in my experience most of the times gives you better assemblies than running proovread first, and then trying to assemble the corrected reads, and also it is much faster. Using proovread makes sense if you have other issues, like low pacbio coverage (<10x), or specific problems and want to do something out-of-the-box. Hope that helps!

**Comment by pomidorku** [comment]
Thank you for your advise. We have Canu installed in the cluster. And there is also arrow to correct pacbio assemblies by using pacbio reads. But this takes a lot of time.

I will first give a try to racon with the pacbio assembly.

Regards,

pomidorku
