### ISSUE TITLE
Can't allocate memory while bwa indexing 

### ISSUE THREAD

**Issue by yazuo0204** [BioInf-Wuerzburg/proovread#154]
Hi,

I have three Nanopore RNA sequence need to be corrected. But one of them would report  Can't allocate memory while running bwa index. I am sure that I have enough memory -- it still has 500G RAM for running this one. And other two sequence running ok without any errors. 
I tried to change the threads to 1 or default, but it didn't working. 

The *.masked.fasta has 9G, so I thought it might due to the sequence is extremely large. 
I tried to drag out 1000 reads to run proovread-bwa index and it didn't output any errors 

`
/data/user/zuoya/Biosoft/proovread/bin/proovread -t 1 --long-reads=$filter_reads --short-reads=$fq1 --short-reads=$fq2 

#------------------------------------------------------------------------------#
[Wed Jul  1 16:21:46 2020] Read IDs don't look like proper PacBio subread IDs.
Falling back to running mode: sr-noccs

[Wed Jul  1 16:22:16 2020] Running task bwa-sr-1
[Wed Jul  1 16:22:16 2020] Indexing Long reads
#------------------------------------------------------------------------------#
/data/user/zuoya/Biosoft/proovread/bin/../util/bwa/bwa-proovread index proovrea\
d/read-long/proovread.masked.fa proovread/read-long/proovread.masked.fa 2>proov\
read/bwa-sr-1/proovread_bwa.log
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#

        Exited at 'main'
        '/data/user/zuoya/Biosoft/proovread/bin/proovread', line 1277
        Last call 'main::run_bwa'
        '/data/user/zuoya/Biosoft/proovread/bin/proovread', line 853

[bwa_index] Pack FASTA... [add1] Failed to allocate -34359738368 bytes at bntseq.c line 260: Cannot allocate memory
`

**Comment by thackl** [comment]
How big is the file with the nanopore reads? I think there is a maximum file size that bwa can index.

Try runnning `/path/to/proovread/util/bwa/bwa-proovread index $filter_reads` directly in the command line. If that does not work, this is a bwa issue. You will have to split your input file into smaller chunks. Have a look at https://github.com/BioInf-Wuerzburg/proovread#getting-chunk-sizes-right-48
