### ISSUE TITLE
Is it possible to prevent proovread from cutting reads into smaller parts?

### ISSUE THREAD

**Issue by ttbond** [BioInf-Wuerzburg/proovread#157]
Hi~ 
I'm correcting PacBio IsoSeq sequence with proovread. It's really a sufficient and helpful tool. 
However, I found some unexpected cutting of reads. Is there any option to prevent proovread from cutting reads? 

Best wishes,
ttbond

**Comment by thackl** [comment]
Sure. proovread generates two output files (see https://github.com/BioInf-Wuerzburg/proovread#output). One contains the uncut ("untrimmed") reads.
