### ISSUE TITLE
dazz-utg mode failed because of short unitigs in input file

### ISSUE THREAD

**Issue by yuragal** [BioInf-Wuerzburg/proovread#16]
Running proovread in mr+dazz-utg mode I faced with error at mapping unitigs stage.

The problem turned out to be in short fragments from utg file provided as input.
This can be simply resolved with @thegenemyers [tip] (https://github.com/thegenemyers/DALIGNER/issues/21).

Here is a code I added after "Creating DAMs" block to fix the proovread script:
```perl
    $VS->verbose("Filter DAMs");
    $cmd = cfg('dazz-db-path')."DBsplit -x100 $qdb";
    $VB->hline();
    $VB->verbose($cmd);
    $VB->hline();
    qx($cmd);
    $V->exit("DBsplit failed: $?\n", do { local $/; local @ARGV = ($log) ; <> }) if $?;
```

One more block was added after "Mapping unitigs" section to combine *.las files generated by daligner as suggested by [DALIGNER README](https://github.com/thegenemyers/DALIGNER):

```perl
    $VS->verbose("Combine .las files");
    $cmd = cfg('dazz-db-path')."LAcat $opt_prefix.$opt_prefix-utg > $opt_prefix.$opt_prefix-utg.las";
    $VB->hline();
    $VB->verbose($cmd);
    $VB->hline();
    qx($cmd);
    $V->exit("LAcat failed: $?\n", do { local $/; local @ARGV = ($log) ; <> }) if $?;
```

Best, Yuri.

**Comment by thackl** [comment]
Hi Yuri,

thanks a lot for reporting this issue. I already included it in the code and updated the master branch. I also added unitig sample data and `--sample dazz` to run proovread in dazzler mode on sample data.

I really don't know how I could have missed the merging step, though...

Cheers
Thomas
