### ISSUE TITLE
File::Which module

### ISSUE THREAD

**Issue by ramarquezo** [BioInf-Wuerzburg/proovread#17]
This is my output when I run proovread:

Can't locate File/Which.pm in @INC (you may need to install the File::Which module) (@INC contains: /bin/proovread/bin/../lib/ /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at ./proovread line 20.

**Comment by thackl** [comment]
You need the File::Which perl module, you can either install it via CPAN command line or download the [source code](http://search.cpan.org/CPAN/authors/id/P/PE/PEREINAR/File-Which-0.05.tar.gz). Assuming you need to install locally:
```
wget http://search.cpan.org/CPAN/authors/id/P/PE/PEREINAR/File-Which-0.05.tar.gz
tar -xzf File-Which-0.05.tar.gz
cd File-Which-0.05
perl Makefile.PL INSTALLSITELIB=/path/to/proovread/lib   # << set this path !!!!
make && make install
```
Ignore `ERROR: Can't create '/usr/local/bin'`, you don't need that.. You should now have `/path/to/proovread/lib/File/Which.pm` and proovread should find it directly.

**Comment by ramarquezo** [comment]
Thanks thackl, I ran the sample test and all looks ok!!!! Thank you so much!!!

**Comment by csuliweilong** [comment]
Hi @thackl ,

I followed your instructions to install FIle:Which. 

However, I still cannot filnd which.pm in  /path/to/proovread/lib/File/.

Can I copy which.pm in File-Which-0.05 to  /path/to/proovread/lib/File/?

Thank you!

Weilong

**Comment by csuliweilong** [comment]
I fixed this problem. Thank you!
