### ISSUE TITLE
Unable to checkout util/SeqFilter

### ISSUE THREAD

**Issue by IanReid** [BioInf-Wuerzburg/proovread#18]
Git clone fails with message
Unable to checkout '3e091f8fe50804815a06a385c5dfa1eee9fa0b75' in submodule path 'util/SeqFilter'

**Comment by thackl** [comment]
Thanks for reporting this. Should work now. Let me know if it doesn't

**Comment by thackl** [comment]
Presuming no news equals good news... Thanks again for the feedback
