### ISSUE TITLE
Unable to use SeqChunker

### ISSUE THREAD

**Issue by csuliweilong** [BioInf-Wuerzburg/proovread#20]
Hi @thackl ,

I have successfully installed proovread.

I followed the instruction manual to use SeqChunker to chunk PacBio reads first.

But I got a problem when using SeqChunker:
Can't open perl script "/homec/liweilong/proovread/bin/SeqChunker-perl": No such file or directory

ps: I have already addedd /homec/liweilong/proovread/bin to $PATH.

Wait for your reply, thanks!

Weilong

**Comment by thackl** [comment]
Have look at the /homec/liweilong/proovread/bin/SeqChunker, it is supposed to be a link to ../util/SeqChunker/bin/SeqChunker. If you for example used scp to copy proovread to another machine, this link might have been replaced by a actual copy, which would account for the error.

**Comment by csuliweilong** [comment]
Hi @thackl,

I can see SeqChunker in proovread/util/SeqChunker/bin.

As you said, since I scp the proovread dir to my server, there is no link from proovread/bin/SeqChunker  to  proovread/util/SeqChunker/bin/SeqChunker.

Here is my solution: add  proovread/util/SeqChunker/bin to $PATH. Is that OK?

Best
Weilong

**Comment by thackl** [comment]
That won't work. The easiest fix is to remove /bin/SeqChunker and restore the link `ln -s ../util/bin/SeqChunker`. As far es copying goes, I'd recommend rsync instead of scp, it will keep links intact.

**Comment by csuliweilong** [comment]
Thank you!
