### ISSUE TITLE
Unable to find a new block in a fastq file

### ISSUE THREAD

**Issue by csuliweilong** [BioInf-Wuerzburg/proovread#21]
Hi @thackl,

I use SeqChunker to chunk pb.fq. Below is the command line:

 SeqChunker -s 20M -o ecoli-pb-%03d.fq /homec/liweilong/data/Ecoli/e-coli-PacBio.fq

However, I can only get the ecoli-pb-001.fq, and an error occured:

···Unable to find a new block in a fastq file···

How can I solve this problem?

Best 

Weilong

**Comment by thackl** [comment]
This seems to be related to #22, see #22 for answer
