### ISSUE TITLE
Couldn't find record start within last 5 lines

### ISSUE THREAD

**Issue by csuliweilong** [BioInf-Wuerzburg/proovread#22]
Hi @thackl,

As the proovread paper suggests, I first download the long reads of Ecoli from 

http://files.pacb.com/datasets/secondary-analysis/e-coli-k12-resequencing/1.3.0/e-coli-k12-resequencing-1.3.0.tgz

Then I choose /e-coli-k12-resequencing-1.3.0/data/filtered_subreads.fastq as the LR of Ecoli.

When running proovread using the following command
 
proovread -l ecoli-pb-001.fq -s ecoli-illumina.fq --pre pb-001

(ecoli-pb-001.fq is the chunked long read file of filtered_subreads.fastq)

A problem occured:

[Tue Oct 27 11:08:59 2015] Running proovread-2.13.10
[Tue Oct 27 11:08:59 2015] Reading core config
[Tue Oct 27 11:08:59 2015] Reading command line options
[Tue Oct 27 11:08:59 2015] Logging parameter to `pb-001/pb-001.parameter.log`
[Tue Oct 27 11:08:59 2015] Checking short read files

ecoli-illumina.fq
  Detected FASTQ format
  Estimated short read length: 200 +-0
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 14.2M

[Tue Oct 27 11:08:59 2015] Checking required binaries

  [ok] samtools-1.1    /homec/liweilong/app/samtools
  [ok] bwa-proovread   /homec/liweilong/proovread/bin/../util/bwa
  [ok] blastn-2.2.31   /homec/liweilong/app/blast/bin

[Tue Oct 27 11:08:59 2015] Running mode: mr
[Tue Oct 27 11:08:59 2015] Preparing long reads
Fastq::Parser::next_seq: ecoli-pb-001.fq, line 10, Couldn't find record start within last 5 lines, possibly corrupted file or wrong format at /homec/liweilong/proovread/bin/../lib//Fastq/Parser.pm line 316, <$fh> line 10.

However, I checked  ecoli-pb-001.fq, which is correct and complete in format:

head ecoli-pb-001.fq
@m120131_103014_sidney_c100278822550000001523007907041295_s1_p0/9/10724_13548
CTTGTGGTGATCTTTAACAAAGGGGCATTGTTCTGAGCTTTACGCTTGTA
CTGTGTGATCTACATGCTGTTCGGCAGCCATTGTTCCGAGAGAAACTATA
GAAAGAGTAAGCCGAGATCTTCTCGCAAAGTCCGCGGGCATGCGACAGCC
GACCATTTCGCTCCTTGGCGACGGCATGCGTGGCACTGATTGTTGATGCT
CCGCCTGCAGGCGATAAACCCGCGAACACGGTATGGCGAACCCGCCGCCT
GATAGTAAAAGGTACAATATGACCGGTATGACGGAAGTTAACAAGCTGGC
CAGCGAGCCGTCAGGTCAGGAATTTCTGGTAATTTACCCTTGGTGATGAA
ATACGGTATTGATACCTGAAAGTGCAGGAATCCGTGGCTAACATCAGGTA
CACACGGATTGCGAACACGTCACAGCCGTTTATCAGCGCACGAATCTGCG

Is the long read fq file of Ecoli correct?

How can I solve the problem this problem?

Best

Weilong

**Comment by thackl** [comment]
Your FASTQ file seems to use multiple lines per sequence (multiline FASTQ). This format is not recommend, it will break most FASTQ based tools including proovread. Proper FASTQ only uses 4 lines per entry, a single line for the sequence info..

**Comment by greatfireball** [comment]
You can use the `filtered_subreads.fasta` file instead of the `filtered_subreads.fastq` which is also part of the data package.

**Comment by csuliweilong** [comment]
I used seqtk to solve this problem successfully, thanks:)
