### ISSUE TITLE
Questions on dataset of proovread and request for evaluating scirpt 

### ISSUE THREAD

**Issue by csuliweilong** [BioInf-Wuerzburg/proovread#23]
Dear Thomas,

It is very exited to see your work on proovread.

In order to test its performance on long reads error correction, I am rerunning the experiment in the paper and planning to evaluate the result.

However, a few problems block me:

1. For Arabidopsis thaliana dataset, the PacBio long reads should be downloaded from 
   https://github.com/PacificBiosciences/DevNet/wiki/Arabidopsis-P5C3
But I can only see the corrected long reads and a huge amount of raw data in .h5 format there. Where can I find the uncorrected long reads of Arabidopsis thaliana in fastq format? Or should I convert the .h5 raw read files into fastq? Could you please provide me the downloading url or tell me your solution?

2. As the paper mentioned, the reader can request you for the script for evaluating the correction result of proovread. Could you please send me the script for evaluation?

Wait for your response.

Best

Weilong

**Comment by thackl** [comment]
Hi Weilong,

sorry for your troubles so far... 

1) As far as the data set goes, I couldn't even find the raw .h5 files. I followed https://github.com/PacificBiosciences/DevNet/wiki/A.-thaliana-%28Ler-0%29-20kb-Size-Selected-with-P4-C2#download-dataset and requested the data directly from PacBio. Just wrote them a short email and they provided me with links. For .h5 file conversion, I recommend https://github.com/thegenemyers/DEXTRACTOR/.

2) As for the script, you can find the code here: https://github.com/BioInf-Wuerzburg/prooveval. However, I would not recommend to use it. It is complicated to install, slow to run and outdated. The easiest and best way for assessment is to use mapPacBio.sh of the bbmap package (http://sourceforge.net/projects/bbmap/). You just map the corrected reads and bbmap, and it will compose a comprehensive summary statistic with about the same information that prooveval would produce.

**Comment by csuliweilong** [comment]
Hi @thackl ,

Thank you for your swift response.

I will try as you suggest

Sorry to push:)

Best

Weilong

**Comment by csuliweilong** [comment]
Hi @thackl,

I followed your suggestion to try downloading pre-assembled long reads of Arabidopsis thaliana from 

https://github.com/PacificBiosciences/DevNet/wiki/A.-thaliana-%28Ler-0%29-20kb-Size-Selected-with-P4-C2#download-dataset

However, I cannot download the data from `Listing of files for download` in the page, due to 404 Not Found error.

I suppose the data set in the url is missed.

Could you please provide me the ftp access for pre-assembled long reads of Arabidopsis thaliana, or alternative way to obtain the dataset?

Best 

Weilong

**Comment by greatfireball** [comment]
Have you tried to request access to the raw data set following the instructions given on https://github.com/PacificBiosciences/DevNet/wiki/A.-thaliana-%28Ler-0%29-20kb-Size-Selected-with-P4-C2#download-dataset?

> The raw data for this assembly is available upon request. Please contact us, or convey your interest via > twitter @PacBio. We appreciate if you could follow us on twitter so that we can direct message in response.

**Comment by csuliweilong** [comment]
Hi @greatfireball ,

Thank you for your suggestion.

I have emailed devnet@pacificbiosciences.com to get access to the raw data.

Weilong
