### ISSUE TITLE
Incompatibility with new SeqFilter comand line

### ISSUE THREAD

**Issue by marcelauliano** [BioInf-Wuerzburg/proovread#25]
Hey guys, I've just downloaded proovread and have installed all the dependencies, but still I'm getting an error message.

command line: ./proovread --sample --pre pr-sample --overwrite --cfg proovread.cfg

Error log:
[Tue Nov  3 17:56:09 2015] Checking short read files
  
F.antasticus_short.fq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Estimating approximate number of short reads: 50.0k

[Tue Nov  3 17:56:10 2015] Checking required binaries

  [ok] samtools-1.2    /data/scratch/muliano/scripts/samtools-1.2
  [ok] bwa-proovread   /data/scratch/muliano/scripts/proovread-master/bin/../ut\
il/bwa
  [ok] blastn-2.2.29   /usr/bin

[Tue Nov  3 17:56:10 2015] Running mode: sr
[Tue Nov  3 17:56:10 2015] Preparing long reads
#------------------------------------------------------------------------------#
perl -I/data/scratch/muliano/scripts/proovread-master/bin/../lib/ /data/scratch\
/muliano/scripts/proovread-master/bin/SeqFilter --fasta --in pr-sample/read-lon\
g/pr-sample.fq --line-width 80 --lower-case --out pr-sample/read-long/pr-sample\
.masked.fa --phred-offset 33
Unknown option: in
#------------------------------------------------------------------------------#
[Tue Nov  3 17:56:10 2015] Read IDs don't look like proper PacBio subread IDs.
Falling back to running mode: sr-noccs

[Tue Nov  3 17:56:10 2015] Running task bwa-sr-1
[Tue Nov  3 17:56:10 2015] Indexing Long reads
#------------------------------------------------------------------------------#
/data/scratch/muliano/scripts/proovread-master/bin/../util/bwa/bwa-proovread in\
dex pr-sample/read-long/pr-sample.masked.fa pr-sample/read-long/pr-sample.maske\
d.fa 2>pr-sample/bwa-sr-1/pr-sample_bwa.log
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
  
	Exited at 'main'
	'./proovread', line 1280
	Last call 'main::run_bwa'
	'./proovread', line 856
END

I was checking the new SeqFilter and it does not have a parameter --in 

Sounds to me the new SeqFilter version is not competible with proovread! Do you advice me on downloading an older one?

Thank you so much!

**Comment by thackl** [comment]
If you checked out proovread via the `git clone --recursive` it will automatically choose the right SeqFilter (v1.06). How did you install proovread?

**Comment by thackl** [comment]
I'm assuming, you have you been able to fix the problem. Feel free to reopen the issue if you haven't

**Comment by marcelauliano** [comment]
Thanks thackl! I manage to get it working! Sorry for not answering sooner!
