### ISSUE TITLE
failed at finished step.

### ISSUE THREAD

**Issue by juyouhui** [BioInf-Wuerzburg/proovread#27]
Hello @thackl ,
 In some case , i find proovread will failed at bwa-mr-finish step. What can i do to avoid this? 

[Tue Nov 10 10:41:33 2015] Batch 8/51
perl -I/home/juyh/bio/pacEC/proovread/bin/../lib/ /home/juyh/bio/pacEC/proovrea\
d/bin/bam2cns --append 1 --bam pb-003/bwa-mr-finish/pb-003.bam --bin-size 50 --\
coverage 22.5 --detect-chimera --ignore-hcr --ignore-weak-reads 0 --mask-weak-r\
eads 0 --max-ins-length 0 --max-ref-seqs 100 --no-use-ref-qual --prefix pb-003/\
bwa-mr-finish/pb-003.7 --qv-offset 33 --ref pb-003/bwa-mr-5/pb-003.fq --ref-off\
set 9781362
#------------------------------------------------------------------------------#
Use of uninitialized value in numeric gt (>) at /home/juyh/bio/pacEC/proovread/\
bin/../lib/Sam/Seq.pm line 591, <SAM> line 2086.
#------------------------------------------------------------------------------#
[Tue Nov 10 10:43:24 2015] bam2cns unexpectedly returned
        Exited at 'main'
        '/home/juyh/bio/pacEC/proovread/bin/proovread', line 1640
        Last call 'main::correct_sr_mt'
        '/home/juyh/bio/pacEC/proovread/bin/proovread', line 864

**Comment by thackl** [comment]
Hi @juyouhui,

sorry for the problem and thanks for reporting it. This is a rather important but also complicated issue. It will be quite hard to debug remotely, though. Is there any way that you could share some of the failing data, so I can examine it directly? I would need `pb-003/bwa-mr-finish/pb-003.bam` and `pb-003/bwa-mr-5/pb-003.fq` and the log of the run that failed.

**Comment by juyouhui** [comment]
Thanks, thackl. I find the error is due to the long reads file contain duplicated sequence, after check the log of bwa index step. After remove the duplicated sequence, everything is ok.

**Comment by thackl** [comment]
This make sense, although, proovread is checking reads for duplicate IDs during start up - so now I'm wondering, why this did not work in your case...
