### ISSUE TITLE
-u arguments not passed to the run_dazzler sub

### ISSUE THREAD

**Issue by JanDrouaud** [BioInf-Wuerzburg/proovread#28]
Hi all,

I tried to correct some Pacbio subreads using four datasets :
one Illumina SR, one Pacbio ccs and two Abyss assemblies (unitigs)
.. providing the first dataset with -s and the other ones each with -u
I got the following log (last 20 lines):

#------------------------------------------------------------------------------#

[Mon Nov 16 11:00:24 2015] Running task dazzler-utg
[Mon Nov 16 11:00:24 2015] Creating DAMs
#------------------------------------------------------------------------------#
fasta2DAM subreadsLe4passes-03-utg.dam subreadsLe4passes-03-utg0.fasta subreads\
Le4passes-03-utg1.fasta subreadsLe4passes-03-utg2.fasta 2>subreadsLe4passes-03-\
dazz.log
#------------------------------------------------------------------------------#
[Mon Nov 16 11:00:24 2015] Filter DAMs
#------------------------------------------------------------------------------#
DBsplit -x100 subreadsLe4passes-03-utg
#------------------------------------------------------------------------------#
DBsplit: Stub file (.db) of subreadsLe4passes-03-utg is junk
#------------------------------------------------------------------------------#
  
	Exited at 'main'
	'/shared/softwares/proovread/20151109/bin/proovread', line 1195
	Last call 'main::run_dazzler'
	'/shared/softwares/proovread/20151109/bin/proovread', line 813

After some investigations, I found that the proovread script created - within the dazzler-utg subfolder - symbolic links for the the "unitigs" fasta files devoided of basenames, ie containing only dirnames.
I found that the array holding the "unitigs" fasta file names ($opt_utg_file) was OK BEFORE executing the code section between lines 549 and 614, but not AFTER it was executed, for some reason that is still unclear to me.
Consequently, it seems that an empty array was passed to the run_dazzler sub, which then could not create correct links to the "unitigs" fasta files.
I am rather crappy with PERL, but I found that replacing all $_ references to "unitigs" fasta files by true variables within the code section between lines 549 and 614 fixed the issue.
Note: I use PERL v5.10.1. Could it be a version related problem ?

Best,

Jan

**Comment by thackl** [comment]
Hi Jan,

Thanks for reporting. I think I already fixed this issue last week, could check if you are running the latest version - and if the problem still persists?

**Comment by JanDrouaud** [comment]
Hi Thomas,
Indeed, the issue was fixed 5 days ago. The master branch is now OK. I apologize for my inopportune comment.
Best.
PS I found another problem, related to dazz_db in fact. fasta2DAM does not like unformatted sequence lines, ie more than 1000 nt long.  "unitigs" fasta files should then reformatted, using EMBOSS seqret for example, prior to proovread execution.
BTW. Your pipeline is great, far simpler, quicker and efficient than other well known tools.
Jan

**Comment by thackl** [comment]
Oh, no need to apologize - I'm always happy about any feedback -  and bugs that have already been fixed are kind of my favorite ;)

Regarding reformatting - You are right, I should include a check for that, I'm already checking the unitigs IDs, line length should not be a problem.

Also, you can simply use the SeqFilter tool that comes with proovread for reformating. Something like:

`proovread/bin/SeqFilter --line-width 80 --out reformatted.fasta utg.fasta`
