### ISSUE TITLE
Can I Input pair ends that are not merged?

### ISSUE THREAD

**Issue by marcelauliano** [BioInf-Wuerzburg/proovread#29]
Hey guys! 
So, I'm trying to correct my PacBIo DNAg reads, and I have about 70x coverage with Illumina short reads. But the thing is this set is divided between 180pb that can be merged, and 500bp that can't. So I was wondering if there is a way I can input unmerged reads to prooveread? Because I was having a look at the parameter -s and it says that multiple libs can be specified multiple times: does it mean that I can input also the pairs subsequently? Like -s 500bp.R1.fq -s 500bp.R2.fq ? 

Thanks a lot!

ps: If opening a Issue is not the right way to ask this question, please just let me know how it would be the most appropriate way! thanks!

**Comment by thackl** [comment]
Yes, you can use multiple unmerged read libraries, and you can also combine them with merged libraries.

´proovread -s 180pb_merged.fq -s 500_1.fq -s 500_2.fq`

**Comment by marcelauliano** [comment]
Thanks a lot. Thomas! Only one more question: as the genome I'm assembling in highly repetititve (about 40%) I haven't succed in finishing assemblies with allpaths or masurca only with short fragment Illumina reads. But Masurca manage to construct some supereads. I was thinking about inputing them as unitigs together with the PE for the correction. But this masurca superreads were constructed with this same PE data. My question is: would that be a conceptual problem if I input unitigs and the PE they were constructed with? I guess not?

**Comment by thackl** [comment]
No, that's not a problem at all, rather the opposite actually... But guessing from you repetitiveness and assembly problems you are dealing with a quite large genome. Running proovread for GB sized genomes requires quite a lot of computational power.. If you need some more feedback on that, you can write me a short mail, maybe quickly describing your data set.

Cheers

**Comment by marcelauliano** [comment]
Thanks Thomas!!! Should I write to thomas.hackl@uni.wuerzburg.de ?

**Comment by thackl** [comment]
yes, or my github address works as well.

**Comment by marcelauliano** [comment]
Hey Thomas! I was already expecting to run it for a while! So, my kmer
analysis says the genome to be around 1,2 Gb in size. Diploid.
I have:
419,000,000 PE 180 bp (merging now),
307,897,804 500bp PE (can't be merged)
280,000,00 of mate pairs

 AND around 1,000,000 PacBio reads (mean 6,8 Kb in size for subreads) that
needs to be corrected.

Any thoughts on how much memory and nodes should I dedicate for this? We
have a cluster with a thousand cores and 3T of Ram.

Thanks a lot for offering help on this too!!! =)

2015-11-24 12:34 GMT+01:00 Thomas Hackl <notifications@github.com>:

> yes, or my github address works as well.
>
> On 24.11.2015 12:19, Marcela wrote:
> > Thanks Thomas!!! Should I write to thomas.hackl@uni.wuerzburg.de
> > <mailto:thomas.hackl@uni.wuerzburg.de> ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/BioInf-Wuerzburg/proovread/issues/29#issuecomment-159234689
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BioInf-Wuerzburg/proovread/issues/29#issuecomment-159237804>
> .
>



-- 
Msc Marcela Uliano da Silva

PhD Student at Universidade Federal do Rio de Janeiro - Brazil
Visiting researcher at Berlin Center for Genomics in Biodiversity Research
(BeGenDiv)
Botanischer Garten und Botanisches Museum Berlin-Dahlem
Berlin - Germany
CV:  http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4261864A3
website: http://improvisocientifico.blogspot.com.br/
<http://improvisocientifico.blogspot.com.br/>

**Comment by marcelauliano** [comment]
Hey Thomas, the email always returns when I try to write you on  thomas.hackl@uni.wuerzburg.de !
Maybe after we discuss it we could erase this last comment about my data?

Thank you!!

**Comment by thackl** [comment]
It's a typo: thomas.hackl@uni-wuerzburg.de   ". -> -"

**Comment by marcelauliano** [comment]
Right! Thanks! Just emailed you! =)
