### ISSUE TITLE
--sample-run error

### ISSUE THREAD

**Issue by noncodo** [BioInf-Wuerzburg/proovread#30]
I'm trying to get proovread-flex to run, but get this error in the final stages (including when running --sample-run). Any ideas how to debug this? 

[Sun Nov 29 22:14:58 2015] Batch 2/2
perl -I/Users/myname/apps/proovread/bin/../lib/ /Users/myname/apps/pr\
oovread/bin/bam2cns --append 1 --bam pr-Fa/bwa-sr-1/pr-Fa.bam --bin-size 20 --c\
overage 11.25 --haplo-coverage --ignore-weak-reads 0 --mask-weak-reads 0 --max-\
ins-length 0 --max-ref-seqs 100 --prefix pr-Fa/bwa-sr-1/pr-Fa.1 --qv-offset 33 \
--ref pr-Fa/read-long/pr-Fa.fq --ref-offset 212420
#------------------------------------------------------------------------------#
haploc_consensus?? at /Users/myname/apps/proovread/bin/bam2cns line 432, <\
SAM> line 123.
#------------------------------------------------------------------------------#
[Sun Nov 29 22:14:58 2015] bam2cns unexpectedly returned
	Exited at 'main'
	'./proovread', line 1635
	Last call 'main::correct_sr_mt'
	'./proovread', line 869

**Comment by thackl** [comment]
proovread-flex is still experimental. What are you trying to do and why do you want to run proovread-flex?

**Comment by noncodo** [comment]
Hi Thomas, 

I’m trying to “polish” Oxford nanopore reads with HiSeq data. However, the sample test didn’t run, so I am thinking perhaps there is something wrong with the compilation (Mac OSX 10.11). There were a lot of warnings and I’m not 100% sure everything worked properly. I’ll double check in the near future. 

Do you believe this might also new the issue?

**Comment by thackl** [comment]
Hi noncodo,

I hope you got things going. I will close this issue for now. Feel free to reopen/open a new one if you still encounter issues
