### ISSUE TITLE
proovread fails with "unknown mode"

### ISSUE THREAD

**Issue by cschu** [BioInf-Wuerzburg/proovread#31]
Hi,

I am trying to run proovread like this
proovread -l ../Sample_1/data/filtered_subreads.fastq -s ../ac2v.R1.fq -s ../ac2v.R2.fq 

which will result in an error (full output given below);

"  unknown mode sr
	Exited at 'main'
	'/tsl/software/testing/bin/core/../..//proovread/2.12/x86_64/bin/proovread', li
ne 654
" 

If I specify -m sr or -m legacy it will also fail with the same error.

Any input would be appreciated.

Thanks!
Christian

Full job output:
[Mon Dec  7 17:20:09 2015] Running proovread-2.13.10
[Mon Dec  7 17:20:09 2015] Reading core config
Odd number of elements in hash assignment at /tsl/software/testing/bin/core/../..//proovread/2.12/x86_64/bin/proovread line 100.
Use of uninitialized value in list assignment at /tsl/software/testing/bin/core/../..//proovread/2.12/x86_64/bin/proovread line 100.
[Mon Dec  7 17:20:09 2015] Reading command line options
[Mon Dec  7 17:20:09 2015] Logging parameter to `proovread/proovread.parameter.l
og`
[Mon Dec  7 17:20:09 2015] Checking short read files
  
ac2v.R1.fq
  Detected FASTQ format
  Estimated short read length: 75 +-2
  Etimated short read quality offset: 64
  Estimating approximate number of short reads: 72.0M
  
ac2v.R2.fq
  Detected FASTQ format
  Estimated short read length: 75 +-2
  Etimated short read quality offset: 64
  Estimating approximate number of short reads: 71.9M
#------------------------------------------------------------------------------#
  unknown mode sr
	Exited at 'main'
	'/tsl/software/testing/bin/core/../..//proovread/2.12/x86_64/bin/proovread', li
ne 654

**Comment by thackl** [comment]
Something already goes wrong while proovread processes you core config (line 2/3 in log). Did you change anything in the  config? proovread should actually catch the problem while reading the config and exit - sorry about that...

**Comment by cschu** [comment]
Thanks for the reply. The core config would be the proovread.cfg? I have not touched that one and I am not specifying any custom config file.

**Comment by thackl** [comment]
I thought so. It seems that the path to the config is not generated properly - proovread.cfg  should be here: `/tsl/software/testing/bin/core/../..//proovread/2.12/x86_64/proovread.cfg`. Is that the case?

The location of the config is determined by first locating the proovread script location using Perl's `FindBin $RealBin` and then going up one directory. To quickly check, `cd` into `proovread/bin/` and paste the following snippet in your command line. It should print the paths and whether or not the config could be found.

``` bash
perl -MFindBin -e '$bin_dir = $FindBin::RealBin;
  print "$bin_dir\n"; $cfg_dir = "$bin_dir/../proovread.cfg"; 
  print "$cfg_dir\n"; print "config", -e $cfg_dir ? " found" : " not found", "\n"'
```

**Comment by cschu** [comment]
No, that was not the case. The .cfg is located in ...../x86_64/../src/proovread.cfg. After I copied it to the location you suggested, your Perl snippet finds it and I could submit the proovread job successfully to the job-queueing system. (Well, initially, now it wants samtools-1.1 but that is another story.)
Thanks for the help!

**Comment by thackl** [comment]
Ah, I see. But their is a more general problem. If I'm assuming correctly, you moved only parts of the proovread distribution to your software folder. That will not work. You need to keep the entire folder structure as it is for proovread to find all its libraries and dependencies. The easiest thing is to keep everything in `src/` and create a link to the proovread main script in `bin`. Something like `cd ...x86_64/bin/; ln -s ../../src/proovread/bin/proovread`

**Comment by cschu** [comment]
Thank you, that solved this issue and a follow-up issue with bam2cns unexpectedly exiting.

**Comment by thackl** [comment]
Great, let me know if you run into other issues.
