### ISSUE TITLE
uninitialized value $po

### ISSUE THREAD

**Issue by pengchy** [BioInf-Wuerzburg/proovread#34]
Hi proovread developers,
When I use proovread version 2.12, I encountered the following error message for the PacBio subreads file. But without this error message for the ROI file. The different between these two files should be the format of the IDs. In subreads the id looks like: 
@m141107_035137_42199_c100681802550000001823139002281580_s1_p0/125271/15046_18462
while the ROI reads id looks like:
@c2628/f67p16/1523 isoform=c2628;full_length_coverage=67;non_full_length_coverage=16;isoform_length=1523

============= the error message ==========
Use of uninitialized value $po in subtraction (-) at /path/to/proovread-master/bin/../lib/Fastq/Seq.pm line 903, <$fh> line 3.

Thank you and best,
Pengcheng Yang

**Comment by thackl** [comment]
`$po` refers to phred offset - seems like there is an issue in determining the offset for the ROI file. Could you post a few reads from your roi file here (at least the quality lines)

**Comment by pengchy** [comment]
Hi Thomas,
I have found the reason that the quality line of the subreads are "I", which were converted from fasta format and the quality was replaced with "I" for all sequences.

I will run proovread using the original quality value.

Best,
Pengcheng

**Comment by thackl** [comment]
Yeah, the problem is that if you have 40 values starting at 33 or 64, 
there is a small window of overlap. "I" is in this window, therefore the 
automatic detection of the offset fails.
