### ISSUE TITLE
Can I use proovread to correct my Low quality consensus sequences from IsoSeq_pipe? 

### ISSUE THREAD

**Issue by 52teth** [BioInf-Wuerzburg/proovread#41]
I have used pacbio's SMRT Analysis IsoSeq_pipe module to generate my consensus sequences. After polished by quiver process, I have got low quality and high quality consensus sequences. Now I want to correct the low quality consensus sequences using Hiseq short reads. So Can I use proovread to correct my Low quality consensus sequences from IsoSeq_pipe? And how can I set proovread.cfg?

Thanks a lot for reply!

**Comment by thackl** [comment]
I have not done that, but in theory, it should be possible. You don't need to configure a lot. Account for the uneven coverage in your illumina set by using `--no-sampling`. Anything else should work out of the box.

**Comment by 52teth** [comment]
Thanks a lot @thackl ! BTW, since my work is for transcript data, should I reset the proovread.cfg? Is there any advice for the setting of proovread.cfg? Or just use the default proovread.cfg?

**Comment by thackl** [comment]
Just use the default for now. Maybe start with a small test set (couple 
of Mbp). You can send me the log of your proovread run afterwards, then 
I'll have a better idea, if some parameters need tuning.

**Comment by 52teth** [comment]
Thanks a lot!
 I'll have a try now!

**Comment by 52teth** [comment]
Hi thackl . Here is the run log and the parameter log. Should I change the parameter and rerun?Thanks for your suggestion.
[pb-001.chim.tsv.txt](https://github.com/BioInf-Wuerzburg/proovread/files/88396/pb-001.chim.tsv.txt)

[pb-001.parameter.log.txt](https://github.com/BioInf-Wuerzburg/proovread/files/88397/pb-001.parameter.log.txt)



[proovread_00001.sh.txt](https://github.com/BioInf-Wuerzburg/proovread/files/88395/proovread_00001.sh.txt)
