### ISSUE TITLE
gmapper-ls: /lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by EricDeveaud** [BioInf-Wuerzburg/proovread#43]
this is the problem that arise when distributing binaries.

instead of distributing binaries, let the user compile their own Srhimp tool and use it from the path.

I would say the same apply to other utils, except your own modified bwa.

**Comment by thackl** [comment]
Binaries are simply distributed for convenience. To use SHRiMP from PATH, just customize the config:
```
## shrimp2 (gmapper-ls) path, set '' to look in PATH
## dont forget the trailing /
'shrimp-path' => $RealBin.'/../util/shrimp-2.2.3/',
```
In your case put `'shrimp-path' => ''` into a file, for example my-proovread.cfg, and run `proovread -c my-proovread.cfg ...`

**Comment by EricDeveaud** [comment]
what I've done. 

it was just for information
