### ISSUE TITLE
sample run gives No sequences found matching given filter criteria

### ISSUE THREAD

**Issue by litianqi715** [BioInf-Wuerzburg/proovread#5]
The environment of my computer is Red Hat Enterprise Linux Server release 6.2 (Santiago), perl 5.10.1, ncbi-blast+2.2.30 and samtools1.2.
I ran command proovread --sample-run in bash. It gave out the following error messages several times:

Can't open perl script "/public/opt/sc/program/proovread/bin/SeqChunker-perl": No such file or directory
 
but continued running. At last it gave out the following message: 

#------------------------------------------------------------------------------#
[17:30:44] No sequences found matching given filter criteria
[15-05-13 17:30:44] [siamaera] Input neither FASTA nor FASTQ
#------------------------------------------------------------------------------#
[Wed May 13 17:30:44 2015] Cleaning up
Wed May 13 17:30:44 2015] Total time spent 00:00:37
[Wed May 13 17:30:44 2015] Done

file pr-Fa.chim.tsv and pr-Fa.trimmed.fq has nothing in it, and pr-Fa.untrimmed.fq has all the sequences. Mask rate is 0.0%.

I don't know what to do now. Can you give me any suggestions?

**Comment by thackl** [comment]
There seems to be a problem with resolving the actual path to the SeqChunker-perl binary. First, give this dirty quick fix a try:
```bash
cd /public/opt/sc/program/proovread/bin/
ln -s ../util/SeqChunker/bin/SeqChunker-perl
```
Now, let's try to get to the real problem. The location of SeqChunker-perl is determined by proovread/bin/SeqChunker, which actually should be a symlink to ../util/SeqChunker/bin/SeqChunker. I can think of two reasons causing your problem:

1. Check if proovread/bin/SeqChunker really is a symlink on your system. If you used some form of reverse coping on proovread it is possible that the symlink wasn't preserved and instead the actual file was copied. It happens for example with `scp -r`, try to use `rsync` instead (https://smaftoul.wordpress.com/2008/08/13/recursive-scp-and-symlinks/).
2. The determination of the actual location of the SeqChunker binary fails on your systems for some reason - but let's look into this if 1. does not pan out.

**Comment by thackl** [comment]
I'm assuming you were able to resolve the problem and hence will close the issue.

Cheers

**Comment by litianqi715** [comment]
Sorry. Yes the rsync method is working and the sample run has passed. I has been running the project data and it consumes much time and make me wait a long time.
Sorry again.
