### ISSUE TITLE
~ is not resolved correctly in samtools path

### ISSUE THREAD

**Issue by nterhoeven** [BioInf-Wuerzburg/proovread#50]
## Problem
When proovread checks for the binary files, it doesn't find `samtools` when the path given starts with the users home directory shortened as `~` (e.g. `~/software/samtools`). This happens when the samtools location is exported in `$PATH` or specified in the `proovread.cfg`. Giving the full path (e.g. `/home/username/software/samtools`) works.

I tested this with a fresh install of **proovread-2.13.12** and **samtools 1.3**

### ~ in PATH
`~/software/samtools` in `$PATH`

```
[Wed Mar 23 12:55:44 2016] Checking required binaries

[main] unrecognized command '--version'
#------------------------------------------------------------------------------#
[Wed Mar 23 12:55:44 2016] Couldn't determine version of samtools, at least 1.1 
required
	Exited at 'main'
	'./bin/proovread', line 2066
	Last call 'main::check_binary'
	'./bin/proovread', line 666
```
 -> finds only old samtools version installed in `/usr/bin/`

### ~ in config
specified `~/software/samtools/` in `proovread.cfg`
```
[Wed Mar 23 12:59:37 2016] Checking required binaries

#------------------------------------------------------------------------------#
[Wed Mar 23 12:59:37 2016] Binary '~/software/samtools/samtools' 
neither in PATH nor executable
	Exited at 'main'
	'./bin/proovread', line 2055
	Last call 'main::check_binary'
	'./bin/proovread', line 666


$ ~/software/samtools/samtools --version
samtools 1.3
Using htslib 1.3
Copyright (C) 2015 Genome Research Ltd
```

### full path in config
specified `/home/username/software/samtools/` in `proovread.cfg`

```
[Wed Mar 23 13:04:34 2016] Checking required binaries

  [ok] samtools-1.3    /home/username/software/samtools

```

**Comment by thackl** [comment]
Yes, you need to provide the full path to binaries for proovread to find them. The problem is, that perl does not resolve `~` in paths, it is a shell alias.

`perl -e "~/path/to/samtools"` will always return false, only `perl -e "/home/mine/path/to/samtools"` will work.

Use `$HOME/` instead of `~` for your `$PATH` definitions to make it work in general.
