### ISSUE TITLE
Error processing --bam

### ISSUE THREAD

**Issue by mwyczalkowski** [BioInf-Wuerzburg/proovread#52]
I am getting errors running proovread with SR files in BAM format, but runs with equivalent SR data in FASTQ format succeed.

Sample dataset, attached below, is created as follows:
- Create minimal (5 read) LR FASTQ file from human PacBio reads ("LR.fq").
- Create a small SR BAM file (100 reads) from an Illumina 125bp paired end 60X BAM, aligned to GRCh38 ("SR.bam").  
- Create corresponding FASTQ file ("SR.fq") with `bedtools bamtofastq`.

I run proovread on SR.fq (Test A) and SR.bam (Test B) using commands below.  
- Test A: `perl proovread -l LR.fq -s SR.fq --pre test.A`
- Test B:`perl proovread -l LR.fq --bam SR.bam --pre test.B`

Test A succeeds, while Test B exists with an error while parsing `bam2cns` output:
[test.A.stdout.txt](https://github.com/BioInf-Wuerzburg/proovread/files/227329/test.A.stdout.txt)
[test.B.stdout.txt](https://github.com/BioInf-Wuerzburg/proovread/files/227328/test.B.stdout.txt)

Digging a bit deeper, the problem seems to stem from a call within `bam2cns` to `samtools view`.  Specifically, `bam2cns` issues the call,
`samtools view test.B/read-bam/test.B.bam "m140726_060753_42161_c100663510310000001823133012201490_s1_p0/61/0_2239:"`
To which `samtools` issues the warning:
> [main_samview] region "m140726_060753_42161_c100663510310000001823133012201490_\
> s1_p0/61/0_2239:" specifies an unknown reference name. Continue anyway.

It appears that `bam2cns` is trying to find the LR reference "m140..." which does not exist in test.B.bam; here, test.B.bam contains SR reads aligned to GRCh38.

A minimal example which reproduces this error is here:
[proovread.test.tar.gz](https://github.com/BioInf-Wuerzburg/proovread/files/228414/proovread.test.tar.gz)

Thanks in advance for your help.  Note that I'm a proovread newbie, so user error is always a possibility.  :)

**Comment by thackl** [comment]
Sorry for my late reply. Yes, the direct processing of bam files is not really well supported in proovread. I usually only use it for debugging purposes. Unfortunately I probably won't find the time to change this behaviour in the near future
