### ISSUE TITLE
BLAST engine error

### ISSUE THREAD

**Issue by kevlim83** [BioInf-Wuerzburg/proovread#54]
Hi,

I am trying to error correct some pacbio reads and have split my data into chunks of 100MB each successfully. I then proceeded with error correction using unitigs that I have constructed with illumina reads.

All the jobs completed with a Done message at the bottom, but I realized 3 out of my 456 chunks contain an error message in the middle, although the job finishes with a Done message.

The error message goes like this:
`
55.7M [=============================================>            ] ETA 00:07:42BLAST engine error: Warning: Sequence contains no data 
[16-04-29 23:04:14] [siamaera] Blast exited with error: 768 
`

I tried to search for this error message but I cant find any information about this. Could you please explain whether there could be problems with the error correction?

The original pacbio data contained 3.9G reads with total length of 71G bp.
After proovread, I concatenated the trimmed reads in each chunk and got 3.9M reads with total length of 7G bp.

Would error correction resulted in such a drastic change in file sizes? I am new to pacbio assembly and would appreciate any help.

Thanks.

Regards,
Kevin

**Comment by thackl** [comment]
Hi Kevin,

1) the error message is puzzling. Not really sure what happened there. I 
will try to look into that. However, I am currently moving to the US and 
I don't know when I will find the time to do so. I also might need some 
feedback/data from you to reproduce the error.

2) About the huge data loss - that is most like not related to the 
siamera error. But it is definitely not the way it should be. If I 
understand you correctly, you only used unitigs - no short reads in 
addition? Than that is most likely the problem. proovread is not really 
suited to work with unitigs alone, they are only supporting data for the 
short reads. So you might want to try to correct one of your chunks with 
short reads and see how that goes.

Cheers
Thomas

**Comment by kevlim83** [comment]
Hi Thomas,

Thanks for your reply. I hope you are doing well.

I am guessing these two issues are related and due to the fact that I only
used unitigs to correct for the pacbio reads.

I have now included about 65x of illumina short reads for the correction.
However, the tool takes a very long time to run. So, perhaps I can consult
you on this matter instead.

1\ Following some of your discussions in forums, I have split my files into
61 chunks of slightly less than 1X of the genome size, using 64 threads and
specifying that the iterative process stop after 85% mask, proovread still
takes about 2 days to correct for the error.

2\ I have access to some computational resource, including a dedicated
server that can run 96 threads with 1T memory, and a cluster but can only
use 160 cpus if I use the long queue (2 days should be fine).
But under these settings, it would still take a months time because if I
specify 64 threads, that will be 4 jobs at a time.

3\ I looked at the logs and think that the bottleneck is at the bwa-sr
stage. Do you think if any of the following strategies below are feasible:
A) creating more jobs but using less threads (if I use 12 threads, we would
create 21 job at a time) but would this advantage outweigh the overhead of
each job being slow?
B) modifying tool parameters - I realised that seqchunk is being called
prior to bwa-sr, can we modify the parameters? sr-coverage?
sr-chunk-number? sr-chunk-step? I have read your paper, but I still cant
figure what these parameters do. Can any of the parameters in bwa-sr be
modified to make the job faster?

Thanks very much. Your help would be greatly appreciated.

Regards,
Kevin

On Tue, May 3, 2016 at 3:48 AM, Thomas Hackl <notifications@github.com>
wrote:

> Hi Kevin,
>
> 1) the error message is puzzling. Not really sure what happened there. I
> will try to look into that. However, I am currently moving to the US and
> I don't know when I will find the time to do so. I also might need some
> feedback/data from you to reproduce the error.
>
> 2) About the huge data loss - that is most like not related to the
> siamera error. But it is definitely not the way it should be. If I
> understand you correctly, you only used unitigs - no short reads in
> addition? Than that is most likely the problem. proovread is not really
> suited to work with unitigs alone, they are only supporting data for the
> short reads. So you might want to try to correct one of your chunks with
> short reads and see how that goes.
>
> Cheers
> Thomas
>
> On 02.05.2016 05:11, kevlim83 wrote:
> > Hi,
> >
> > I am trying to error correct some pacbio reads and have split my data
> > into chunks of 100MB each successfully. I then proceeded with error
> > correction using unitigs that I have constructed with illumina reads.
> >
> > All the jobs completed with a Done message at the bottom, but I realized
> > 3 out of my 456 chunks contain an error message in the middle, although
> > the job finishes with a Done message.
> >
> > The error message goes like this:
> > |
> > 55.7M [=============================================> ] ETA
> > 00:07:42BLAST engine error: Warning: Sequence contains no data
> > [16-04-29 23:04:14] [siamaera] Blast exited with error: 768
> > |
> >
> > I tried to search for this error message but I cant find any information
> > about this. Could you please explain whether there could be problems
> > with the error correction?
> >
> > The original pacbio data contained 3.9G reads with total length of 71G
> bp.
> > After proovread, I concatenated the trimmed reads in each chunk and got
> > 3.9M reads with total length of 7G bp.
> >
> > Would error correction resulted in such a drastic change in file sizes?
> > I am new to pacbio assembly and would appreciate any help.
> >
> > Thanks.
> >
> > Regards,
> > Kevin
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/BioInf-Wuerzburg/proovread/issues/54>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BioInf-Wuerzburg/proovread/issues/54#issuecomment-216342018>
>

ᐧ

**Comment by thackl** [comment]
Hi Kevin,

sorry for the late reply. I just moved to Boston and getting settled takes some time.

1\ Your strategy makes sense so far. Two days per job for a large genome is kind of sad but it happens.

2&3\ So yes, bwa-sr is usually the bottleneck. I don't think you could save a reasonable amount of time by going for more jobs at less threads. Modifying the seqchunker parameters is equal to reducing overall Illumina coverage. Right now, you are using 65X, which is good (have you specified `--coverage` accordingly - otherwise 50X is assumed, which would make things slower). You can go with lower coverages and reduce proovreads trimming sensitivity to also make use of corrected regions with weak support. But that only makes sense if your current setup works well and you not already are loosing a lot of data during trimming.

4\ The best ways to save some runtime are a) merging overlapping reads with tools like FLASh (https://ccb.jhu.edu/software/FLASH/) - proovread automatically chooses less sensitive mapping options for longer reads, and b) reducing repeat data using digital normalization. bbnorm.sh of the bbmap package does a good job. On large plant genomes I removed 25-50% of short reads prior to correction, which speed up the entire process up to 4-10 times without getting worse correction results.

Nevertheless, in particular for a large data set such as yours, you might also want to look into alternative tools such as LoRDEC or LoRMA, which use de-bruijn graph strategies and require much less cpu power
