### ISSUE TITLE
empty trimmed.fq file

### ISSUE THREAD

**Issue by el42008** [BioInf-Wuerzburg/proovread#55]
I did try to correct my pacbio reads adding 6 illumina short read files and I got empty trimmed.fq. It seems that all reads were not trimmed. Chim.tsv and ignored.tsv files are also empty. is this expected? How can I know that the reads were good enough and that is why they were not trimmed?

**Comment by thackl** [comment]
Can you send me your log file?

**Comment by el42008** [comment]
Thank you for you quick reply. I think I solved it by adding --coverage 22.5
Is this looking fine for you?
Cheers

2016-05-08 5:14 GMT+01:00 Thomas Hackl <notifications@github.com>:

**Comment by el42008** [comment]
Hi,

I have another question. When giving the short reads to the software by -s
I did it by adding -s Lib1_R1 -s Lib1_R2 -s Lib2_R1 -s Lib2_R2 and so on.
Is this a proper way to do it or do I need to merge the pairs in one single
file?

Cheers

2016-05-08 15:09 GMT+01:00 Elena LOPEZ GIRONA <elenalopezgirona@gmail.com>:

**Comment by thackl** [comment]
--coverage 22 looks fine and specifying multiple libraries with -s is the proper way.
