### ISSUE TITLE
bam2cns fails using unitig mode 

### ISSUE THREAD

**Issue by cartal** [BioInf-Wuerzburg/proovread#59]
Hi

I've been trying to run proovread using units instead of Illumina reads as follows:

_$ProovRead/proovread -l $subset -u $utg -t 16 -p pb-001_

However, I always got this error:

_bam2cns unexpectedly returned
Exited at 'main'
'/home/cartal/Tools/proovread/bin/proovread', line 1634
Last call 'main::correct_sr_mt'
'/home/carlosta/Tools/proovread/bin/proovread', line 805_

After googling a bit, I found that this might be due to an issue with samtools 1.3 and that I should use samtools 1.2 instead: https://github.com/BioInf-Wuerzburg/proovread/issues/35. But I still get the same error.

Any ideas of how to fix this? 

Thanks in advance

**Comment by thackl** [comment]
Hi Carlos,

one issue is that proovread does not really do correction of pacbio 
reads with unitigs only. Unitigs can be used to support short reads, but 
short reads should always be supplied. This might already fix the problem.

To understand what went wrong in your case exactly, it would help if I 
could see the full log output of the run.

Cheers
Thomas

**Comment by cartal** [comment]
Hi Thomas,

Thank you for the quick reply. 

Ok, so I should include at least 30 X Illumina coverage together with the unitigs? Or can the Illumina coverage be somehow decreased? 

Here is the log file of the experiment. All modules required were located in my path. 

_+ ProovRead=/home/carlosta/Tools/proovread/bin
+ subset=pb-001.fq
+ utg=Pw.fermi-Illumina.OVL75.p2.fasta
+ /home/carlosta/Tools/proovread/bin/proovread -l pb-001.fq -u Pw.fermi-Illumina.OVL75.p2.fasta -t 16 -p pb-001
[Tue May 17 22:47:18 2016] Running proovread-2.13.13 under Perl 5.18.4
[Tue May 17 22:47:18 2016] Reading core config
[Tue May 17 22:47:18 2016] Reading command line options
[Tue May 17 22:47:18 2016] Logging parameter to `pb-001/pb-001.parameter.log`

[Tue May 17 22:47:18 2016] Checking alternative read files
  
Pw.fermi-Illumina.OVL75.p2.fasta
  Detected FASTA format
  Estimating fragment length: 399 +-313
  Estimating approximate number of fragments: 42.9M

[Tue May 17 22:49:02 2016] Checking required binaries

  [ok] samtools-1.2    /sw/apps/bioinfo/samtools/1.2/milou/bin
  [ok] blasr           /pica/h1/carlosta/Tools/proovread/bin/../util/blasr-1.3.1
  [ok] blastn-2.2.31   /sw/apps/bioinfo/blast/2.2.31+/milou/bin

[Tue May 17 22:49:02 2016] Running mode: tug
[Tue May 17 22:49:02 2016] Preparing long reads
#------------------------------------------------------------------------------#
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/SeqFilter --fasta --in pb-001/read-long/pb-001.fq --line-width 80 -\
-lower-case --out pb-001/read-long/pb-001.masked.fa --phred-offset 33
[22:49:04] /pica/h1/carlosta/Tools/proovread/bin/SeqFilter-1.06
[22:49:04] --in: pb-001/read-long/pb-001.fq
[22:49:04] Detected FASTQ format, pared-offset 33
    0  [                                                          ]
  386k [=>                                                        ]
 21.0M [=========================================================>] TTS 00:00:00
#------------------------------------------------------------------------------#
[22:49:04] Input
[22:49:04] Sequences             1261 #
[22:49:04] Total             10442569 bp
[22:49:04] Longest              29703 bp
[22:49:04] Shortest               520 bp
[22:49:04] N50                  10662 bp
[22:49:04] N90                   4959 bp
#------------------------------------------------------------------------------#
[22:49:04] Filtered
[22:49:04] Sequences             1261 #
[22:49:04] Total             10442569 bp
[22:49:04] Longest              29703 bp
[22:49:04] Shortest               520 bp
[22:49:04] N50                  10662 bp
[22:49:04] N90                   4959 bp
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/ccseq --bwa-path /pica/h1/carlosta/Tools/proovread/bin/../util/bwa/\
 --threads 16 --pre pb-001/ccs-1 <pb-001/read-long/pb-001.fq | tee pb-001/ccs-1\
/pb-001.fq | perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carl\
osta/Tools/proovread/bin/SeqFilter --line-width 80 --phred-offset 33 --phred-ma\
sk 20,41,160,260,60,0.7 --fasta --out pb-001/ccs-1/pb-001.masked.fa --base-cont\
ent N --tsv - --quiet
[16-05-17 22:49:04] [ccseq] Reading STDIN
[16-05-17 22:51:06] [ccseq] Processed 1261 subreads from 935 reads
[16-05-17 22:51:06] [ccseq]   241 consensus + 694 bypassed single subheads
#------------------------------------------------------------------------------#

[Tue May 17 22:51:08 2016] Running task blasr-utg
[Tue May 17 22:51:08 2016] Mapping reads `Pw.fermi-Illumina.OVL75.p2.fasta`
#------------------------------------------------------------------------------#
/pica/h1/carlosta/Tools/proovread/bin/../util/blasr-1.3.1/blasr Pw.fermi-Illumi\
na.OVL75.p2.fasta pb-001/ccs-1/pb-001.masked.fa -affineAlign  -minMatch 17 -agg\
ressiveIntervalCut  -noSplitSubreads  -nproc 16 -nCandidates 100 -bestn 100 -sa\
m 2>pb-001/blasr-utg/pb-001_blasr.log | samtools view -@ 16 -bS /dev/fd/0 >pb-0\
01/blasr-utg/pb-001_tmp.bam
#------------------------------------------------------------------------------#

[Wed May 18 03:16:40 2016] Sorting BAM `pb-001/blasr-utg/pb-001.bam`
#------------------------------------------------------------------------------#
samtools sort -m 2G -@ 9 -T pb-001/blasr-utg/pb-001_tmp -o pb-001/blasr-utg/pb-\
001.bam pb-001/blasr-utg/pb-001_tmp.bam
#------------------------------------------------------------------------------#
[bam_sort_core] merging from 198 files...

[Wed May 18 04:21:05 2016] Indexing BAM `pb-001/blasr-utg/pb-001`
#------------------------------------------------------------------------------#
samtools index pb-001/blasr-utg/pb-001.bam
#------------------------------------------------------------------------------#

[Wed May 18 04:33:57 2016] Correcting Sequences (10 batches)
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 1/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.0 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 0 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 2/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.1 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 1787710 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 3/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.2 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 3751849 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 4/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.3 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 5446010 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 5/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.4 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 7206447 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 6/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.5 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 8960920 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 7/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.6 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 10641817 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 8/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.7 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 12312486 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 9/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.8 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 14179952 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
[Wed May 18 04:33:57 2016] Batch 10/10
perl -I/pica/h1/carlosta/Tools/proovread/bin/../lib/ /pica/h1/carlosta/Tools/pr\
oovread/bin/bam2cns --append 1 --bam pb-001/blasr-utg/pb-001.bam --bin-size 150\
 --coverage 1 --fallback-phred 30 --ignore-weak-reads 0 --invert-scores --mask-\
weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.3 --prefix p\
b-001/blasr-utg/pb-001.9 --qual-weighted --qv-offset 33 --ref pb-001/ccs-1/pb-0\
01.fq --ref-offset 15910255 --rep-coverage 7 --utg-mode 
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
[Wed May 18 04:47:42 2016] bam2cns unexpectedly returned
	Exited at 'main'
	'/home/carlosta/Tools/proovread/bin/proovread', line 1634
	Last call 'main::correct_sr_mt'
	'/home/carlosta/Tools/proovread/bin/proovread', line 805_

**Comment by thackl** [comment]
Okay, a little weird - there should have been an error message from 
bam2cns right before the 'returned unexpectedly' message - not really 
sure what went wrong. But I guess including short reads won't fix the 
problem. I will have to look into that, but it might take a while.

My suggestion for now: unitigs only help so much, in some cases even 
decrease correction performance, and the real power is with the short 
reads anyway. Try to run a correction with short reads only. Coverage 
can be lower than 30X, just specify accordingly with --coverage. 
Ideally, if short reads are from an overlapping library, pairs should be 
merged into in single fragments beforehand. Also, short read mapping is 
computationally quite intensive, so expect long runtimes.

Your genome appears to be rather large, have a look at 
https://github.com/BioInf-Wuerzburg/proovread/issues/48 on how to set 
chunk sizes etc. If you don't have the computational resources to run 
the exhaustive mapping based approach of proovread, you might want to 
look at other correction programs, such as LoRDEC or Jabba.

Cheers
Thomas
