### ISSUE TITLE
bam2ncs returns unexpectedly

### ISSUE THREAD

**Issue by bwlang** [BioInf-Wuerzburg/proovread#6]
I'm trying to run proovread using daligner, it makes some progress but then fails at the "Correcting Sequences" step.

Did I do something wrong, or is it a bug?

Here's my command line:
```
PERL5LIB=${HOME}/perl5/lib/perl5 ~/src/proovread/bin/proovread -c proovread.cfg \
--long-reads ovi-001.fasta  \
--short-reads /mnt/ngsarchive/langhorst/ovi/nextseq_ovi_runs/pear/ovi_run_15_pear.assembled.fastq \
--short-reads /mnt/ngsarchive/langhorst/ovi/nextseq_ovi_runs/pear/ovi_run_17_pear.assembled.fastq \
-u /mnt/ngsarchive/langhorst/ovi/sparseassembler/Contigs.txt \
--coverage=60
```
I have about 1B short reads, (~250bp) 100 40-60kb  pacbio reads (for a trial) and a bunch of contigs from illumina reads (generated by sparseassembler)

The only change to the default cfg is:
```
'mode' => 'mr+dazz-utg',
```

Here's the partial output.

```
[Sat May 16 09:22:31 2015] Correcting Sequences (1 batches)
#------------------------------------------------------------------------------#
[Sat May 16 09:22:31 2015] Batch 1/1
perl -I/home/NEB/langhorst/src/proovread/bin/../lib/ /home/NEB/langhorst/src/pr\
oovread/bin/bam2cns --append 1 --bam proovread/dazzler-utg/proovread.bam --bin-\
size 150 --cfg proovread.cfg --coverage 1 --fallback-phred 30 --ignore-weak-rea\
ds 0 --mask-weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --min-ncscore 3.\
7 --prefix proovread/dazzler-utg/proovread.0 --qual-weighted --qv-offset 33 --r\
ef proovread/ccs-1/proovread.fq --ref-offset 0 --rep-coverage 7 --utg-mode
#------------------------------------------------------------------------------#
[main_samview] region "m150113_061447_42200_c100741892550000001823163306051572_\
s1_p0/2990/4273_51724" specifies an unknown reference name. Continue anyway.
#------------------------------------------------------------------------------#
[Sat May 16 09:22:34 2015] bam2cns unexpectedly returned
        Exited at 'main'
        '/home/NEB/langhorst/src/proovread/bin/proovread', line 1597
        Last call 'main::correct_sr_mt'
        '/home/NEB/langhorst/src/proovread/bin/proovread', line 804
```

**Comment by thackl** [comment]
The invocation looks okay. There might be a problem with the daligner to sam conversion, though. Can you please have a look at the IDs from the reference file and the bam file header.
``` bash
grep "^@m" proovread/ccs-1/proovread.fq
samtools view -H proovread/dazzler-utg/proovread.bam
# missing IDs
(samtools view -H proovread/dazzler-utg/proovread.bam | grep -oP '(?<=SN:)\S+'; 
grep -oP '(?<=^@)\S+' proovread/ccs-1/proovread.fq) | sort | uniq -u
```

**Comment by bwlang** [comment]
Hmm - there are no headers in the bam... digging a bit further I see in this error log.

It looks like that is your module... do I need to do something to get it be visible?

Thanks!

Can't locate Fasta/Parser.pm in @INC (you may need to install the Fasta::Parser module) (@INC contains: /home/NEB/langhorst/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/NEB/langhorst/perl5/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/NEB/langhorst/src/proovread/bin/dazz2sam line 17.
BEGIN failed--compilation aborted at /home/NEB/langhorst/src/proovread/bin/dazz2sam line 17.

**Comment by thackl** [comment]
I think I found the problem. Could you checkout the the develop branch and pull.
```bash
cd ~/src/proovread/
git checkout develop
git pull
```
Let me know if this fixes the issue.

Cheers

**Comment by bwlang** [comment]
This seems to have resolved the problem - Proovread is now performing the "mapping unitigs" step.
Thanks!

**Comment by thackl** [comment]
You're welcome and thanks a lot for taking the time testing the fix.
