### ISSUE TITLE
Can't exec "samtools": No such file or directory

### ISSUE THREAD

**Issue by thefantasticdron** [BioInf-Wuerzburg/proovread#60]
Hello,

I recently installed proovread on my system and I tested my installation using the command `./proovread --sample --pre pr-sample`, but I'm encountering an error. Here is my output:

<pre><code>
[Thu May 19 12:17:19 2016] Running proovread-2.13.12 under Perl 5.22.0
[Thu May 19 12:17:19 2016] Reading core config
[Thu May 19 12:17:19 2016] Reading command line options
[Thu May 19 12:17:19 2016] Logging parameter to `pr-sample/pr-sample.parameter.l
og`
[Thu May 19 12:17:19 2016] Checking short read files
  
F.antasticus_short.fq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Estimating approximate number of short reads: 50.0k

[Thu May 19 12:17:25 2016] Checking required binaries

  [ok] samtools-1.3    /global/software/samtools/samtools13/bin
  [ok] blastn-2.2.30   /global/software/blast/ncbi-blast-2.2.30+/bin

[Thu May 19 12:17:25 2016] Running mode: bam
[Thu May 19 12:17:25 2016] Preparing long reads
#------------------------------------------------------------------------------#
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/SeqFilter --fasta --in pr-sample/read-long/pr-sample.fq --line-width 80\
 --lower-case --out pr-sample/read-long/pr-sample.masked.fa --phred-offset 33
[12:17:26] /home/seanla/Software/proovread/bin/SeqFilter-1.06
[12:17:26] --in: pr-sample/read-long/pr-sample.fq
[12:17:26] Detected FASTQ format, phred-offset 33
  257k [=========================================================>] TTS 00:00:00
#------------------------------------------------------------------------------#
[12:17:26] Input
[12:17:26] Sequences              121 #
[12:17:26] Total               126422 bp
[12:17:26] Longest               1074 bp
[12:17:26] Shortest              1012 bp
[12:17:26] N50                   1045 bp
[12:17:26] N90                   1032 bp
#------------------------------------------------------------------------------#
[12:17:26] Filtered
[12:17:26] Sequences              121 #
[12:17:26] Total               126422 bp
[12:17:26] Longest               1074 bp
[12:17:26] Shortest              1012 bp
[12:17:26] N50                   1045 bp
[12:17:26] N90                   1032 bp
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
/global/software/samtools/samtools13/bin/samtools index pr-sample/read-bam/pr-s\
ample.bam
#------------------------------------------------------------------------------#

[Thu May 19 12:17:32 2016] Correcting Sequences (2 batches)
#------------------------------------------------------------------------------#
[Thu May 19 12:17:32 2016] Batch 1/2
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/bam2cns --append 1 --bam pr-sample/read-bam/pr-sample.bam --bin-size 20\
 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 \
--max-ref-seqs 100 --prefix pr-sample/read-bam/pr-sample.0 --qv-offset 33 --ref\
 pr-sample/read-long/pr-sample.fq --ref-offset 0 
#------------------------------------------------------------------------------#
[Thu May 19 12:17:32 2016] Batch 2/2
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/bam2cns --append 1 --bam pr-sample/read-bam/pr-sample.bam --bin-size 20\
 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 \
--max-ref-seqs 100 --prefix pr-sample/read-bam/pr-sample.1 --qv-offset 33 --ref\
 pr-sample/read-long/pr-sample.fq --ref-offset 212420 
#------------------------------------------------------------------------------#
Can't exec "samtools": No such file or directory at /home/seanla/Software/proov\
read/bin/bam2cns line 224.
#------------------------------------------------------------------------------#
[Thu May 19 12:17:33 2016] bam2cns unexpectedly returned
	Exited at 'main'
	'./proovread', line 1634
	Last call 'main::correct_sr_mt'
	'./proovread', line 736
</code></pre>

Any ideas on how I can fix this?
Thanks in advance.

**Comment by thackl** [comment]
Oh, you are right, that's a bug (I am assuming you set the samtools path 
in the config). Hot fix for now, run

export PATH=/global/software/samtools/samtools13/bin:$PATH

prior to calling proovread. That should work right away.

Cheers
Thomas

**Comment by thefantasticdron** [comment]
Thank you!
