### ISSUE TITLE
'[main_samview] region "long_contamination_0:" specifies an unknown reference call name' error after PATH hotfix

### ISSUE THREAD

**Issue by thefantasticdron** [BioInf-Wuerzburg/proovread#61]
Hello again,

I have encountered another error when running `./proovread --sample --pre pr-sample --overwrite` after running `export PATH=/global/software/samtools/samtools13/bin:$PATH` as per the solution to my previous [issue](https://github.com/BioInf-Wuerzburg/proovread/issues/60). Here is the output:

<pre><code>
[Thu May 19 13:08:25 2016] Running proovread-2.13.12 under Perl 5.22.0
[Thu May 19 13:08:25 2016] Reading core config
[Thu May 19 13:08:25 2016] Reading command line options
[Thu May 19 13:08:25 2016] Logging parameter to `pr-sample/pr-sample.parameter.l
og`
[Thu May 19 13:08:25 2016] Checking short read files
  
F.antasticus_short.fq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Estimating approximate number of short reads: 50.0k

[Thu May 19 13:08:26 2016] Checking required binaries

  [ok] samtools-1.3    /global/software/samtools/samtools13/bin
  [ok] blastn-2.2.30   /global/software/blast/ncbi-blast-2.2.30+/bin

[Thu May 19 13:08:26 2016] Running mode: bam
[Thu May 19 13:08:26 2016] Preparing long reads
#------------------------------------------------------------------------------#
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/SeqFilter --fasta --in pr-sample/read-long/pr-sample.fq --line-width 80\
 --lower-case --out pr-sample/read-long/pr-sample.masked.fa --phred-offset 33
[13:08:26] /home/seanla/Software/proovread/bin/SeqFilter-1.06
[13:08:26] --in: pr-sample/read-long/pr-sample.fq
[13:08:26] Detected FASTQ format, phred-offset 33
  257k [=========================================================>] TTS 00:00:00
#------------------------------------------------------------------------------#
[13:08:26] Input
[13:08:26] Sequences              121 #
[13:08:26] Total               126422 bp
[13:08:26] Longest               1074 bp
[13:08:26] Shortest              1012 bp
[13:08:26] N50                   1045 bp
[13:08:26] N90                   1032 bp
#------------------------------------------------------------------------------#
[13:08:26] Filtered
[13:08:26] Sequences              121 #
[13:08:26] Total               126422 bp
[13:08:26] Longest               1074 bp
[13:08:26] Shortest              1012 bp
[13:08:26] N50                   1045 bp
[13:08:26] N90                   1032 bp
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
/global/software/samtools/samtools13/bin/samtools index pr-sample/read-bam/pr-s\
ample.bam
#------------------------------------------------------------------------------#

[Thu May 19 13:08:33 2016] Correcting Sequences (2 batches)
#------------------------------------------------------------------------------#
[Thu May 19 13:08:33 2016] Batch 1/2
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/bam2cns --append 1 --bam pr-sample/read-bam/pr-sample.bam --bin-size 20\
 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 \
--max-ref-seqs 100 --prefix pr-sample/read-bam/pr-sample.0 --qv-offset 33 --ref\
 pr-sample/read-long/pr-sample.fq --ref-offset 0 
#------------------------------------------------------------------------------#
[Thu May 19 13:08:33 2016] Batch 2/2
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/bam2cns --append 1 --bam pr-sample/read-bam/pr-sample.bam --bin-size 20\
 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 \
--max-ref-seqs 100 --prefix pr-sample/read-bam/pr-sample.1 --qv-offset 33 --ref\
 pr-sample/read-long/pr-sample.fq --ref-offset 212420 
#------------------------------------------------------------------------------#
[main_samview] region "long_contamination_0:" specifies an unknown reference na\
me. Continue anyway.
#------------------------------------------------------------------------------#
[Thu May 19 13:08:33 2016] bam2cns unexpectedly returned
	Exited at 'main'
	'./proovread', line 1634
	Last call 'main::correct_sr_mt'
	'./proovread', line 736
</code></pre>

Thanks in advance!

**Comment by thackl** [comment]
Okay, weird, I can't actually figure out what happened, but `[Thu May 19 13:08:26 2016] Running mode: bam` is definitely wrong. That is only for reading bam files directly for debugging, rather than mapping short reads (mode: sr). Unfortunately, I cannot reproduce the problem by running the same command that you used. Did you make any changes to the config or does this happen with a freshly cloned distribution?

**Comment by thefantasticdron** [comment]
After deleting, recloning and making a fresh install, I no longer encounter the error, weird.
