### ISSUE TITLE
Does it matter if I have too high coverage from the short reads?

### ISSUE THREAD

**Issue by yfu** [BioInf-Wuerzburg/proovread#63]
I know that in the documentation, it is suggested that I should use 30-50X coverage from short reads. However, now I have >100X coverage from short reads. Should I downsample and use 50X from them, or, should I just feed all the reads to `proovread` and set the `--coverage` parameter to a greater value?

Thanks!

**Comment by thackl** [comment]
You can use all of your reads. If you set --coverage accordingly, proovread will downsample internally so runtime will be similar to 50x

Cheers
Thomas

**Comment by yfu** [comment]
Thanks, Thomas!
