### ISSUE TITLE
Log::Log4perl module

### ISSUE THREAD

**Issue by donlantican** [BioInf-Wuerzburg/proovread#64]
Hi, 

I'm getting this error whenever I execute proovread:

Can't locate Log/Log4perl.pm in @INC (you may need to install the Log::Log4perl module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at ./proovread line 11.

Thanks!

**Comment by donlantican** [comment]
Thanks @greatfireball! Unfortunately, I don't have any admin privilege to install this module in the env perl directory. I just added a line in the proovread perl script to make it work: use lib 'path/to/local/perl/directory';. Now, it is running perfectly! Cheers!

**Comment by greatfireball** [comment]
This is one of the possible solutions. Another possibility is the usage of `PERL5LIB` environmental variable. All folders in that variable are searched for `perl` modules loaded by the `use` or `require` statements. Therefore,  a code modification is not required any more.

Best Frank
