### ISSUE TITLE
Running proovread on sample data yields empty trimmed reads file

### ISSUE THREAD

**Issue by thefantasticdron** [BioInf-Wuerzburg/proovread#66]
Hello, it's me again.

After a fresh install of proovread, I tried testing it on the sample data using the command `./proovread --sample --pre pr-sample --overwrite`. After the program completed running, the file `pr-sample.trimmed.fq` was empty though `pr-sample.untrimmed.fq` was not empty. In stdout, there was the error message

```
[Wed Jun 15 09:46:58 2016] Quality trimming and siamaera filtering raw output
#------------------------------------------------------------------------------#
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/SeqFilter --in pr-sample/pr-sample.untrimmed.fq --min-length 500 --phre\
d-offset 33 --substr pr-sample/pr-sample.chim.tsv --trim-win 12,5 --out - | per\
l -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovread\
/bin/siamaera --blast-path /global/software/blast/ncbi-blast-2.2.30+/bin/ > pr-\
sample/pr-sample.trimmed.fq
[09:46:59] /home/seanla/Software/proovread/bin/SeqFilter-1.06
[09:46:59] --in: pr-sample/pr-sample.untrimmed.fq
[09:46:59] Detected FASTQ format, phred-offset 33
[09:46:59] --substr-file: pr-sample/pr-sample.chim.tsv
 6.17k [=>                                                        ]bash: line 4: blastn: command not found
[16-06-15 09:46:59] [siamaera] Blast exited with error: 32512
#------------------------------------------------------------------------------#
[Wed Jun 15 09:46:59 2016] Cleaning up
Wed Jun 15 09:46:59 2016] Total time spent 00:00:42
[Wed Jun 15 09:46:59 2016] Done
```

I changed my configuration file to include the paths to my samtools and blast binaries. I have enclosed files containing the complete output from stdout and my configuration file.

Any suggestions on how to fix this? Thanks.

[proovread_cfg.txt](https://github.com/BioInf-Wuerzburg/proovread/files/316575/proovread_cfg.txt)
[proovread_error.txt](https://github.com/BioInf-Wuerzburg/proovread/files/316577/proovread_error.txt)

**Comment by thackl** [comment]
Yes, I think there is a bug with promoting the paths from the config to the siameara module. Could you export the path to samtools and blast rather than putting them into the config for the time being?

Run something like the following in bash prior to calling proovread
```export PATH=/path/to/blast:/path/to/samtools/:$PATH```

**Comment by thefantasticdron** [comment]
Fantastic, `pr-sample.trimmed.fq` is non-empty now. Thanks.
