### ISSUE TITLE
bam2cns error: Odd number of elements in hash assignment at bam2cns line 67

### ISSUE THREAD

**Issue by thefantasticdron** [BioInf-Wuerzburg/proovread#67]
I've been testing proovread on PBSim simulated long reads and ART simulated short reads of a tuberculosis genome and I've encountered this error when running the tool on the data:

```
...
[Wed Jun 15 10:32:34 2016] Batch 4/20
perl -I/home/seanla/Software/proovread/bin/../lib/ /home/seanla/Software/proovr\
ead/bin/bam2cns --append 1 --bam proovread/bwa-sr-1/proovread.bam --bin-size 20\
 --cfg ../proovread.cfg --coverage 11.25 --ignore-weak-reads 0 --mask-weak-read\
s 0 --max-ins-length 0 --max-ref-seqs 100 --prefix proovread/bwa-sr-1/proovread\
.3 --qv-offset 33 --ref proovread/read-long/proovread.fq --ref-offset 7022806 
#------------------------------------------------------------------------------#
Odd number of elements in hash assignment at /home/seanla/Software/proovread/bi\
n/bam2cns line 67.
#------------------------------------------------------------------------------#
[Wed Jun 15 10:32:34 2016] bam2cns unexpectedly returned
	Exited at 'main'
	'./proovread', line 1634
	Last call 'main::correct_sr_mt'
	'./proovread', line 868
```

I've attached a text file containing the output from stdout, the configuration file, and files containing a few reads from my short reads and long reads files. 

[ecoli-long-d5_0001-sample.fastq.txt](https://github.com/BioInf-Wuerzburg/proovread/files/316682/ecoli-long-d5_0001-sample.fastq.txt)
[ecoli-short-single-d50-sample.fq.txt](https://github.com/BioInf-Wuerzburg/proovread/files/316685/ecoli-short-single-d50-sample.fq.txt)
[proovread-out.txt](https://github.com/BioInf-Wuerzburg/proovread/files/316684/proovread-out.txt)
[proovread.cfg.txt](https://github.com/BioInf-Wuerzburg/proovread/files/316683/proovread.cfg.txt)

Any ideas on how I can fix this? Thanks.

**Comment by thefantasticdron** [comment]
The command I used is `./proovread -c ../proovread.cfg` in the `proovread/bin` folder

**Comment by thefantasticdron** [comment]
I changed deleted the paths for blast and samtools from my configuration file and added the paths to the binaries to PATH as suggested in my previous issue and running the program again yielded the same error. The output and my new config file are attached below:

[proovread_out.txt](https://github.com/BioInf-Wuerzburg/proovread/files/316878/proovread_out.txt)
[proovread.cfg.txt](https://github.com/BioInf-Wuerzburg/proovread/files/316879/proovread.cfg.txt)

**Comment by thackl** [comment]
I ran your .cfg on my installation without problems. There is, however, 
something odd about your usage. If I am correct, you modified the 
proovread.cfg file in the proovread installation folder? That file 
ideally should not be changed - it is used in any run kind of as the 
default config and is read without being specified by -c.

To create your own config, run `proovread --create-cfg my.cfg`, change 
my.cfg and than run `proovread -c my.cfg ...`

Let me know if using the original proovread.cfg + a customized my.cfg 
fixes your problem. And sorry about the inconvenience!

Cheers
Thomas

**Comment by thefantasticdron** [comment]
Hi Thomas,

Thanks for letting me know, I generated my own config file as you suggested and ran my tests using it. Unfortunately I encountered the same error. I have attached a copy of my output and my config file.

[my.cfg.txt](https://github.com/BioInf-Wuerzburg/proovread/files/317101/my.cfg.txt)
[proovread-out.txt](https://github.com/BioInf-Wuerzburg/proovread/files/317102/proovread-out.txt)

**Comment by thackl** [comment]
Did you restore the original config file?

**Comment by thefantasticdron** [comment]
Yes, I did.

**Comment by thackl** [comment]
weird. To possible fixes:

1) try using a full path to your config file `-c /full/path/to/config`
2) if 1) fails, try to avoid using a custom config and just supply 
everything on command line `-l long_reads.fq -s short_reads.fq -p prefix`

**Comment by thefantasticdron** [comment]
Providing the full path to the config file worked! Thank you so much!
