### ISSUE TITLE
Long read quality offset auto-detection failed

### ISSUE THREAD

**Issue by thefantasticdron** [BioInf-Wuerzburg/proovread#68]
Hello again,

This issue is not a matter of technical difficulties as much as it is a question of theory. When running several jobs using proovread, on some of my samples the program failed with an error message saying something similar to "long read quality offset auto-detection failed" and prompted me to input the "long read quality offset" manually. What is a "long read quality offset" and could you tell me how I could find this value?

Thanks in advance.

**Comment by thackl** [comment]
This goes to the phred-offset used to encode fastq qualities. It is 
either 33 or 64. proovread tries to automatically guess that value. It 
does so by finding values that either unambiguously fall in the 33 ro 
33+40 or 64 to 64+40 range. Unfortunately, there is a region of overlap 
between those ranges: 64-73. If all your quality values in a batch fall 
in this range, the auto-detection of the offset fails. This does not 
make to much sense for long reads, as quality values are not really 
used, but I just run them through the same import routine as the short 
reads, and for those the determination is useful. Hope that helps

Cheers
Thomas

**Comment by thefantasticdron** [comment]
Thank you!
