### ISSUE TITLE
Is proovread output guaranteed to be in the order given in the input FASTQ file?

### ISSUE THREAD

**Issue by thefantasticdron** [BioInf-Wuerzburg/proovread#70]
Hello,

Is proovread output guaranteed to be in the same order as the inputted fastq file? e.g. if I input a fastq file of reads 1, 2, 3 and 4, will proovread always output the corrected reads in order of 1, 2, 3 and 4?

Thank you,
Sean

**Comment by thackl** [comment]
Yes, but there are two things to keep in mind:
1. proovread will entirely ignore (and thus also remove from the unrimmed output) reads that are shorter than 2x the estimated short read length,  therefore it is possible to get an output of corrected reads in the right order but with missing IDs, like 1,2,4 for example.. The IDs of ignored reads are listed in .ignored.tsv. 
2. If reads have PacBio style headers and comprise reads from the same template, proovread will merge them into a single circular consensus sequence, for example

``` bash
@m120114_011938_42177_c100247042550000001523002504251220_s1_p0/10/891_4025
@m120114_011938_42177_c100247042550000001523002504251220_s1_p0/10/4069_7193
@m120114_011938_42177_c100247042550000001523002504251220_s1_p0/10/7237_10310
```
will become a single entry after the CCS module with the following header:

```
@m120114_011938_42177_c100247042550000001523002504251220_s1_p0/10/4069_7193 CCS:primary
```

Cheers
Thomas

**Comment by thefantasticdron** [comment]
Thank you!
