### ISSUE TITLE
how to correct list of many long reads files for Proovread?

### ISSUE THREAD

**Issue by wsuplantpathology** [BioInf-Wuerzburg/proovread#74]
Hello:

After I got ~100 .fq long reads files from `SeqChunker` step, I wonder how to add this list of files into the program? for example, we can use `-s 1.fq -s 2.fq -s 3.fq`  for many high quality short reads, how to deal with ~100 long reads .fq files.

In the proovread.cfg file, it says (line37-38):

> ## LIST of Pacbio read files to correct. FASTA or FASTQ format.
'long-reads' => [],

However, I cannot figure out how to use this option.  

I tried: 

> 'long-reads' => [pb-001.fq],[pb-002.fq]

> 'long-reads' => [pb-001.fq],
> 'long-reads' => [pb-002.fq],

> 'long-reads' => [*.fq],

ALL of them are FAILED. Any suggestions? Thanks

**Comment by thackl** [comment]
The correct syntax would be:
```
'long-reads' => ["pb-001.fq", "pb-002.fq"],
```
**However**, if you want to run all of your reads in one go, there is no need to split them in the first place. You can just run proovread on the unsplit file directly. The advantage of splitting is, that you can submit a proovread job for every chunk independently to a computing cluster. This allows you, in particular, to adjust runtimes to given queue limits, etc, or to do test runs on a subset of the data. If your data set is small, i.e. not a large eukaryotic genome, and you have a computer with +10 cores and +50 GB RAM, then you should be fine running all at once.

**Comment by wsuplantpathology** [comment]
Hi @thackl , Thanks so much for your response. It saves me a lot of time to testing different syntax.

My PacBio data is ~12G in .fq, the genome is around 120 Mb, I'll run Proovread in our computer cluster in which I am allowed to use 12 threads, 64 CPU and 504 G of memory.

So what's suggestion, e.g.: how many chunk? or I can run all my 12G data at once?

Again, your suggestion will save me a lot of testing time, so I am looking forward to getting your suggestions. Thanks so much.

**Comment by thackl** [comment]
That is a rather small genome. 12G sounds like you have multiple PacBio 
cells, I would run one instance of proovread per pacbio cell (or some 
500MB to 1G chunks). Max out the CPUs. Submit the job with 64 CPUs and 
set proovread --thread to 64. Make sure to set --coverage to the 
coverage of your Illumina data.

**Comment by wsuplantpathology** [comment]
Thanks so much. I'll try different chunks and test your suggestion. Thanks for such a nice program.
