### ISSUE TITLE
Proovread error

### ISSUE THREAD

**Issue by Trevaly** [BioInf-Wuerzburg/proovread#79]
Dear all,
I'm trying to run proovread with the following job array code (~1000 run in order to maximize the parallelization). However the job failed and I don't manage to identify why, the log is after the script. If you have an idea it would be fantastic ! 

Thanks Jeremie

----------------------Script-------------------------------------------------------
#!/bin/csh
#PBS -l mem=23000mb

source /usr/share/modules/init/csh
module load java

setenv PATH ${PATH}:/home12/caparmor/bioinfo/softs/sources/proovread/bin
setenv PATH ${PATH}:/home12/caparmor/bioinfo/softs/sources/proovread/util/SeqChunker/bin
setenv PERL5LIB /home12/caparmor/bioinfo/softs/perlmodules/lib/perl5/site_perl/5.10.0/:/home12/caparmor/bioinfo/softs/perlmodules:/home12/caparmor/bioinfo/softs/perlmodules/lib/perl5/5.10.0/x86_64-linux-thread-multi/
setenv PATH ${PATH}:/home12/caparmor/bioinfo/softs/sources/blast/ncbiblast+/2.2.29/bin/:/home12/caparmor/bioinfo/softs/sources/samtools/1.3.1/samtools/bin

setenv TMP /home/trash/Users/5_days_max/bioinfo
setenv TMPDIR /home/trash/Users/5_days_max/bioinfo

#going into result directory
cd /work/galaxy/p_margaritifera/genome/pacbio_manip/pacbio_corrected/

set read_dir=/work/galaxy/p_margaritifera/genome/illumina_40x_normalized
set data_dir=/work/galaxy/p_margaritifera/genome/pacbio_manip/40mb_chunk_fastq

proovread -l $data_dir/$PBS_ARRAY_INDEX.fastq -s $read_dir/PE_genome_40x_cat.fastq -p $PBS_ARRAY_INDEX >>& /work/galaxy/p_margaritifera/genome/pacbio_manip/log_files/$PBS_ARRAY_INDEX.log
-----------------------------------------------------------------------------------------------------

------------------------------------log--------------------------------------------------------------
[Fri Sep  9 18:03:01 2016] Running proovread-2.13.12 under Perl 5.10.0
[Fri Sep  9 18:03:01 2016] Reading core config
[Fri Sep  9 18:03:01 2016] Reading command line options
[Fri Sep  9 18:03:01 2016] Logging parameter to `98/98.parameter.log`
[Fri Sep  9 18:03:01 2016] Checking short read files
  
PE_genome_40x_cat.fastq
  Detected FASTQ format
  Estimated short read length: 123 +-4
#------------------------------------------------------------------------------#
  Estimating short read quality offset failed.
See 'sr-qv-offset' in the advanced section for manual overwrite
	Exited at 'main'
	'/home12/caparmor/bioinfo/softs/sources/proovread/bin/proovread', line 469

Nb if I well understood other responses about the quality offset this should not be the problem.

**Comment by thackl** [comment]
But I do think that the `sr-qv-offset` is the actual problem. Try running proovread with the additional parameter `--sr-qv-offset 33/64` specified.

**Comment by Trevaly** [comment]
Thank you for your rapid answer, your were right every things lloks fine now and is running.

Jeremie
