### ISSUE TITLE
Is it possible to split the splitted read even more 

### ISSUE THREAD

**Issue by MeHelmy** [BioInf-Wuerzburg/proovread#81]
as declared in the question I have read like this:
>S1_1542.1.1 SUBSTR:0,6282 SUBSTR:4966,1208
>S1_1542.1.2 SUBSTR:0,6282 SUBSTR:3165,711
>S1_1542.1.3 SUBSTR:0,6282 SUBSTR:3900,574

this means that read 1 was divided into three more split?

also I grep my file for S1_1542.2 but there was no result, why then we did not name the previous reads like 

S1_1542.1
S1_1542.2
S1_1542.3

**Comment by thackl** [comment]
There is more than 1 step in proovread that potentially leads to cutting reads into smaller pieces, such as  chimera/siamera trimming and quality trimming. Having something like S1_1542.1.1 and
S1_1542.1.2 and no read S1_1542.2 usually means, that the read initially was split into at least 2 parts (S1_1542.1 and S1_1542.2) but that later only one of those parts was kept. For example if S1_1542.2 would be very short or entirely of low quality, it would be removed during quality trimming, while S1_1542.1 was split further into 3 high quality parts (S1_1542.1.1,S1_1542.1.2,S1_1542.1.3).

**Comment by MeHelmy** [comment]
Thanks a lot

**Comment by MeHelmy** [comment]
Sorry; but I have another question

I have reads like

>S1_2546.1 SUBSTR:2079,1912 SUBSTR:21 SIAMAERA:21,1912

>S1_1356.2.1 HPL:5 SUBSTR:4079 SUBSTR:772,561

in case of  SUBSTR:21 it means he will cut the sub-sequence(splitted read) from position 21 ?

and what is HPL:5 (you mentioned chimera and siamera )
