### ISSUE TITLE
get error when run the sample data [proovread --sample --pre pr-sample]

### ISSUE THREAD

**Issue by yplee614** [BioInf-Wuerzburg/proovread#82]
proovread --sample --pre pr-sample

[Sun Oct  9 15:58:44 2016] Reading core config
[Sun Oct  9 15:58:44 2016] Reading command line options
[Sun Oct  9 15:58:44 2016] Logging parameter to `pr-sample/pr-sample.parameter.l
og`
[Sun Oct  9 15:58:44 2016] Checking short read files

F.antasticus_short.fq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Estimating approximate number of short reads: 50.0k

[Sun Oct  9 15:58:44 2016] Checking required binaries

  [ok] samtools-1.2    /home/yplee/bin
  [ok] bwa-proovread   /home/yplee/software/proovread-2.12/bin/../util/bwa
  [ok] blastn-2.2.31   /home/yplee/software/ncbi-blast-2.2.31+/bin

[Sun Oct  9 15:58:44 2016] Running mode: sr
[Sun Oct  9 15:58:44 2016] Preparing long reads
# ------------------------------------------------------------------------------

perl -I/home/yplee/software/proovread-2.12/bin/../lib/ /home/yplee/software/pro\
ovread-2.12/bin/SeqFilter --fasta --in pr-sample/read-long/pr-sample.fq --line-\
width 80 --lower-case --out pr-sample/read-long/pr-sample.masked.fa --phred-off\
set 33
[15:58:44] /home/yplee/software/proovread-2.12/bin/SeqFilter-1.06
[15:58:44] --in: pr-sample/read-long/pr-sample.fq
[15:58:44] Detected FASTQ format, phred-offset 33
  257k [=========================================================>] TTS 00:00:00
# ------------------------------------------------------------------------------

[15:58:44] Input
[15:58:44] Sequences              121 #
[15:58:44] Total               126422 bp
[15:58:44] Longest               1074 bp
[15:58:44] Shortest              1012 bp
[15:58:44] N50                   1045 bp
[15:58:44] N90                   1032 bp
# ------------------------------------------------------------------------------

[15:58:44] Filtered
[15:58:44] Sequences              121 #
[15:58:44] Total               126422 bp
[15:58:44] Longest               1074 bp
[15:58:44] Shortest              1012 bp
[15:58:44] N50                   1045 bp
[15:58:44] N90                   1032 bp
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------

[Sun Oct  9 15:58:44 2016] Read IDs don't look like proper PacBio subread IDs.
Falling back to running mode: sr-noccs

[Sun Oct  9 15:58:44 2016] Running task bwa-sr-1
[Sun Oct  9 15:58:44 2016] Indexing Long reads
# ------------------------------------------------------------------------------

/home/yplee/software/proovread-2.12/bin/../util/bwa/bwa-proovread index pr-samp\
le/read-long/pr-sample.masked.fa pr-sample/read-long/pr-sample.masked.fa 2>pr-s\
ample/bwa-sr-1/pr-sample_bwa.log
# ------------------------------------------------------------------------------

[Sun Oct  9 15:58:44 2016] Mapping reads `/home/yplee/software/proovread-2.12/bi
n/../sample/F.antasticus_short.fq`
# ------------------------------------------------------------------------------

/home/yplee/software/proovread-2.12/bin/SeqChunker --chunk-number 1000 --chunk-\
step 20 --chunks-per-step 6 --first-chunk 1 /home/yplee/software/proovread-2.12\
/bin/../sample/F.antasticus_short.fq | /home/yplee/software/proovread-2.12/bin/\
../util/bwa/bwa-proovread mem -b 20 -l 300 -E 4,3 -k 12 -B 11 -r 1.5 -A 5 -O 2,\
1 -Y  -y 20 -T 3 -w 40 -a  -W 20 -t 4 -L 30,30 -D .75 pr-sample/read-long/pr-sa\
mple.masked.fa /dev/fd/0 2>pr-sample/bwa-sr-1/pr-sample_bwa.log | samtools view\
 -@ 4 -bS /dev/fd/0 >pr-sample/bwa-sr-1/pr-sample_tmp.bam
# ------------------------------------------------------------------------------

Reading /home/yplee/software/proovread-2.12/bin/../sample/F.antasticus_short.fq

[Sun Oct  9 15:58:46 2016] Sorting BAM `pr-sample/bwa-sr-1/pr-sample.bam`
# ------------------------------------------------------------------------------

samtools sort -m 2G -@ 3 pr-sample/bwa-sr-1/pr-sample_tmp.bam pr-sample/bwa-sr-\
1/pr-sample
# ------------------------------------------------------------------------------

[Sun Oct  9 15:58:46 2016] Indexing BAM `pr-sample/bwa-sr-1/pr-sample`
# ------------------------------------------------------------------------------

samtools index pr-sample/bwa-sr-1/pr-sample.bam
# ------------------------------------------------------------------------------

[Sun Oct  9 15:58:46 2016] Correcting Sequences (2 batches)
# ------------------------------------------------------------------------------

[Sun Oct  9 15:58:46 2016] Batch 1/2
perl -I/home/yplee/software/proovread-2.12/bin/../lib/ /home/yplee/software/pro\
ovread-2.12/bin/bam2cns --append 1 --bam pr-sample/bwa-sr-1/pr-sample.bam --bin\
-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --max-ins-l\
ength 0 --max-ref-seqs 100 --prefix pr-sample/bwa-sr-1/pr-sample.0 --qv-offset \
33 --ref pr-sample/read-long/pr-sample.fq --ref-offset 0
# ------------------------------------------------------------------------------

[Sun Oct  9 15:58:46 2016] Batch 2/2
perl -I/home/yplee/software/proovread-2.12/bin/../lib/ /home/yplee/software/pro\
ovread-2.12/bin/bam2cns --append 1 --bam pr-sample/bwa-sr-1/pr-sample.bam --bin\
-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --max-ins-l\
ength 0 --max-ref-seqs 100 --prefix pr-sample/bwa-sr-1/pr-sample.1 --qv-offset \
33 --ref pr-sample/read-long/pr-sample.fq --ref-offset 212403
# ------------------------------------------------------------------------------

perl: warning: Setting locale failed.
# ------------------------------------------------------------------------------

[Sun Oct  9 15:58:46 2016] bam2cns unexpectedly returned
    Exited at 'main'
    '/home/yplee/software/proovread-2.12/bin/proovread', line 1578
    Last call 'main::correct_sr_mt'
    '/home/yplee/software/proovread-2.12/bin/proovread', line 842

**Comment by thackl** [comment]
There seems to be an issue with the `locale` settings on your machine (something along those lines: http://stackoverflow.com/questions/2499794/how-can-i-fix-a-locale-warning-from-perl). But to be honest, I don't really know where that is coming from. Can you rerun the failed command directly (from the same location you ran the sample):
```
perl -I/home/yplee/software/proovread-2.12/bin/../lib/ /home/yplee/software/pro\
ovread-2.12/bin/bam2cns --append 1 --bam pr-sample/bwa-sr-1/pr-sample.bam --bin\
-size 20 --coverage 11.25 --ignore-weak-reads 0 --mask-weak-reads 0 --max-ins-l\
ength 0 --max-ref-seqs 100 --prefix pr-sample/bwa-sr-1/pr-sample.0 --qv-offset \
33 --ref pr-sample/read-long/pr-sample.fq --ref-offset 0
```

That might give some more information about the error.

**Comment by zhoujiebioinf** [comment]
I've met the same question and rerun the failed command directly, the command works without an exit. But the [proovread --sample --pre pr-sample] exits.
Then I tested the advice from the link thackl listed (Add “export LC_ALL=en_US.UTF-8” to my bashrc file on the host machine), it's solved now.

**Comment by thackl** [comment]
Cool, thanks a lot for posting this!
