### ISSUE TITLE
masking percentage less than 50

### ISSUE THREAD

**Issue by MeHelmy** [BioInf-Wuerzburg/proovread#84]
Hi,
I was trying to tune options to correct my data (Yeast) so;
I simulate one chromosome and used [ArtificialFastqGenerator.jar](https://sourceforge.net/projects/artfastqgen/) to create artificial short read with length 100 and coverage 50 resulting in foreword and revers fastq file
and 
[pbsim](http://bioinformatics.oxfordjournals.org/content/29/1/119.full) to create PacBio reads CLR with depth 20

then I used proovread as follow:

`./proovread/bin/proovread -l yeast_pacbio.fastq -s yeast.1.fastq -s yeast.2.fastq -t 10 -p yeast --sr-qv-offset 33 > out.log 2>&1`

and as the documentation said I run 

`grep -P 'Running mode|ked :|ning task' out.log`

But the result was 
[Fri Oct 14 14:44:01 2016] Running mode: sr
[Fri Oct 14 14:44:03 2016] Running task bwa-sr-1
[Fri Oct 14 14:47:12 2016] Masked : 9.5%
[Fri Oct 14 14:47:12 2016] Running task bwa-sr-2
[Fri Oct 14 14:50:20 2016] Masked : 20.1%
[Fri Oct 14 14:50:20 2016] Running task bwa-sr-3
[Fri Oct 14 14:53:24 2016] Masked : 31.2%
[Fri Oct 14 14:53:24 2016] Running task bwa-sr-4
[Fri Oct 14 14:56:03 2016] Masked : 47.1%
[Fri Oct 14 14:56:03 2016] Running task bwa-sr-5
[Fri Oct 14 14:58:29 2016] Masked : 60.9%
[Fri Oct 14 14:58:29 2016] Running task bwa-sr-6
[Fri Oct 14 15:00:48 2016] Masked : 74.2%
[Fri Oct 14 15:00:49 2016] Running task bwa-sr-finish
[Fri Oct 14 15:05:17 2016] Masked : 42.2%

which do not fit to what is suggested by documentation 
is there any mistake in command or how can I enhance it?

Thanks,

**Comment by thackl** [comment]
Yep, there are two problems:

1. In particular for small genomes, there is the issue that you need to split your long reads in chunks so small, that there is less than 1X genome coverage per pacbio chunk. The reason is that you don't want to have multiple pacbio reads from the same location in one chunk, or else they do compete for short read alignments, i.e. the read / part of the read with already the least errors will get all the best short read mappings, while other reads / parts of other reads from the same location get none. No mappings == no correction
2. pbsim has a rather poor model for pacbio errors, mostly because it is based on data from very old pacbio chemistry. These are the settings that I use for more realistic reads:

```
pbsim 
 --length-max 50000 --length-min 1000 --length-mean 7000 --difference-ratio 8:62:30 \
 --data-type CLR --accuracy-mean 0.83 --model_qc /path/to/pbsim/data/model_qc_clr \
 --depth ...
```
Let me know if that helps.

**Comment by MeHelmy** [comment]
so in case of the chromosome size is 1,531,933
 and coverage is 20 I need in each chunk 1531933/20

**Comment by thackl** [comment]
Exactly. The following command for example would create good chunks (2MB chunks =~ 1Mbp)
```
SeqChunker -s 2M -o pb-%03d.fq pb-reads.fq
```

**Comment by MeHelmy** [comment]
after creating chunks as suggested in your answer 

I run the command 

`./proovread/bin/proovread -l pb-001.fq -s yeast.1.fastq -s yeast.2.fastq -t 10 -p yeast_001 --sr-qv-offset 33 > out_001.log 2>&1`

Then when  use the command

grep -P 'Running mode|ked :|ning task' out_001.log                                                                              
[Sat Oct 15 09:51:16 2016] Running mode: sr
[Sat Oct 15 09:51:16 2016] Running task bwa-sr-1

in the log file there is error 

```
bam2cns unexpectedly returned
        Exited at 'main'
        './proovread/bin/proovread', line 1634
        Last call 'main::correct_sr_mt'
        './proovread/bin/proovread', line 868
```

**Comment by MeHelmy** [comment]
after creating chunks as suggested in your answer

I run the command

./proovread/bin/proovread -l pb-001.fq -s yeast.1.fastq -s yeast.2.fastq -t 10 -p yeast_001 --sr-qv-offset 33 > out_001.log 2>&1

Then when use the command

grep -P 'Running mode|ked :|ning task' out_001.log

[Sat Oct 15 10:06:30 2016] Running mode: sr
[Sat Oct 15 10:06:30 2016] Running task bwa-sr-1
[Sat Oct 15 10:06:44 2016] Masked : 17.1%
[Sat Oct 15 10:06:44 2016] Running task bwa-sr-2
[Sat Oct 15 10:06:57 2016] Masked : 33.7%
[Sat Oct 15 10:06:58 2016] Running task bwa-sr-3
[Sat Oct 15 10:07:09 2016] Masked : 50.5%
[Sat Oct 15 10:07:09 2016] Running task bwa-sr-4
[Sat Oct 15 10:07:19 2016] Masked : 69.6%
[Sat Oct 15 10:07:19 2016] Running task bwa-sr-5
[Sat Oct 15 10:07:28 2016] Masked : 79.7%
[Sat Oct 15 10:07:28 2016] Running task bwa-sr-6
[Sat Oct 15 10:07:35 2016] Masked : 87.9%
[Sat Oct 15 10:07:35 2016] Running task bwa-sr-finish
[Sat Oct 15 10:07:54 2016] Masked : 54.5%


still did not meet the recommended by documentation!
do I need more chunks?

**Comment by thackl** [comment]
Possible, but I don't think so. Did you use the modified pbsim settings? It is weird that your need that many iterations in the first place. And did you check the how much data you actually get in the .trimmed.fq? That can be more than the %masked in the last iteration.

**Comment by MeHelmy** [comment]
I am still working with the default pbsim settings to see how it will behave with old data,  regarding how many data I begin with 345 sequence in the uncorrected PacBio file ended with 332 in the trimmed file "some of them are splitted as you know read_1.1 read_1.2 as you know"
