### ISSUE TITLE
No sequences found matching given filter criteria

### ISSUE THREAD

**Issue by wangxinbio** [BioInf-Wuerzburg/proovread#86]
Hi
When I used prooread for my personal data, it showed a error like this:
 No sequences found matching given filter criteria
Use of uninitialized value $c in ord at /data/correct/proovread/proovread/bin/../lib//Fastq/Parser.pm line 355.
Use of uninitialized value $c in string eq at /data/correct/proovread/proovread/bin/../lib//Fastq/Parser.pm line 359.

But when I used for sample data "proovread --sample --pre pr-sample", it runned well and I got the .trimmed.f[aq] &&  .untrimmed.fq files. Could you help me to solve this problem ?

**Comment by thackl** [comment]
Can you send the complete log of the failed run?

**Comment by wangxinbio** [comment]
When I use another illumina data (read length 150bp), It is Ok. Whether the error is related with short read length ? The short read length is only 48bp.

**Comment by wangxinbio** [comment]
When I use another illumina data (read length 150bp), It is Ok. Whether the error is related with short read length ? The short read length is only 48bp.
[log.txt](https://github.com/BioInf-Wuerzburg/proovread/files/561866/log.txt)

**Comment by thackl** [comment]
Yes, that is the problem. proovread cannot get mappings from reads that short. You should have at least 75bp, better 100bp or more. Sorry...

**Comment by wangxinbio** [comment]
Ok. Thank you very much. I will abandon the read that length shorter than 75 bp.
