### ISSUE TITLE
Proovread error on sample data

### ISSUE THREAD

**Issue by laure182** [BioInf-Wuerzburg/proovread#89]
Hi,
Could you help me for the error below ?
Thank you very much.
Laure

proovread --sample-run
[Tue Nov 29 14:50:06 2016] Running proovread-2.13.13 under Perl 5.22.0
[Tue Nov 29 14:50:06 2016] Reading core config
[Tue Nov 29 14:50:06 2016] Reading command line options
[Tue Nov 29 14:50:06 2016] Logging parameter to `pr-Fa/pr-Fa.parameter.log`
[Tue Nov 29 14:50:06 2016] Checking short read files
  
F.antasticus_short.fq
  Detected FASTQ format
  Estimated short read length: 100 +-0
  Estimating approximate number of short reads: 50.0k

[Tue Nov 29 14:50:06 2016] Checking required binaries

  [ok] samtools-1.3.1  /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/b\
in
  [ok] bwa-proovread   /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/p\
roovread/bin/../util/bwa
  [ok] blastn-2.5.0    /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/b\
in

[Tue Nov 29 14:50:06 2016] Running mode: sr
[Tue Nov 29 14:50:06 2016] Preparing long reads
#------------------------------------------------------------------------------#
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqFi\
lter --fasta --in pr-Fa/read-long/pr-Fa.fq --line-width 80 --lower-case --out p\
r-Fa/read-long/pr-Fa.masked.fa --phred-offset 33
[14:50:06] /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/
SeqFilter-1.06
[14:50:06] --in: pr-Fa/read-long/pr-Fa.fq
[14:50:06] Detected FASTQ format, phred-offset 33
  257k [=========================================================>] TTS 00:00:00
#------------------------------------------------------------------------------#
[14:50:06] Input
[14:50:06] Sequences              121 #
[14:50:06] Total               126422 bp
[14:50:06] Longest               1074 bp
[14:50:06] Shortest              1012 bp
[14:50:06] N50                   1045 bp
[14:50:06] N90                   1032 bp
#------------------------------------------------------------------------------#
[14:50:06] Filtered
[14:50:06] Sequences              121 #
[14:50:06] Total               126422 bp
[14:50:06] Longest               1074 bp
[14:50:06] Shortest              1012 bp
[14:50:06] N50                   1045 bp
[14:50:06] N90                   1032 bp
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:06 2016] Read IDs don't look like proper PacBio subread IDs.
Falling back to running mode: sr-noccs

[Tue Nov 29 14:50:06 2016] Running task bwa-sr-1
[Tue Nov 29 14:50:06 2016] Indexing Long reads
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/bw\
a/bwa-proovread index pr-Fa/read-long/pr-Fa.masked.fa pr-Fa/read-long/pr-Fa.mas\
ked.fa 2>pr-Fa/bwa-sr-1/pr-Fa_bwa.log
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:06 2016] Mapping reads `/home12/caparmor/bioinfo/tools/anacond
a/envs/proovread/proovread/bin/../sample/F.antasticus_short.fq`
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqChunker\
 --chunk-number 1000 --chunk-step 20 --chunks-per-step 6 --first-chunk 1 /home1\
2/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../sample/F.anta\
sticus_short.fq | /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovr\
ead/bin/../util/bwa/bwa-proovread mem -b 20 -l 300 -r 1 -A 5 -D 0 -k 12 -Y  -E \
4,3 -t 4 -L 30,30 -W 20 -y 20 -w 40 -a  -T 2.5 -B 11 -O 2,1 pr-Fa/read-long/pr-\
Fa.masked.fa /dev/fd/0 2>pr-Fa/bwa-sr-1/pr-Fa_bwa.log | samtools view -@ 4 -bS \
/dev/fd/0 >pr-Fa/bwa-sr-1/pr-Fa_tmp.bam
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/SeqChunker/bin/SeqChunker
FILE should be located at '/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/SeqChunker/bin/SeqChunker'
Reading /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../sample/F.antasticus_short.fq

[Tue Nov 29 14:50:07 2016] Sorting BAM `pr-Fa/bwa-sr-1/pr-Fa.bam`
#------------------------------------------------------------------------------#
samtools sort -m 2G -@ 3 -T pr-Fa/bwa-sr-1/pr-Fa_tmp -o pr-Fa/bwa-sr-1/pr-Fa.ba\
m pr-Fa/bwa-sr-1/pr-Fa_tmp.bam
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:07 2016] Indexing BAM `pr-Fa/bwa-sr-1/pr-Fa`
#------------------------------------------------------------------------------#
samtools index pr-Fa/bwa-sr-1/pr-Fa.bam
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:07 2016] Correcting Sequences (2 batches)
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:07 2016] Batch 1/2
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/bam2c\
ns --append 1 --bam pr-Fa/bwa-sr-1/pr-Fa.bam --bin-size 20 --coverage 11.25 --i\
gnore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --\
prefix pr-Fa/bwa-sr-1/pr-Fa.0 --qv-offset 33 --ref pr-Fa/read-long/pr-Fa.fq --r\
ef-offset 0 
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:07 2016] Batch 2/2
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/bam2c\
ns --append 1 --bam pr-Fa/bwa-sr-1/pr-Fa.bam --bin-size 20 --coverage 11.25 --i\
gnore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --\
prefix pr-Fa/bwa-sr-1/pr-Fa.1 --qv-offset 33 --ref pr-Fa/read-long/pr-Fa.fq --r\
ef-offset 212420 
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:12 2016] Merging corrected output
#------------------------------------------------------------------------------#
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqFi\
lter pr-Fa/bwa-sr-1/pr-Fa.fq --line-width 80 --quiet --out pr-Fa/bwa-sr-1/pr-Fa\
.masked.fa --phred-offset 33 --phred-mask 20,41,80,130,60,0.7 --fasta --base-co\
ntent N --tsv -
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:13 2016] Masked : 60.9%
[Tue Nov 29 14:50:13 2016] Masked < 92% total / > 3% new - continuing

[Tue Nov 29 14:50:13 2016] Running task bwa-sr-2
[Tue Nov 29 14:50:13 2016] Indexing Long reads
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/bw\
a/bwa-proovread index pr-Fa/bwa-sr-1/pr-Fa.masked.fa pr-Fa/bwa-sr-1/pr-Fa.maske\
d.fa 2>pr-Fa/bwa-sr-2/pr-Fa_bwa.log
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:13 2016] Mapping reads `/home12/caparmor/bioinfo/tools/anacond
a/envs/proovread/proovread/bin/../sample/F.antasticus_short.fq`
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqChunker\
 --chunk-number 1000 --chunk-step 20 --chunks-per-step 6 --first-chunk 7 /home1\
2/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../sample/F.anta\
sticus_short.fq | /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovr\
ead/bin/../util/bwa/bwa-proovread mem -b 20 -l 300 -y 20 -w 40 -a  -T 2.5 -B 11\
 -O 2,1 -r 1 -D 0 -A 5 -k 12 -Y  -t 4 -E 4,3 -W 20 -L 30,30 pr-Fa/bwa-sr-1/pr-F\
a.masked.fa /dev/fd/0 2>pr-Fa/bwa-sr-2/pr-Fa_bwa.log | samtools view -@ 4 -bS /\
dev/fd/0 >pr-Fa/bwa-sr-2/pr-Fa_tmp.bam
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/SeqChunker/bin/SeqChunker
FILE should be located at '/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/SeqChunker/bin/SeqChunker'
Reading /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../sample/F.antasticus_short.fq

[Tue Nov 29 14:50:13 2016] Sorting BAM `pr-Fa/bwa-sr-2/pr-Fa.bam`
#------------------------------------------------------------------------------#
samtools sort -m 2G -@ 3 -T pr-Fa/bwa-sr-2/pr-Fa_tmp -o pr-Fa/bwa-sr-2/pr-Fa.ba\
m pr-Fa/bwa-sr-2/pr-Fa_tmp.bam
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:13 2016] Indexing BAM `pr-Fa/bwa-sr-2/pr-Fa`
#------------------------------------------------------------------------------#
samtools index pr-Fa/bwa-sr-2/pr-Fa.bam
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:13 2016] Correcting Sequences (2 batches)
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:13 2016] Batch 1/2
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/bam2c\
ns --append 1 --bam pr-Fa/bwa-sr-2/pr-Fa.bam --bin-size 20 --coverage 11.25 --i\
gnore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --\
prefix pr-Fa/bwa-sr-2/pr-Fa.0 --qv-offset 33 --ref pr-Fa/bwa-sr-1/pr-Fa.fq --re\
f-offset 0 
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:13 2016] Batch 2/2
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/bam2c\
ns --append 1 --bam pr-Fa/bwa-sr-2/pr-Fa.bam --bin-size 20 --coverage 11.25 --i\
gnore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --\
prefix pr-Fa/bwa-sr-2/pr-Fa.1 --qv-offset 33 --ref pr-Fa/bwa-sr-1/pr-Fa.fq --re\
f-offset 202529 
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:17 2016] Merging corrected output
#------------------------------------------------------------------------------#
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqFi\
lter pr-Fa/bwa-sr-2/pr-Fa.fq --line-width 80 --quiet --out pr-Fa/bwa-sr-2/pr-Fa\
.masked.fa --phred-offset 33 --phred-mask 20,41,80,130,60,0.7 --fasta --base-co\
ntent N --tsv -
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:18 2016] Masked : 73.4%
[Tue Nov 29 14:50:18 2016] Masked < 92% total / > 3% new - continuing

[Tue Nov 29 14:50:18 2016] Running task bwa-sr-3
[Tue Nov 29 14:50:18 2016] Indexing Long reads
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/bw\
a/bwa-proovread index pr-Fa/bwa-sr-2/pr-Fa.masked.fa pr-Fa/bwa-sr-2/pr-Fa.maske\
d.fa 2>pr-Fa/bwa-sr-3/pr-Fa_bwa.log
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:18 2016] Mapping reads `/home12/caparmor/bioinfo/tools/anacond
a/envs/proovread/proovread/bin/../sample/F.antasticus_short.fq`
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqChunker\
 --chunk-number 1000 --chunk-step 20 --chunks-per-step 6 --first-chunk 13 /home\
12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../sample/F.ant\
asticus_short.fq | /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proov\
read/bin/../util/bwa/bwa-proovread mem -b 20 -l 300 -k 12 -D 0 -A 5 -r 1 -E 4,3\
 -t 4 -W 20 -L 30,30 -Y  -T 2.5 -B 11 -w 40 -a  -y 20 -O 2,1 pr-Fa/bwa-sr-2/pr-\
Fa.masked.fa /dev/fd/0 2>pr-Fa/bwa-sr-3/pr-Fa_bwa.log | samtools view -@ 4 -bS \
/dev/fd/0 >pr-Fa/bwa-sr-3/pr-Fa_tmp.bam
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/SeqChunker/bin/SeqChunker
FILE should be located at '/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/SeqChunker/bin/SeqChunker'
Reading /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../sample/F.antasticus_short.fq

[Tue Nov 29 14:50:18 2016] Sorting BAM `pr-Fa/bwa-sr-3/pr-Fa.bam`
#------------------------------------------------------------------------------#
samtools sort -m 2G -@ 3 -T pr-Fa/bwa-sr-3/pr-Fa_tmp -o pr-Fa/bwa-sr-3/pr-Fa.ba\
m pr-Fa/bwa-sr-3/pr-Fa_tmp.bam
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:18 2016] Indexing BAM `pr-Fa/bwa-sr-3/pr-Fa`
#------------------------------------------------------------------------------#
samtools index pr-Fa/bwa-sr-3/pr-Fa.bam
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:18 2016] Correcting Sequences (2 batches)
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:18 2016] Batch 1/2
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/bam2c\
ns --append 1 --bam pr-Fa/bwa-sr-3/pr-Fa.bam --bin-size 20 --coverage 11.25 --i\
gnore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --\
prefix pr-Fa/bwa-sr-3/pr-Fa.0 --qv-offset 33 --ref pr-Fa/bwa-sr-2/pr-Fa.fq --re\
f-offset 0 
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:18 2016] Batch 2/2
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/bam2c\
ns --append 1 --bam pr-Fa/bwa-sr-3/pr-Fa.bam --bin-size 20 --coverage 11.25 --i\
gnore-weak-reads 0 --mask-weak-reads 0 --max-ins-length 0 --max-ref-seqs 100 --\
prefix pr-Fa/bwa-sr-3/pr-Fa.1 --qv-offset 33 --ref pr-Fa/bwa-sr-2/pr-Fa.fq --re\
f-offset 202441 
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:22 2016] Merging corrected output
#------------------------------------------------------------------------------#
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqFi\
lter pr-Fa/bwa-sr-3/pr-Fa.fq --line-width 80 --quiet --out pr-Fa/bwa-sr-3/pr-Fa\
.masked.fa --phred-offset 33 --phred-mask 20,41,80,130,60,0.7 --fasta --base-co\
ntent N --tsv -
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:22 2016] Masked : 73.4%
[Tue Nov 29 14:50:22 2016] Masked < 3% new - skipping all but last iteration

#------------------------------------------------------------------------------#
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqFi\
lter --fasta --in pr-Fa/bwa-sr-3/pr-Fa.fq --out pr-Fa/bwa-sr-3/pr-Fa.unmasked.f\
a --phred-offset 33 --quiet
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:22 2016] Running task bwa-sr-finish
[Tue Nov 29 14:50:22 2016] Indexing Long reads
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/bw\
a/bwa-proovread index pr-Fa/bwa-sr-3/pr-Fa.unmasked.fa pr-Fa/bwa-sr-3/pr-Fa.unm\
asked.fa 2>pr-Fa/bwa-sr-finish/pr-Fa_bwa.log
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:22 2016] Mapping reads `/home12/caparmor/bioinfo/tools/anacond
a/envs/proovread/proovread/bin/../sample/F.antasticus_short.fq`
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqChunker\
 --chunk-number 1000 --chunk-step 20 --chunks-per-step 12 --first-chunk 19 /hom\
e12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../sample/F.an\
tasticus_short.fq | /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proo\
vread/bin/../util/bwa/bwa-proovread mem -b 20 -l 600 -Y  -E 3,3 -t 4 -W 18 -L 3\
0,30 -r 1.5 -D .75 -A 5 -k 17 -O 15,19 -a  -w 30 -T 4 -B 13 pr-Fa/bwa-sr-3/pr-F\
a.unmasked.fa /dev/fd/0 2>pr-Fa/bwa-sr-finish/pr-Fa_bwa.log | samtools view -@ \
4 -bS /dev/fd/0 >pr-Fa/bwa-sr-finish/pr-Fa_tmp.bam
#------------------------------------------------------------------------------#
/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/SeqChunker/bin/SeqChunker
FILE should be located at '/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/SeqChunker/bin/SeqChunker'
Reading /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../sample/F.antasticus_short.fq

[Tue Nov 29 14:50:23 2016] Sorting BAM `pr-Fa/bwa-sr-finish/pr-Fa.bam`
#------------------------------------------------------------------------------#
samtools sort -m 2G -@ 3 -T pr-Fa/bwa-sr-finish/pr-Fa_tmp -o pr-Fa/bwa-sr-finis\
h/pr-Fa.bam pr-Fa/bwa-sr-finish/pr-Fa_tmp.bam
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:23 2016] Indexing BAM `pr-Fa/bwa-sr-finish/pr-Fa`
#------------------------------------------------------------------------------#
samtools index pr-Fa/bwa-sr-finish/pr-Fa.bam
#------------------------------------------------------------------------------#

[Tue Nov 29 14:50:23 2016] Correcting Sequences (2 batches)
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:23 2016] Batch 1/2
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/bam2c\
ns --append 1 --bam pr-Fa/bwa-sr-finish/pr-Fa.bam --bin-size 20 --coverage 22.5\
 --detect-chimera --ignore-hcr --ignore-weak-reads 0 --mask-weak-reads 0 --max-\
ins-length 0 --max-ref-seqs 100 --no-use-ref-qual --prefix pr-Fa/bwa-sr-finish/\
pr-Fa.0 --qv-offset 33 --ref pr-Fa/bwa-sr-3/pr-Fa.fq --ref-offset 0 
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:23 2016] Batch 2/2
perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/bam2c\
ns --append 1 --bam pr-Fa/bwa-sr-finish/pr-Fa.bam --bin-size 20 --coverage 22.5\
 --detect-chimera --ignore-hcr --ignore-weak-reads 0 --mask-weak-reads 0 --max-\
ins-length 0 --max-ref-seqs 100 --no-use-ref-qual --prefix pr-Fa/bwa-sr-finish/\
pr-Fa.1 --qv-offset 33 --ref pr-Fa/bwa-sr-3/pr-Fa.fq --ref-offset 202503 
#------------------------------------------------------------------------------#
Warning: The index file is older than the data file: pr-Fa/bwa-sr-finish/pr-Fa.\
bam.bai
#------------------------------------------------------------------------------#
[Tue Nov 29 14:50:23 2016] bam2cns unexpectedly returned
	Exited at 'main'
	'/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/bin/proovread', line 16
34
	Last call 'main::correct_sr_mt'
	'/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/bin/proovread', line 868

**Comment by thackl** [comment]
I hope so, very weird error, though. The problem is related to the following two files:

``` sh
pr-Fa/bwa-sr-finish/pr-Fa.bam  # data file
pr-Fa/bwa-sr-finish/pr-Fa.bam.bai  # index file
```

By design, the .bam file is created first, and than indexed in a second step. So the error `The index file is older than the data file: pr-Fa/bwa-sr-finish/pr-Fa.bam.bai` does not make sense.

1) Could you have a look at the timestamps of those two files?
2) Could you run `samtools view -H pr-Fa/bwa-sr-finish/pr-Fa.bam` and see if you get the same error?

**Comment by laure182** [comment]
1. Weird timestamps !
```
2016-11-29 15:36:14.000000000 +0000 pr-Fa.bam
2016-11-29 15:32:11.000000000 +0000 pr-Fa.bam.bai
```
2. `samtools view -H pr-Fa/bwa-sr-finish/pr-Fa.bam` returns 

@HD	VN:1.3	SO:coordinate
@SQ	SN:long_contamination_0	LN:1052
@SQ	SN:long_error_0_0	LN:999
@SQ	SN:long_error_1_0	LN:1002
@SQ	SN:long_error_2_0	LN:1000
@SQ	SN:long_error_3_0	LN:1000
@SQ	SN:long_error_4_0	LN:997
@SQ	SN:long_error_5_0	LN:1001
@SQ	SN:long_error_6_0	LN:1000
@SQ	SN:long_error_7_0	LN:1000
@SQ	SN:long_error_8_0	LN:998
@SQ	SN:long_error_9_0	LN:1007
@SQ	SN:long_error_10_0	LN:1000
@SQ	SN:long_error_11_0	LN:1002
@SQ	SN:long_error_12_0	LN:1001
@SQ	SN:long_error_13_0	LN:1000
@SQ	SN:long_error_14_0	LN:1001
@SQ	SN:long_error_15_0	LN:1001
@SQ	SN:long_error_16_0	LN:1000
@SQ	SN:long_error_17_0	LN:1000
@SQ	SN:long_error_18_0	LN:1008
@SQ	SN:long_error_19_0	LN:996
@SQ	SN:long_error_20_0	LN:1006
@SQ	SN:long_error_21_0	LN:1004
@SQ	SN:long_error_22_0	LN:1000
@SQ	SN:long_error_23_0	LN:1001
@SQ	SN:long_error_24_0	LN:1000
@SQ	SN:long_error_25_0	LN:1002
@SQ	SN:long_error_26_0	LN:1003
@SQ	SN:long_error_27_0	LN:1001
@SQ	SN:long_error_28_0	LN:1004
@SQ	SN:long_error_29_0	LN:1001
@SQ	SN:long_error_30_0	LN:1002
@SQ	SN:long_error_31_0	LN:1002
@SQ	SN:long_error_32_0	LN:1000
@SQ	SN:long_error_33_0	LN:1002
@SQ	SN:long_error_34_0	LN:1001
@SQ	SN:long_error_35_0	LN:1000
@SQ	SN:long_error_36_0	LN:1000
@SQ	SN:long_error_37_0	LN:1003
@SQ	SN:long_error_38_0	LN:1006
@SQ	SN:long_error_39_0	LN:1000
@SQ	SN:long_error_40_0	LN:1000
@SQ	SN:long_error_41_0	LN:1000
@SQ	SN:long_error_42_0	LN:1001
@SQ	SN:long_error_43_0	LN:1013
@SQ	SN:long_error_44_0	LN:1002
@SQ	SN:long_error_45_0	LN:1005
@SQ	SN:long_error_46_0	LN:1005
@SQ	SN:long_error_47_0	LN:1001
@SQ	SN:long_error_48_0	LN:999
@SQ	SN:long_error_49_0	LN:1002
@SQ	SN:long_error_50_0	LN:1000
@SQ	SN:long_error_51_0	LN:1000
@SQ	SN:long_error_52_0	LN:1000
@SQ	SN:long_error_53_0	LN:1001
@SQ	SN:long_error_54_0	LN:1000
@SQ	SN:long_error_55_0	LN:1007
@SQ	SN:long_error_56_0	LN:1006
@SQ	SN:long_error_57_0	LN:1000
@SQ	SN:long_error_58_0	LN:1000
@SQ	SN:long_error_59_0	LN:1000
@SQ	SN:long_error_60_0	LN:999
@SQ	SN:long_error_61_0	LN:1006
@SQ	SN:long_error_62_0	LN:1008
@SQ	SN:long_error_63_0	LN:1012
@SQ	SN:long_error_64_0	LN:1002
@SQ	SN:long_error_65_0	LN:1000
@SQ	SN:long_error_66_0	LN:1000
@SQ	SN:long_error_67_0	LN:997
@SQ	SN:long_error_68_0	LN:1000
@SQ	SN:long_error_69_0	LN:1002
@SQ	SN:long_error_70_0	LN:1002
@SQ	SN:long_error_71_0	LN:1000
@SQ	SN:long_error_72_0	LN:1006
@SQ	SN:long_error_73_0	LN:1001
@SQ	SN:long_error_74_0	LN:999
@SQ	SN:long_error_75_0	LN:1000
@SQ	SN:long_error_76_0	LN:999
@SQ	SN:long_error_77_0	LN:1001
@SQ	SN:long_error_78_0	LN:1001
@SQ	SN:long_error_79_0	LN:1000
@SQ	SN:long_error_80_0	LN:1005
@SQ	SN:long_error_81_0	LN:1000
@SQ	SN:long_error_82_0	LN:998
@SQ	SN:long_error_83_0	LN:1000
@SQ	SN:long_error_84_0	LN:1000
@SQ	SN:long_error_85_0	LN:1001
@SQ	SN:long_error_86_0	LN:1000
@SQ	SN:long_error_87_0	LN:1000
@SQ	SN:long_error_88_0	LN:999
@SQ	SN:long_error_89_0	LN:1000
@SQ	SN:long_error_90_0	LN:1002
@SQ	SN:long_error_91_0	LN:996
@SQ	SN:long_error_92_0	LN:1001
@SQ	SN:long_error_93_0	LN:1003
@SQ	SN:long_error_94_0	LN:1000
@SQ	SN:long_error_95_0	LN:1004
@SQ	SN:long_error_96_0	LN:999
@SQ	SN:long_error_97_0	LN:1000
@SQ	SN:long_error_98_0	LN:1000
@SQ	SN:long_error_99_0	LN:1001
@SQ	SN:long_error_100_0	LN:1003
@SQ	SN:long_error_101_0	LN:1000
@SQ	SN:long_error_102_0	LN:1010
@SQ	SN:long_error_103_0	LN:1001
@SQ	SN:long_error_104_0	LN:1001
@SQ	SN:long_error_105_0	LN:1001
@SQ	SN:long_error_106_0	LN:1000
@SQ	SN:long_error_107_0	LN:1000
@SQ	SN:long_error_108_0	LN:1004
@SQ	SN:long_error_109_0	LN:1000
@SQ	SN:long_error_110_0	LN:1006
@SQ	SN:long_error_111_0	LN:999
@SQ	SN:long_error_112_0	LN:1000
@SQ	SN:long_error_113_0	LN:1002
@SQ	SN:long_error_114_0	LN:999
@SQ	SN:long_error_115_0	LN:1005
@SQ	SN:long_error_116_0	LN:1000
@SQ	SN:long_error_117_0	LN:1001
@SQ	SN:long_error_118_0	LN:1002
@SQ	SN:long_error_119_0	LN:1004
@PG	ID:bwa	PN:bwa	VN:0.7.10-r960-dirty	CL:/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../util/bwa/bwa-proovread mem -b 20 -l 600 -D .75 -t 4 -O 15,19 -A 5 -L 30,30 -B 13 -W 18 -r 1.5 -k 17 -T 4 -E 3,3 -a -w 30 -Y pr-Fa/bwa-sr-3/pr-Fa.unmasked.fa /dev/fd/0

**Comment by thackl** [comment]
Weird Indeed. Not sure how this can happen. Probably not really an issue of proovread, but let's see...
1) Can you delete the sample output, and run it again. Just to see if this is a persistent problem, or maybe just a one-time glitch. Check the time stamps again.
2) Does the second command (maybe better run like this: `samtools view -H pr-Fa/bwa-sr-finish/pr-Fa.bam >/dev/null`, we don't care about the output) give the same warning as proovread, i.e. index file too old?

**Comment by laure182** [comment]
Ok, I delete the sample output and rerun. There is still the same error. When I run Samtools view I don't have the error. I read here (https://groups.google.com/forum/#!topic/deeptools/mNogU_INUd4) that this issue can't be linked to the cluster system. Do you think adding a samtools index command should help ?

**Comment by laure182** [comment]
Or maybe just a `touch file.bam.bai` could do the trick ?

**Comment by laure182** [comment]
I added a `touch` on the bam.bai file in the beginning of the function `correct_sr_mt` and it's working...

**Comment by thackl** [comment]
Perfect! Let me know, if you run into any other problems. Btw, great avatar.
