### ISSUE TITLE
Long read pacbio ID Issue

### ISSUE THREAD

**Issue by rakeshponnala** [BioInf-Wuerzburg/proovread#9]
Dear Thomas,

I hope your well. I’ve attempted to use proovread to correct long pacbio reads with the help of illumine short reads. However, during the process proovread main command throws up an error   I‘m kind of puzzled to fix this error. I tried all possible options but haven’t been successful so far. Any thoughts/help? I’ve pasted the command line used, an error log and the head of pacbio sequence. 

Command line:
nohup proovread -t 10 -l /home/ponnar02/data/horn_polled_106H02754/abyss_paired_end_short_assembly/blasr_mapping_to_short_assembly/chr1_longreads_unmapped_longreads.standard.fasta -u /home/ponnar02/data/horn_polled_106H02754/ectools_paired_end_test3/9-terminator/paired_short_Assembly_test3.utg.fasta -s /home/ponnar02/data/horn_polled_106H02754/ectools_paired_end/chr1_unmap_pair_R1.fastq -s /home/ponnar02/data/horn_polled_106H02754/ectools_paired_end/chr1_unmap_pair_R2.fastq -p proovread_long_ec_test1

Error message:

[Wed Jul 22 19:37:58 2015] Running proovread-2.13.6
[Wed Jul 22 19:37:58 2015] Reading core config
[Wed Jul 22 19:37:58 2015] Reading command line options
[Wed Jul 22 19:37:58 2015] Logging parameter to `proovread_long_ec_test1/proovre
ad_long_ec_test1.parameter.log`
[Wed Jul 22 19:37:58 2015] Checking short read files

chr1_unmap_pair_R1.fastq
  Detected FASTQ format
  Estimated short read length: 98 +-11
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 18.8M

chr1_unmap_pair_R2.fastq
  Detected FASTQ format
  Estimated short read length: 98 +-10
  Etimated short read quality offset: 33
  Estimating approximate number of short reads: 18.9M

[Wed Jul 22 19:38:42 2015] Checking alternative read files

paired_short_Assembly_test3.utg.fasta
  Detected FASTA format
  Estimating fragment length: 350 +-469
  Estimating approximate number of fragments: 726k

[Wed Jul 22 19:38:42 2015] Checking required binaries

  [ok] samtools-1.2    /home/ponnar02/apps/samtools-1.2
  [ok] bwa-proovread   /home/ponnar02/apps/proovread/bin/../util/bwa
  [ok] blasr           /home/ponnar02/apps/proovread/bin/../util/blasr-1.3.1
  [ok] blastn-2.2.31   /home/ponnar02/apps/ncbi-blast-2.2.31+/bin

[Wed Jul 22 19:38:42 2015] Running mode: sr+utg
[Wed Jul 22 19:38:42 2015] Preparing long reads
#------------------------------------------------------------------------------#
[Wed Jul 22 19:38:42 2015] Non-unique long read id (m150324_081013_42145_c100787
772550000001823173008251523_s1_p0/19733) in /home/ponnar02/data/horn_polled_106H
02754/abyss_paired_end_short_assembly/blasr_mapping_to_short_assembly/chr1_longr
eads_unmapped_longreads.standard.fasta
        Exited at 'main'
        '/home/ponnar02/apps/proovread/bin/proovread', line 1393
Last call 'main::read_long'
        '/home/ponnar02/apps/proovread/bin/proovread', line 713                                                     

Pacbio head(fasta file):

>m150324_081013_42145_c100787772550000001823173008251523_s1_p0/19733
GACACTGAAGAGACTTGGAAAGAGAAGGGAAGCCAAATAAACAAGAGAGGAAACACACTCTAAGAAGTGACAGATCCACAAGATTAAAACCTGTAGTTTAAAATTGACTAAGTATGGGGGCCTAATGACCTTGAGTATTTGCTCAAGTGAACAAGAACTAACTGAAATTGAACTGACCCCCACGGTCTGCCACAACAGCTCCAGAAGAAAATTCCTAGATATTAGTTTTTACATTATCAACTTTTTAAGTTGTTTTCATTTTAAGTTATTTATTGGCCCTTCAATTATTTTTATAGCCTACTATTACATTGCAAAAAAAGGACCCATTTTCTAAAAGAGAATTTCATATATATATTAAGTTCAATAATTTTTTTATGATTGAGTTATTTGTATTAATATTGTAAGTTTTTGAGAGTGTAACCTCGTAACTGCTAGATCTTAATCTTGCTTTTGTGTATTTCTTATCACAGTTTTGTACCTTCTCTAAGAATCTAATCTGCAGTTCATTTTCTCTTAAGGGGTGTGATTAACTGGCTTTATTGTCTCTCCTCTTTTTGACTCTCCCTTTCTCTCCCCAGTCAAGCTCTTCCTCCCTCCCCTTCTCTCTCTTAACTTCACTCTGTGAATCTCTAGGGGTCTGAGCTGGTAGGAAACACTAGGGAACTGATTATGCTAGATCAGTCTCCCCTTGACTGCATTCTCTCTCTCCTGGTCCCTCTCATCTCCTCTCCCTCTTCTTCTTTCCTGGTACTCTGTGAAATCCTCTGGTGGTCAGACTGTGGTGTGAGCAACATATAGGGAAGTGATTATAGCTAGATTGCCTGGTTACCTGTTGACTGTCCCCCCTCCCGCTTCTCTCTCCTGGTCTCTAGTCTCTCATCCTTCTCTCTTCTCCATATATTAACTCTGTGAACCTCTCTGGTCTCCCTTAGTGGAAATTGTTTCACCATTAACCTAGAAGGTTTACCTCTGTGCTGTAGATGGAGAAGTCTTAAGCGCTATGTAAAGACATAAGATGAAAGTGTAGAGACAGGTAGATTAAATCCAAAACTGCTGAGAACCAAGGAAACTCCGCAGAACATTATAAATCCAAAGCTCATACCCAAAAGCTCCAAGCCTACACGGAACACAAGCTCCAATCAACGAGCCAACATATTCCAGATACAGACTAGATTACATGCCCTAATCTCCAACAACATAGGAGAAGCATAAGC

**Comment by thackl** [comment]
Hi Rakesh,

it seems taht you have duplicates in your long read fasta file. Could you check

```bash
grep '^>' /home/ponnar02/data/horn_polled_106H02754/\
abyss_paired_end_short_assembly/blasr_mapping_to_short_assembly\
/chr1_longreads_unmapped_longreads.standard.fasta | uniq -cd

**Comment by rakeshponnala** [comment]
Hello Thomas, 
Yes. There are duplicates in the fasta file. You recommend having only unique long reads in the file for proovread to work?
Thanks
Rakesh

**Comment by thackl** [comment]
proovread uses the ID to internally uniquely identify the reads. Therefore, duplicate IDs won't work.

If your reads are real duplicates (identical sequence), than correcting the duplicates would only increase the work-load, that wouldn't make sense anyways.

Duplicate IDs for different PacBio reads, however, shouldn't occur with standard PacBio names. But if that is the case with your data, something might be off.

On a side note, your read IDs don't seem to be subread IDs - missing subread coordinates at the end of the ids (m15...3_s1_p0/19733/FROM_TO). You should split your raw pacbio reads into subreads first before correction.

**Comment by rakeshponnala** [comment]
Hello,

Thanks. Yes, the reads in the FASTA file where extracted from the alignment
file. I think during the aligment, the reads ID were probably not labelled
completely by the aligner. I did remove the duplicate reads ( weren't that
many) from the FASTA file and now that the new FASTA has unique headers in
the newly created fasta file... Seems to be running as of now... Thanks for
the comments. Appreciated very much
Regards,
RP

**Comment by thackl** [comment]
I'm assuming you did not run into any more problems related to the topic and you successfully ran proovread.

Cheers

**Comment by rakeshponnala** [comment]
Thank you. Yes I did. Thanks thomas
