### ISSUE TITLE
BLAST engine error: Warning: Sequence contains no data, [siamaera] Blast exited with error: 768

### ISSUE THREAD

**Issue by cmor2207** [BioInf-Wuerzburg/proovread#91]
Hi there and happy new year!

I have been tryiong to run proovread on pacbio chunks of 1Gb (high mem cluster), using short reads normalized at 40X coverage. All goes well until one of the last steps, when creating the trimmed file and I get the message:

_perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/../\
lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/SeqFi\
lter --in proovread_1200/proovread_1200.untrimmed.fq --min-length 500 --phred-o\
ffset 33 --substr proovread_1200/proovread_1200.chim.tsv --trim-win 12,5 --out \ - | perl -I/home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin\
/../lib/ /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/s\
iamaera > proovread_1200/proovread_1200.trimmed.fq
[01:18:40] /home12/caparmor/bioinfo/tools/anaconda/envs/proovread/proovread/bin/
SeqFilter-1.06
[01:18:40] --in: proovread_1200/proovread_1200.untrimmed.fq
[01:18:40] Detected FASTQ format, phred-offset 33
[01:18:40] --substr-file: proovread_1200/proovread_1200.chim.tsv
    0  [    ] BLAST engine error: Warning: Sequence contains no data 
[17-01-18 01:18:57] [siamaera] Blast exited with error: 768_

Everything else in the run is relatively ok. 

Running task bwa-sr-1
Masked : 71.2%
Running task bwa-sr-2
Masked : 83.9%
Running task bwa-sr-3
Masked : 87.2%
Running task bwa-sr-4
Masked : 92.6%
Masked > 92% total - skipping all but last iteration
Masked : 82.4%

Here are the size of the files:
-rw-rw-r-- 1  bioinfo 1.2M Jan 18 01:18 proovread_1200.chim.tsv
-rw-rw-r-- 1  bioinfo  81K Jan 11 01:51 proovread_1200.ignored.tsv
-rw-rw-r-- 1  bioinfo  23K Jan 11 02:04 proovread_1200.parameter.log
-rw-rw-r-- 1  bioinfo 1.6M Jan 18 01:18 proovread_1200.trimmed.fa
-rw-rw-r-- 1  bioinfo 3.1M Jan 18 01:18 proovread_1200.trimmed.fq
-rw-rw-r-- 1  bioinfo 848M Jan 18 01:18 proovread_1200.untrimmed.fq

It took 5 to 6 days to run, but it is a big file, and I let the masking threshold at 92%, so I know I can lower it a bit to get it faster. Here are the specificities of all bwa-sr steps.

I thus started with:
_#------------------------------------------------------------------------------#
[01:51:59] Input
[01:51:59] Sequences            83659 #
[01:51:59] Total            573045932 bp
[01:51:59] Longest              53461 bp
[01:51:59] Shortest               254 bp
[01:51:59] N50                  11058 bp
[01:51:59] N90                   3346 bp
#------------------------------------------------------------------------------#_

and finished with:
_#------------------------------------------------------------------------------#
[01:18:58] Input
[01:18:58] Sequences              478 #
[01:18:58] Total              1567044 bp
[01:18:58] Longest              20511 bp
[01:18:58] Shortest                45 bp
[01:18:58] N50                   5350 bp
[01:18:58] N90                   1409 bp
#------------------------------------------------------------------------------#_

Percentage masked and the N50 data are sort of ok (though the final N50 could be a bit higher, I guess it is biased by the fact it is only calculated on 478 sequences).

Do you know what is going on?

Cheers

Celine

**Comment by thackl** [comment]
Hi Celine,

I'm not sure what is going wrong there. I agree, the initial steps look 
fine. Would it be possible to share a part of the file that crashed - 
looks like sequence 479 failed, so maybe the first 500 reads from 
proovread_1200/proovread_1200.untrimmed.fq, so I can reproduce the issue?

Cheers
Thomas

**Comment by thackl** [comment]
OK, this seems to be a common and recent problem - see Miquel's post (#90) for further discussion
