### ISSUE TITLE
can't find ccseq-mKxJ3.fq.idx.log

### ISSUE THREAD

**Issue by zhoujiebioinf** [BioInf-Wuerzburg/proovread#92]
HI:
I run the command like this: 
../bin/proovread -l /data3/zhoulab/cotton/2016WLZsubreads/pb-001.fq -s /data3/zhoulab/cotton/20160505BMK2fq/Anther_R1.fastq --pre /data3/zhoulab/cotton/run_proovread/test  -c --overwrite

after checking reads ,I got the  following errors:

#------------------------------------------------------------------------------#
perl -I/data3/zhoulab/cotton/bin/proovread/bin/../lib/ /data3/zhoulab/cotton/bi\
n/proovread/bin/ccseq --bwa-path /data3/zhoulab/cotton/bin/proovread/bin/../uti\
l/bwa/ --threads 4 --pre test/ccs-1 <test/read-long/test.fq | tee test/ccs-1/te\
st.fq | perl -I/data3/zhoulab/cotton/bin/proovread/bin/../lib/ /data3/zhoulab/c\
otton/bin/proovread/bin/SeqFilter --line-width 80 --phred-offset 33 --phred-mas\
k 20,41,126,205,60,0.7 --fasta --out test/ccs-1/test.masked.fa --base-content N\
 --tsv - --quiet
[17-01-18 23:04:43] [ccseq] Reading STDIN
Can't open test/ccs-1/ccseq-mKxJ3.fq.idx.log: No such file or directory at /data3/zhoulab/cotton/bin/proovread/bin/ccseq line 377.
[17-01-18 23:04:57] [ccseq] bwa failed: -1
Use of uninitialized value $c in ord at /data3/zhoulab/cotton/bin/proovread/bin/../lib/Fastq/Parser.pm line 355.
Use of uninitialized value $c in string eq at /data3/zhoulab/cotton/bin/proovread/bin/../lib/Fastq/Parser.pm line 359.
Fasta::Parser::check_format: Format checking only works at the start of the file at /data3/zhoulab/cotton/bin/proovread/bin/../lib/Fasta/Parser.pm line 151.
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
  ccseq failed: 2304

	Exited at 'main'
	'../bin/proovread', line 890

I don't know where is wrong.

**Comment by thackl** [comment]
there seems to be something off with the paths - the command you submitted has an absolute --pre, while the ccseq command uses a relative --pre. I'm currently at a conference, but I try to have a look at it as soon as possible.

**Comment by zhoujiebioinf** [comment]
It works. Thank you！
