### ISSUE TITLE
Can siamaera be used for raw pacbio reads?

### ISSUE THREAD

**Issue by danshu** [BioInf-Wuerzburg/proovread#98]
Hi,

May I ask if  it is possible to run siamaera on raw pacbio reads?

Best,
Danshu

**Comment by thackl** [comment]
Not really. It is based on aligning the read against its reverse-complement, and the errors in raw reads obscure good overlaps.

Cheers
Thomas

**Comment by danshu** [comment]
Can I set -y/--all-min-idy to lower values (e.g. 0.75) to account high error rates of raw reads?

Best,
Danshu

**Comment by thackl** [comment]
Hi,

yes, you can certainly try that. You might run into a few problems, though:

- you will have a lot more false negatives and positives
- the alignment scoring parameter (match/mismatch/gap costs) used with 
blast won't fit well with the mostly InDel errors of the PacBio reads.

Sorry I can't be of more help here. I just haven't done a lot of testing 
with raw reads...

Cheers
Thomas

**Comment by danshu** [comment]
Thanks!
