### ISSUE TITLE
Conflicting BLAST installations?! 

### ISSUE THREAD

**Issue by eldariont** [BioInf-Wuerzburg/proovread#99]
Hi,
when I run `make sample` I get the following error:

```
[12:01:16] --in: sample-results/sample-results.untrimmed.fq
[12:01:16] Detected FASTQ format, phred-offset 33
[12:01:16] --substr-file: sample-results/sample-results.chim.tsv
 6.17k [=>                                                        ]FATAL:  Argument 1 ("-subject") is not recognized or is improperly formed.
EXIT CODE 5
[17-04-07 12:01:16] [siamaera] Blast exited with error: 1280 BLASTN 2.0MP-WashU [04-May-2006] [linux26-x64-I32LPF64 2006-05-10T17:22:28]
```

Apparently, the blast subroutine in `siamaera` is causing this. On my machine, an old version of blastn is installed at `/usr/local/package/bin/blastn`. For proovread, I installed the current version into another location and referenced it in the `proovread.cfg`. But it seems that the subroutine does not call the version from the .cfg but the standard version in `/usr/local/package/bin/`. Is that correct?

Linux
Perl v5.12.1

**Comment by thackl** [comment]
Hi David,

you're absolutely right - that's a bug. It looks like the 'blast-path` from the config is not correctly propagated to the siamera call. Instead it always takes the blast from PATH. I very busy today, I'm gonna try and fix that on the weekend.

A quick fix for now should be to just put the new blast install location in the $PATH before running proovread, i.e. try:

``` sh
export PATH=/path/to/new/blast/:$PATH
proovread --sample
```
